-- Gerado automaticamente pelo skill_parser.py

CREATE TABLE IF NOT EXISTS skills (
    id          BIGINT PRIMARY KEY,
    aegis_name  VARCHAR(100) NOT NULL,
    name        VARCHAR(150),
    type        VARCHAR(100)
);

INSERT INTO skills (id, aegis_name, name, type) VALUES
  (1, 'NV_BASIC', 'Basic Skill', ''),
  (2, 'SM_SWORD', 'Sword Mastery', ''),
  (3, 'SM_TWOHAND', 'Two-Handed Sword Mastery', ''),
  (4, 'SM_RECOVERY', 'Increase HP Recovery', ''),
  (5, 'SM_BASH', 'Bash', ''),
  (6, 'SM_PROVOKE', 'Provoke', ''),
  (7, 'SM_MAGNUM', 'Magnum Break', ''),
  (8, 'SM_ENDURE', 'Endure', ''),
  (9, 'MG_SRECOVERY', 'Increase SP Recovery', ''),
  (10, 'MG_SIGHT', 'Sight', ''),
  (11, 'MG_NAPALMBEAT', 'Napalm Beat', ''),
  (12, 'MG_SAFETYWALL', 'Safety Wall', ''),
  (13, 'MG_SOULSTRIKE', 'Soul Strike', ''),
  (14, 'MG_COLDBOLT', 'Cold Bolt', ''),
  (15, 'MG_FROSTDIVER', 'Frost Diver', ''),
  (16, 'MG_STONECURSE', 'Stone Curse', ''),
  (17, 'MG_FIREBALL', 'Fire Ball', ''),
  (18, 'MG_FIREWALL', 'Fire Wall', ''),
  (19, 'MG_FIREBOLT', 'Fire Bolt', ''),
  (20, 'MG_LIGHTNINGBOLT', 'Lightning Bolt', ''),
  (21, 'MG_THUNDERSTORM', 'Thunderstorm', ''),
  (22, 'AL_DP', 'Divine Protection', ''),
  (23, 'AL_DEMONBANE', 'Demon Bane', ''),
  (24, 'AL_RUWACH', 'Ruwach', ''),
  (25, 'AL_PNEUMA', 'Pneuma', ''),
  (26, 'AL_TELEPORT', 'Teleport', ''),
  (27, 'AL_WARP', 'Warp Portal', ''),
  (28, 'AL_HEAL', 'Heal', ''),
  (29, 'AL_INCAGI', 'Increase AGI', ''),
  (30, 'AL_DECAGI', 'Decrease AGI', ''),
  (31, 'AL_HOLYWATER', 'Aqua Benedicta', ''),
  (32, 'AL_CRUCIS', 'Signum Crucis', ''),
  (33, 'AL_ANGELUS', 'Angelus', ''),
  (34, 'AL_BLESSING', 'Blessing', ''),
  (35, 'AL_CURE', 'Cure', ''),
  (36, 'MC_INCCARRY', 'Enlarge Weight Limit', ''),
  (37, 'MC_DISCOUNT', 'Discount', ''),
  (38, 'MC_OVERCHARGE', 'Overcharge', ''),
  (39, 'MC_PUSHCART', 'Pushcart', ''),
  (40, 'MC_IDENTIFY', 'Item Appraisal', ''),
  (41, 'MC_VENDING', 'Vending', ''),
  (42, 'MC_MAMMONITE', 'Mammonite', ''),
  (43, 'AC_OWL', 'Owl''s Eye', ''),
  (44, 'AC_VULTURE', 'Vulture''s Eye', ''),
  (45, 'AC_CONCENTRATION', 'Improve Concentration', ''),
  (46, 'AC_DOUBLE', 'Double Strafe', ''),
  (47, 'AC_SHOWER', 'Arrow Shower', ''),
  (48, 'TF_DOUBLE', 'Double Attack', ''),
  (49, 'TF_MISS', 'Improve Dodge', ''),
  (50, 'TF_STEAL', 'Steal', ''),
  (51, 'TF_HIDING', 'Hiding', ''),
  (52, 'TF_POISON', 'Envenom', ''),
  (53, 'TF_DETOXIFY', 'Detoxify', ''),
  (54, 'ALL_RESURRECTION', 'Resurrection', ''),
  (55, 'KN_SPEARMASTERY', 'Spear Mastery', ''),
  (56, 'KN_PIERCE', 'Pierce', ''),
  (57, 'KN_BRANDISHSPEAR', 'Brandish Spear', ''),
  (58, 'KN_SPEARSTAB', 'Spear Stab', ''),
  (59, 'KN_SPEARBOOMERANG', 'Spear Boomerang', ''),
  (60, 'KN_TWOHANDQUICKEN', 'Twohand Quicken', ''),
  (61, 'KN_AUTOCOUNTER', 'Counter Attack', ''),
  (62, 'KN_BOWLINGBASH', 'Bowling Bash', ''),
  (63, 'KN_RIDING', 'Peco Peco Riding', ''),
  (64, 'KN_CAVALIERMASTERY', 'Cavalier Mastery', ''),
  (65, 'PR_MACEMASTERY', 'Mace Mastery', ''),
  (66, 'PR_IMPOSITIO', 'Impositio Manus', ''),
  (67, 'PR_SUFFRAGIUM', 'Suffragium', ''),
  (68, 'PR_ASPERSIO', 'Aspersio', ''),
  (69, 'PR_BENEDICTIO', 'B.S. Sacramenti', ''),
  (70, 'PR_SANCTUARY', 'Sanctuary', ''),
  (71, 'PR_SLOWPOISON', 'Slow Poison', ''),
  (72, 'PR_STRECOVERY', 'Status Recovery', ''),
  (73, 'PR_KYRIE', 'Kyrie Eleison', ''),
  (74, 'PR_MAGNIFICAT', 'Magnificat', ''),
  (75, 'PR_GLORIA', 'Gloria', ''),
  (76, 'PR_LEXDIVINA', 'Lex Divina', ''),
  (77, 'PR_TURNUNDEAD', 'Turn Undead', ''),
  (78, 'PR_LEXAETERNA', 'Lex Aeterna', ''),
  (79, 'PR_MAGNUS', 'Magnus Exorcismus', ''),
  (80, 'WZ_FIREPILLAR', 'Fire Pillar', ''),
  (81, 'WZ_SIGHTRASHER', 'Sightrasher', ''),
  (83, 'WZ_METEOR', 'Meteor Storm', ''),
  (84, 'WZ_JUPITEL', 'Jupitel Thunder', ''),
  (85, 'WZ_VERMILION', 'Lord of Vermilion', ''),
  (86, 'WZ_WATERBALL', 'Water Ball', ''),
  (87, 'WZ_ICEWALL', 'Ice Wall', ''),
  (88, 'WZ_FROSTNOVA', 'Frost Nova', ''),
  (89, 'WZ_STORMGUST', 'Storm Gust', ''),
  (90, 'WZ_EARTHSPIKE', 'Earth Spike', ''),
  (91, 'WZ_HEAVENDRIVE', 'Heaven''s Drive', ''),
  (92, 'WZ_QUAGMIRE', 'Quagmire', ''),
  (93, 'WZ_ESTIMATION', 'Sense', ''),
  (94, 'BS_IRON', 'Iron Tempering', ''),
  (95, 'BS_STEEL', 'Steel Tempering', ''),
  (96, 'BS_ENCHANTEDSTONE', 'Enchanted Stone Craft', ''),
  (97, 'BS_ORIDEOCON', 'Oridecon Research', ''),
  (98, 'BS_DAGGER', 'Smith Dagger', ''),
  (99, 'BS_SWORD', 'Smith Sword', ''),
  (100, 'BS_TWOHANDSWORD', 'Smith Two-handed Sword', ''),
  (101, 'BS_AXE', 'Smith Axe', ''),
  (102, 'BS_MACE', 'Smith Mace', ''),
  (103, 'BS_KNUCKLE', 'Smith Knucklebrace', ''),
  (104, 'BS_SPEAR', 'Smith Spear', ''),
  (105, 'BS_HILTBINDING', 'Hilt Binding', ''),
  (106, 'BS_FINDINGORE', 'Ore Discovery', ''),
  (107, 'BS_WEAPONRESEARCH', 'Weaponry Research', ''),
  (108, 'BS_REPAIRWEAPON', 'Weapon Repair', ''),
  (109, 'BS_SKINTEMPER', 'Skin Tempering', ''),
  (110, 'BS_HAMMERFALL', 'Hammer Fall', ''),
  (111, 'BS_ADRENALINE', 'Adrenaline Rush', ''),
  (112, 'BS_WEAPONPERFECT', 'Weapon Perfection', ''),
  (113, 'BS_OVERTHRUST', 'Power-Thrust', ''),
  (114, 'BS_MAXIMIZE', 'Maximize Power', ''),
  (115, 'HT_SKIDTRAP', 'Skid Trap', ''),
  (116, 'HT_LANDMINE', 'Land Mine', ''),
  (117, 'HT_ANKLESNARE', 'Ankle Snare', ''),
  (118, 'HT_SHOCKWAVE', 'Shockwave Trap', ''),
  (119, 'HT_SANDMAN', 'Sandman', ''),
  (120, 'HT_FLASHER', 'Flasher', ''),
  (121, 'HT_FREEZINGTRAP', 'Freezing Trap', ''),
  (122, 'HT_BLASTMINE', 'Blast Mine', ''),
  (123, 'HT_CLAYMORETRAP', 'Claymore Trap', ''),
  (124, 'HT_REMOVETRAP', 'Remove Trap', ''),
  (125, 'HT_TALKIEBOX', 'Talkie Box', ''),
  (126, 'HT_BEASTBANE', 'Beast Bane', ''),
  (127, 'HT_FALCON', 'Falconry Mastery', ''),
  (128, 'HT_STEELCROW', 'Steel Crow', ''),
  (129, 'HT_BLITZBEAT', 'Blitz Beat', ''),
  (130, 'HT_DETECTING', 'Detect', ''),
  (131, 'HT_SPRINGTRAP', 'Spring Trap', ''),
  (132, 'AS_RIGHT', 'Righthand Mastery', ''),
  (133, 'AS_LEFT', 'Lefthand Mastery', ''),
  (134, 'AS_KATAR', 'Katar Mastery', ''),
  (135, 'AS_CLOAKING', 'Cloaking', ''),
  (136, 'AS_SONICBLOW', 'Sonic Blow', ''),
  (137, 'AS_GRIMTOOTH', 'Grimtooth', ''),
  (138, 'AS_ENCHANTPOISON', 'Enchant Poison', ''),
  (139, 'AS_POISONREACT', 'Poison React', ''),
  (140, 'AS_VENOMDUST', 'Venom Dust', ''),
  (141, 'AS_SPLASHER', 'Venom Splasher', ''),
  (142, 'NV_FIRSTAID', 'First Aid', ''),
  (143, 'NV_TRICKDEAD', 'Play Dead', ''),
  (144, 'SM_MOVINGRECOVERY', 'Moving HP-Recovery', ''),
  (145, 'SM_FATALBLOW', 'Fatal Blow', ''),
  (146, 'SM_AUTOBERSERK', 'Auto Berserk', ''),
  (147, 'AC_MAKINGARROW', 'Arrow Crafting', ''),
  (148, 'AC_CHARGEARROW', 'Arrow Repel', ''),
  (149, 'TF_SPRINKLESAND', 'Sand Attack', ''),
  (150, 'TF_BACKSLIDING', 'Back Slide', ''),
  (151, 'TF_PICKSTONE', 'Find Stone', ''),
  (152, 'TF_THROWSTONE', 'Stone Fling', ''),
  (153, 'MC_CARTREVOLUTION', 'Cart Revolution', ''),
  (154, 'MC_CHANGECART', 'Change Cart', ''),
  (155, 'MC_LOUD', 'Crazy Uproar', ''),
  (156, 'AL_HOLYLIGHT', 'Holy Light', ''),
  (157, 'MG_ENERGYCOAT', 'Energy Coat', ''),
  (158, 'NPC_PIERCINGATT', 'Piercing Attack', ''),
  (159, 'NPC_MENTALBREAKER', 'Spirit Destruction', ''),
  (160, 'NPC_RANGEATTACK', 'Stand off attack', ''),
  (161, 'NPC_ATTRICHANGE', 'Attribute Change', ''),
  (162, 'NPC_CHANGEWATER', 'Water Attribute Change', ''),
  (163, 'NPC_CHANGEGROUND', 'Earth Attribute Change', ''),
  (164, 'NPC_CHANGEFIRE', 'Fire Attribute Change', ''),
  (165, 'NPC_CHANGEWIND', 'Wind Attribute Change', ''),
  (166, 'NPC_CHANGEPOISON', 'Poison Attribute Change', ''),
  (167, 'NPC_CHANGEHOLY', 'Holy Attribute Change', ''),
  (168, 'NPC_CHANGEDARKNESS', 'Shadow Attribute Change', ''),
  (169, 'NPC_CHANGETELEKINESIS', 'Ghost Attribute Change', ''),
  (170, 'NPC_CRITICALSLASH', 'Defense disregard attack', ''),
  (171, 'NPC_COMBOATTACK', 'Multi-stage Attack', ''),
  (172, 'NPC_GUIDEDATTACK', 'Guided Attack', ''),
  (173, 'NPC_SELFDESTRUCTION', 'Suicide bombing', ''),
  (174, 'NPC_SPLASHATTACK', 'Splash attack', ''),
  (175, 'NPC_SUICIDE', 'Suicide', ''),
  (176, 'NPC_POISON', 'Poison Attack', ''),
  (177, 'NPC_BLINDATTACK', 'Blind Attack', ''),
  (178, 'NPC_SILENCEATTACK', 'Silence Attack', ''),
  (179, 'NPC_STUNATTACK', 'Stun Attack', ''),
  (180, 'NPC_PETRIFYATTACK', 'Petrify Attack', ''),
  (181, 'NPC_CURSEATTACK', 'Curse Attack', ''),
  (182, 'NPC_SLEEPATTACK', 'Sleep attack', ''),
  (183, 'NPC_RANDOMATTACK', 'Random Attack', ''),
  (184, 'NPC_WATERATTACK', 'Water Attribute Attack', ''),
  (185, 'NPC_GROUNDATTACK', 'Earth Attribute Attack', ''),
  (186, 'NPC_FIREATTACK', 'Fire Attribute Attack', ''),
  (187, 'NPC_WINDATTACK', 'Wind Attribute Attack', ''),
  (188, 'NPC_POISONATTACK', 'Poison Attribute Attack', ''),
  (189, 'NPC_HOLYATTACK', 'Holy Attribute Attack', ''),
  (190, 'NPC_DARKNESSATTACK', 'Shadow Attribute Attack', ''),
  (191, 'NPC_TELEKINESISATTACK', 'Ghost Attribute Attack', ''),
  (192, 'NPC_MAGICALATTACK', 'Demon Shock Attack', ''),
  (193, 'NPC_METAMORPHOSIS', 'Metamorphosis', ''),
  (194, 'NPC_PROVOCATION', 'Provocation', ''),
  (195, 'NPC_SMOKING', 'Smoking', ''),
  (196, 'NPC_SUMMONSLAVE', 'Follower Summons', ''),
  (197, 'NPC_EMOTION', 'Emotion', ''),
  (198, 'NPC_TRANSFORMATION', 'Transformation', ''),
  (199, 'NPC_BLOODDRAIN', 'Sucking Blood', ''),
  (200, 'NPC_ENERGYDRAIN', 'Energy Drain', ''),
  (201, 'NPC_KEEPING', 'Keeping', ''),
  (202, 'NPC_DARKBREATH', 'Dark Breath', ''),
  (203, 'NPC_DARKBLESSING', 'Dark Blessing', ''),
  (204, 'NPC_BARRIER', 'Barrier', ''),
  (205, 'NPC_DEFENDER', 'Defender', ''),
  (206, 'NPC_LICK', 'Lick', ''),
  (207, 'NPC_HALLUCINATION', 'Hallucination', ''),
  (208, 'NPC_REBIRTH', 'Rebirth', ''),
  (209, 'NPC_SUMMONMONSTER', 'Monster Summons', ''),
  (210, 'RG_SNATCHER', 'Gank', ''),
  (211, 'RG_STEALCOIN', 'Mug', ''),
  (212, 'RG_BACKSTAP', 'Back Stab', ''),
  (213, 'RG_TUNNELDRIVE', 'Stalk', ''),
  (214, 'RG_RAID', 'Sightless Mind', ''),
  (215, 'RG_STRIPWEAPON', 'Divest Weapon', ''),
  (216, 'RG_STRIPSHIELD', 'Divest Shield', ''),
  (217, 'RG_STRIPARMOR', 'Divest Armor', ''),
  (218, 'RG_STRIPHELM', 'Divest Helm', ''),
  (219, 'RG_INTIMIDATE', 'Snatch', ''),
  (220, 'RG_GRAFFITI', 'Scribble', ''),
  (221, 'RG_FLAGGRAFFITI', 'Piece', ''),
  (222, 'RG_CLEANER', 'Remover', ''),
  (223, 'RG_GANGSTER', 'Slyness', ''),
  (224, 'RG_COMPULSION', 'Haggle', ''),
  (225, 'RG_PLAGIARISM', 'Intimidate', ''),
  (226, 'AM_AXEMASTERY', 'Axe Mastery', ''),
  (227, 'AM_LEARNINGPOTION', 'Potion Research', ''),
  (228, 'AM_PHARMACY', 'Prepare Potion', ''),
  (229, 'AM_DEMONSTRATION', 'Bomb', ''),
  (230, 'AM_ACIDTERROR', 'Acid Terror', ''),
  (231, 'AM_POTIONPITCHER', 'Aid Potion', ''),
  (232, 'AM_CANNIBALIZE', 'Summon Flora', ''),
  (233, 'AM_SPHEREMINE', 'Summon Marine Sphere', ''),
  (234, 'AM_CP_WEAPON', 'Alchemical Weapon', ''),
  (235, 'AM_CP_SHIELD', 'Synthesized Shield', ''),
  (236, 'AM_CP_ARMOR', 'Synthetic Armor', ''),
  (237, 'AM_CP_HELM', 'Biochemical Helm', ''),
  (238, 'AM_BIOETHICS', 'Bioethics', ''),
  (243, 'AM_CALLHOMUN', 'Call Homunculus', ''),
  (244, 'AM_REST', 'Vaporize', ''),
  (247, 'AM_RESURRECTHOMUN', 'Homunculus Resurrection', ''),
  (248, 'CR_TRUST', 'Faith', ''),
  (249, 'CR_AUTOGUARD', 'Guard', ''),
  (250, 'CR_SHIELDCHARGE', 'Smite', ''),
  (251, 'CR_SHIELDBOOMERANG', 'Shield Boomerang', ''),
  (252, 'CR_REFLECTSHIELD', 'Shield Reflect', ''),
  (253, 'CR_HOLYCROSS', 'Holy Cross', ''),
  (254, 'CR_GRANDCROSS', 'Grand Cross', ''),
  (255, 'CR_DEVOTION', 'Sacrifice', ''),
  (256, 'CR_PROVIDENCE', 'Resistant Souls', ''),
  (257, 'CR_DEFENDER', 'Defending Aura', ''),
  (258, 'CR_SPEARQUICKEN', 'Spear Quicken', ''),
  (259, 'MO_IRONHAND', 'Iron Fists', ''),
  (260, 'MO_SPIRITSRECOVERY', 'Spiritual Cadence', ''),
  (261, 'MO_CALLSPIRITS', 'Summon Spirit Sphere', ''),
  (262, 'MO_ABSORBSPIRITS', 'Absorb Spirit Sphere', ''),
  (263, 'MO_TRIPLEATTACK', 'Raging Trifecta Blow', ''),
  (264, 'MO_BODYRELOCATION', 'Snap', ''),
  (265, 'MO_DODGE', 'Dodge', ''),
  (266, 'MO_INVESTIGATE', 'Occult Impaction', ''),
  (267, 'MO_FINGEROFFENSIVE', 'Throw Spirit Sphere', ''),
  (268, 'MO_STEELBODY', 'Mental Strength', ''),
  (269, 'MO_BLADESTOP', 'Root', ''),
  (270, 'MO_EXPLOSIONSPIRITS', 'Fury', ''),
  (271, 'MO_EXTREMITYFIST', 'Asura Strike', ''),
  (272, 'MO_CHAINCOMBO', 'Raging Quadruple Blow', ''),
  (273, 'MO_COMBOFINISH', 'Raging Thrust', ''),
  (274, 'SA_ADVANCEDBOOK', 'Study', ''),
  (275, 'SA_CASTCANCEL', 'Cast Cancel', ''),
  (276, 'SA_MAGICROD', 'Magic Rod', ''),
  (277, 'SA_SPELLBREAKER', 'Spell Breaker', ''),
  (278, 'SA_FREECAST', 'Free Cast', ''),
  (279, 'SA_AUTOSPELL', 'Hindsight', ''),
  (280, 'SA_FLAMELAUNCHER', 'Endow Blaze', ''),
  (281, 'SA_FROSTWEAPON', 'Endow Tsunami', ''),
  (282, 'SA_LIGHTNINGLOADER', 'Endow Tornado', ''),
  (283, 'SA_SEISMICWEAPON', 'Endow Quake', ''),
  (284, 'SA_DRAGONOLOGY', 'Dragonology', ''),
  (285, 'SA_VOLCANO', 'Volcano', ''),
  (286, 'SA_DELUGE', 'Deluge', ''),
  (287, 'SA_VIOLENTGALE', 'Whirlwind', ''),
  (288, 'SA_LANDPROTECTOR', 'Magnetic Earth', ''),
  (289, 'SA_DISPELL', 'Dispell', ''),
  (290, 'SA_ABRACADABRA', 'Hocus-pocus', ''),
  (291, 'SA_MONOCELL', 'Monocell', ''),
  (292, 'SA_CLASSCHANGE', 'Class Change', ''),
  (293, 'SA_SUMMONMONSTER', 'Monster Chant', ''),
  (294, 'SA_REVERSEORCISH', 'Grampus Morph', ''),
  (295, 'SA_DEATH', 'Grim Reaper', ''),
  (296, 'SA_FORTUNE', 'Gold Digger', ''),
  (297, 'SA_TAMINGMONSTER', 'Beastly Hypnosis', ''),
  (298, 'SA_QUESTION', 'Questioning', ''),
  (299, 'SA_GRAVITY', 'Gravity', ''),
  (300, 'SA_LEVELUP', 'Leveling', ''),
  (301, 'SA_INSTANTDEATH', 'Suicide', ''),
  (302, 'SA_FULLRECOVERY', 'Rejuvenation', ''),
  (303, 'SA_COMA', 'Coma', ''),
  (304, 'BD_ADAPTATION', 'Amp', ''),
  (305, 'BD_ENCORE', 'Encore', ''),
  (306, 'BD_LULLABY', 'Lullaby', ''),
  (307, 'BD_RICHMANKIM', 'Mental Sensing', ''),
  (308, 'BD_ETERNALCHAOS', 'Down Tempo', ''),
  (309, 'BD_DRUMBATTLEFIELD', 'Battle Theme', ''),
  (310, 'BD_RINGNIBELUNGEN', 'Harmonic Lick', ''),
  (311, 'BD_ROKISWEIL', 'Classical Pluck', ''),
  (312, 'BD_INTOABYSS', 'Power Chord', ''),
  (313, 'BD_SIEGFRIED', 'Acoustic Rhythm', ''),
  (315, 'BA_MUSICALLESSON', 'Music Lessons', ''),
  (316, 'BA_MUSICALSTRIKE', 'Melody Strike', ''),
  (317, 'BA_DISSONANCE', 'Unchained Serenade', ''),
  (318, 'BA_FROSTJOKER', 'Unbarring Octave', ''),
  (319, 'BA_WHISTLE', 'Perfect Tablature', ''),
  (320, 'BA_ASSASSINCROSS', 'Impressive Riff', ''),
  (321, 'BA_POEMBRAGI', 'Magic Strings', ''),
  (322, 'BA_APPLEIDUN', 'Song of Lutie', ''),
  (323, 'DC_DANCINGLESSON', 'Dance Lessons', ''),
  (324, 'DC_THROWARROW', 'Slinging Arrow', ''),
  (325, 'DC_UGLYDANCE', 'Hip Shaker', ''),
  (326, 'DC_SCREAM', 'Dazzler', ''),
  (327, 'DC_HUMMING', 'Focus Ballet', ''),
  (328, 'DC_DONTFORGETME', 'Slow Grace', ''),
  (329, 'DC_FORTUNEKISS', 'Lady Luck', ''),
  (330, 'DC_SERVICEFORYOU', 'Gypsy''s Kiss', ''),
  (331, 'NPC_RANDOMMOVE', 'Random Move', ''),
  (332, 'NPC_SPEEDUP', 'Speed UP', ''),
  (333, 'NPC_REVENGE', 'Revenge', ''),
  (334, 'WE_MALE', 'I Will Protect You', ''),
  (335, 'WE_FEMALE', 'I Look up to You', ''),
  (336, 'WE_CALLPARTNER', 'I miss You', ''),
  (337, 'ITM_TOMAHAWK', 'Throw Tomahawk', ''),
  (338, 'NPC_DARKCROSS', 'Cross of Darkness', ''),
  (339, 'NPC_GRANDDARKNESS', 'Grand cross of Darkness', ''),
  (340, 'NPC_DARKSTRIKE', 'Soul Strike of Darkness', ''),
  (341, 'NPC_DARKTHUNDER', 'Darkness Jupitel', ''),
  (342, 'NPC_STOP', 'Stop', ''),
  (343, 'NPC_WEAPONBRAKER', 'Break weapon', ''),
  (344, 'NPC_ARMORBRAKE', 'Break armor', ''),
  (345, 'NPC_HELMBRAKE', 'Break helm', ''),
  (346, 'NPC_SHIELDBRAKE', 'Break shield', ''),
  (347, 'NPC_UNDEADATTACK', 'Undead Element Attack', ''),
  (348, 'NPC_CHANGEUNDEAD', 'Undead Attribute Change', ''),
  (349, 'NPC_POWERUP', 'Power Up', ''),
  (350, 'NPC_AGIUP', 'Agility Up', ''),
  (351, 'NPC_SIEGEMODE', 'Siege Mode', ''),
  (352, 'NPC_CALLSLAVE', 'Recall Slaves', ''),
  (353, 'NPC_INVISIBLE', 'Invisible', ''),
  (354, 'NPC_RUN', 'Run', ''),
  (355, 'LK_AURABLADE', 'Aura Blade', ''),
  (356, 'LK_PARRYING', 'Parrying', ''),
  (357, 'LK_CONCENTRATION', 'Concentration', ''),
  (358, 'LK_TENSIONRELAX', 'Relax', ''),
  (359, 'LK_BERSERK', 'Frenzy', ''),
  (360, 'LK_FURY', 'Fury', ''),
  (361, 'HP_ASSUMPTIO', 'Assumptio', ''),
  (362, 'HP_BASILICA', 'Basilica', ''),
  (363, 'HP_MEDITATIO', 'Meditatio', ''),
  (364, 'HW_SOULDRAIN', 'Soul Drain', ''),
  (365, 'HW_MAGICCRASHER', 'Stave Crasher', ''),
  (366, 'HW_MAGICPOWER', 'Mystical Amplification', ''),
  (367, 'PA_PRESSURE', 'Gloria Domini', ''),
  (368, 'PA_SACRIFICE', 'Martyr''s Reckoning', ''),
  (369, 'PA_GOSPEL', 'Battle Chant', ''),
  (370, 'CH_PALMSTRIKE', 'Raging Palm Strike', ''),
  (371, 'CH_TIGERFIST', 'Glacier Fist', ''),
  (372, 'CH_CHAINCRUSH', 'Chain Crush Combo', ''),
  (373, 'PF_HPCONVERSION', 'Indulge', ''),
  (374, 'PF_SOULCHANGE', 'Soul Exhale', ''),
  (375, 'PF_SOULBURN', 'Soul Siphon', ''),
  (376, 'ASC_KATAR', 'Advanced Katar Mastery', ''),
  (378, 'ASC_EDP', 'Enchant Deadly Poison', ''),
  (379, 'ASC_BREAKER', 'Soul Destroyer', ''),
  (380, 'SN_SIGHT', 'Falcon Eyes', ''),
  (381, 'SN_FALCONASSAULT', 'Falcon Assault', ''),
  (382, 'SN_SHARPSHOOTING', 'Focused Arrow Strike', ''),
  (383, 'SN_WINDWALK', 'Wind Walker', ''),
  (384, 'WS_MELTDOWN', 'Shattering Strike', ''),
  (385, 'WS_CREATECOIN', 'Create Coins', ''),
  (386, 'WS_CREATENUGGET', 'Create Nuggets', ''),
  (387, 'WS_CARTBOOST', 'Cart Boost', ''),
  (388, 'WS_SYSTEMCREATE', 'Auto Attack System', ''),
  (389, 'ST_CHASEWALK', 'Stealth', ''),
  (390, 'ST_REJECTSWORD', 'Counter Instinct', ''),
  (392, 'CR_ALCHEMY', 'Alchemy', ''),
  (393, 'CR_SYNTHESISPOTION', 'Potion Synthesis', ''),
  (394, 'CG_ARROWVULCAN', 'Vulcan Arrow', ''),
  (395, 'CG_MOONLIT', 'Sheltering Bliss', ''),
  (396, 'CG_MARIONETTE', 'Marionette Control', ''),
  (397, 'LK_SPIRALPIERCE', 'Spiral Pierce', ''),
  (398, 'LK_HEADCRUSH', 'Traumatic Blow', ''),
  (399, 'LK_JOINTBEAT', 'Vital Strike', ''),
  (400, 'HW_NAPALMVULCAN', 'Napalm Vulcan', ''),
  (401, 'CH_SOULCOLLECT', 'Zen', ''),
  (402, 'PF_MINDBREAKER', 'Mind Breaker', ''),
  (403, 'PF_MEMORIZE', 'Foresight', ''),
  (404, 'PF_FOGWALL', 'Blinding Mist', ''),
  (405, 'PF_SPIDERWEB', 'Fiber Lock', ''),
  (406, 'ASC_METEORASSAULT', 'Meteor Assault', ''),
  (407, 'ASC_CDP', 'Create Deadly Poison', ''),
  (408, 'WE_BABY', 'Baby', ''),
  (409, 'WE_CALLPARENT', 'Call Parent', ''),
  (410, 'WE_CALLBABY', 'Call Baby', ''),
  (411, 'TK_RUN', 'Running', ''),
  (412, 'TK_READYSTORM', 'Tornado Stance', ''),
  (413, 'TK_STORMKICK', 'Tornado Kick', ''),
  (414, 'TK_READYDOWN', 'Heel Drop Stance', ''),
  (415, 'TK_DOWNKICK', 'Heel Drop', ''),
  (416, 'TK_READYTURN', 'Roundhouse Stance', ''),
  (417, 'TK_TURNKICK', 'Roundhouse Kick', ''),
  (418, 'TK_READYCOUNTER', 'Counter Kick Stance', ''),
  (419, 'TK_COUNTER', 'Counter Kick', ''),
  (420, 'TK_DODGE', 'Tumbling', ''),
  (421, 'TK_JUMPKICK', 'Flying Kick', ''),
  (422, 'TK_HPTIME', 'Peaceful Break', ''),
  (423, 'TK_SPTIME', 'Happy Break', ''),
  (424, 'TK_POWER', 'Kihop', ''),
  (425, 'TK_SEVENWIND', 'Mild Wind', ''),
  (426, 'TK_HIGHJUMP', 'Taekwon Jump', ''),
  (427, 'SG_FEEL', 'Feeling the Sun Moon and Stars', ''),
  (428, 'SG_SUN_WARM', 'Warmth of the Sun', ''),
  (429, 'SG_MOON_WARM', 'Warmth of the Moon', ''),
  (430, 'SG_STAR_WARM', 'Warmth of the Stars', ''),
  (431, 'SG_SUN_COMFORT', 'Comfort of the Sun', ''),
  (432, 'SG_MOON_COMFORT', 'Comfort of the Moon', ''),
  (433, 'SG_STAR_COMFORT', 'Comfort of the Stars', ''),
  (434, 'SG_HATE', 'Hatred of the Sun Moon and Stars', ''),
  (435, 'SG_SUN_ANGER', 'Anger of the Sun', ''),
  (436, 'SG_MOON_ANGER', 'Anger of the Moon', ''),
  (437, 'SG_STAR_ANGER', 'Anger of the Stars', ''),
  (438, 'SG_SUN_BLESS', 'Blessing of the Sun', ''),
  (439, 'SG_MOON_BLESS', 'Blessing of the Moon', ''),
  (440, 'SG_STAR_BLESS', 'Blessing of the Stars', ''),
  (441, 'SG_DEVIL', 'Demon of the Sun Moon and Stars', ''),
  (442, 'SG_FRIEND', 'Friend of the Sun Moon and Stars', ''),
  (443, 'SG_KNOWLEDGE', 'Knowledge of the Sun Moon and Stars', ''),
  (444, 'SG_FUSION', 'Union of the Sun Moon and Stars', ''),
  (445, 'SL_ALCHEMIST', 'Spirit of the Alchemist', ''),
  (446, 'AM_BERSERKPITCHER', 'Aid Berserk Potion', ''),
  (447, 'SL_MONK', 'Spirit of the Monk', ''),
  (448, 'SL_STAR', 'Spirit of the Star Gladiator', ''),
  (449, 'SL_SAGE', 'Spirit of the Sage', ''),
  (450, 'SL_CRUSADER', 'Spirit of the Crusader', ''),
  (451, 'SL_SUPERNOVICE', 'Spirit of the Supernovice', ''),
  (452, 'SL_KNIGHT', 'Spirit of the Knight', ''),
  (453, 'SL_WIZARD', 'Spirit of the Wizard', ''),
  (454, 'SL_PRIEST', 'Spirit of the Priest', ''),
  (455, 'SL_BARDDANCER', 'Spirit of the Artist', ''),
  (456, 'SL_ROGUE', 'Spirit of the Rogue', ''),
  (457, 'SL_ASSASIN', 'Spirit of the Assasin', ''),
  (458, 'SL_BLACKSMITH', 'Spirit of the Blacksmith', ''),
  (459, 'BS_ADRENALINE2', 'Advanced Adrenaline Rush', ''),
  (460, 'SL_HUNTER', 'Spirit of the Hunter', ''),
  (461, 'SL_SOULLINKER', 'Spirit of the Soul Linker', ''),
  (462, 'SL_KAIZEL', 'Kaizel', ''),
  (463, 'SL_KAAHI', 'Kaahi', ''),
  (464, 'SL_KAUPE', 'Kaupe', ''),
  (465, 'SL_KAITE', 'Kaite', ''),
  (466, 'SL_KAINA', 'Kaina', ''),
  (467, 'SL_STIN', 'Estin', ''),
  (468, 'SL_STUN', 'Estun', ''),
  (469, 'SL_SMA', 'Esma', ''),
  (470, 'SL_SWOO', 'Eswoo', ''),
  (471, 'SL_SKE', 'Eske', ''),
  (472, 'SL_SKA', 'Eska', ''),
  (473, 'SM_SELFPROVOKE', 'Provoke Self', ''),
  (474, 'NPC_EMOTION_ON', 'Emotion ON', ''),
  (475, 'ST_PRESERVE', 'Preserve', ''),
  (476, 'ST_FULLSTRIP', 'Divest All', ''),
  (477, 'WS_WEAPONREFINE', 'Upgrade Weapon', ''),
  (478, 'CR_SLIMPITCHER', 'Aid Condensed Potion', ''),
  (479, 'CR_FULLPROTECTION', 'Full Protection', ''),
  (480, 'PA_SHIELDCHAIN', 'Shield Chain', ''),
  (481, 'HP_MANARECHARGE', 'Mana Recharge', ''),
  (482, 'PF_DOUBLECASTING', 'Double Casting', ''),
  (483, 'HW_GANBANTEIN', 'Ganbantein', ''),
  (484, 'HW_GRAVITATION', 'Gravitation Field', ''),
  (485, 'WS_CARTTERMINATION', 'Cart Termination', ''),
  (486, 'WS_OVERTHRUSTMAX', 'Maximum Power Thrust', ''),
  (488, 'CG_HERMODE', 'Wand of Hermode', ''),
  (489, 'CG_TAROTCARD', 'Tarot Card of Fate', ''),
  (490, 'CR_ACIDDEMONSTRATION', 'Acid Demonstration', ''),
  (491, 'CR_CULTIVATION', 'Plant Cultivation', ''),
  (492, 'ITEM_ENCHANTARMS', 'Weapon Enchantment', ''),
  (493, 'TK_MISSION', 'Taekwon Mission', ''),
  (494, 'SL_HIGH', 'Spirit of Rebirth', ''),
  (495, 'KN_ONEHAND', 'Onehand Quicken', ''),
  (496, 'AM_TWILIGHT1', 'Twilight Alchemy 1', ''),
  (497, 'AM_TWILIGHT2', 'Twilight Alchemy 2', ''),
  (498, 'AM_TWILIGHT3', 'Twilight Alchemy 3', ''),
  (499, 'HT_POWER', 'Beast Strafing', ''),
  (500, 'GS_GLITTERING', 'Flip the Coin', ''),
  (501, 'GS_FLING', 'Fling', ''),
  (502, 'GS_TRIPLEACTION', 'Triple Action', ''),
  (503, 'GS_BULLSEYE', 'Bulls Eye', ''),
  (504, 'GS_MADNESSCANCEL', 'Madness Canceller', ''),
  (505, 'GS_ADJUSTMENT', 'Adjustment', ''),
  (506, 'GS_INCREASING', 'Increasing Accuracy', ''),
  (507, 'GS_MAGICALBULLET', 'Magical Bullet', ''),
  (508, 'GS_CRACKER', 'Cracker', ''),
  (509, 'GS_SINGLEACTION', 'Single Action', ''),
  (510, 'GS_SNAKEEYE', 'Snake Eye', ''),
  (511, 'GS_CHAINACTION', 'Chain Action', ''),
  (512, 'GS_TRACKING', 'Tracking', ''),
  (513, 'GS_DISARM', 'Disarm', ''),
  (514, 'GS_PIERCINGSHOT', 'Piercing Shot', ''),
  (515, 'GS_RAPIDSHOWER', 'Rapid Shower', ''),
  (516, 'GS_DESPERADO', 'Desperado', ''),
  (517, 'GS_GATLINGFEVER', 'Gatling Fever', ''),
  (518, 'GS_DUST', 'Dust', ''),
  (519, 'GS_FULLBUSTER', 'Full Buster', ''),
  (520, 'GS_SPREADATTACK', 'Spread Attack', ''),
  (521, 'GS_GROUNDDRIFT', 'Ground Drift', ''),
  (522, 'NJ_TOBIDOUGU', 'Shuriken Training', ''),
  (523, 'NJ_SYURIKEN', 'Throw Shuriken', ''),
  (524, 'NJ_KUNAI', 'Throw Kunai', ''),
  (525, 'NJ_HUUMA', 'Throw Huuma Shuriken', ''),
  (526, 'NJ_ZENYNAGE', 'Throw Zeny', ''),
  (527, 'NJ_TATAMIGAESHI', 'Improvised Defense', ''),
  (528, 'NJ_KASUMIKIRI', 'Vanishing Slash', ''),
  (529, 'NJ_SHADOWJUMP', 'Shadow Leap', ''),
  (530, 'NJ_KIRIKAGE', 'Shadow Slash', ''),
  (531, 'NJ_UTSUSEMI', 'Cicada Skin Sheeding', ''),
  (532, 'NJ_BUNSINJYUTSU', 'Mirror Image', ''),
  (533, 'NJ_NINPOU', 'Spirit of the Blade', ''),
  (534, 'NJ_KOUENKA', 'Crimson Fire Petal', ''),
  (535, 'NJ_KAENSIN', 'Crimson Fire Formation', ''),
  (536, 'NJ_BAKUENRYU', 'Raging Fire Dragon', ''),
  (537, 'NJ_HYOUSENSOU', 'Spear of Ice', ''),
  (538, 'NJ_SUITON', 'Hidden Water', ''),
  (539, 'NJ_HYOUSYOURAKU', 'Ice Meteor', ''),
  (540, 'NJ_HUUJIN', 'Wind Blade', ''),
  (541, 'NJ_RAIGEKISAI', 'Lightning Strike of Destruction', ''),
  (542, 'NJ_KAMAITACHI', 'Kamaitachi', ''),
  (543, 'NJ_NEN', 'Soul', ''),
  (544, 'NJ_ISSEN', 'Final Strike', ''),
  (572, 'SL_DEATHKNIGHT', 'SL_DEATHKNIGHT', ''),
  (573, 'SL_COLLECTOR', 'SL_COLLECTOR', ''),
  (574, 'SL_NINJA', 'SL_NINJA', ''),
  (575, 'SL_GUNNER', 'SL_GUNNER', ''),
  (653, 'NPC_EARTHQUAKE', 'Earthquake', ''),
  (654, 'NPC_FIREBREATH', 'Fire Breath', ''),
  (655, 'NPC_ICEBREATH', 'Ice Breath', ''),
  (656, 'NPC_THUNDERBREATH', 'Thunder Breath', ''),
  (657, 'NPC_ACIDBREATH', 'Acid Breath', ''),
  (658, 'NPC_DARKNESSBREATH', 'Darkness Breath', ''),
  (659, 'NPC_DRAGONFEAR', 'Dragon Fear', ''),
  (660, 'NPC_BLEEDING', 'Bleeding', ''),
  (661, 'NPC_PULSESTRIKE', 'Pulse Strike', ''),
  (662, 'NPC_HELLJUDGEMENT', 'Hell''s Judgement', ''),
  (663, 'NPC_WIDESILENCE', 'Wide Silence', ''),
  (664, 'NPC_WIDEFREEZE', 'Wide Freeze', ''),
  (665, 'NPC_WIDEBLEEDING', 'Wide Bleeding', ''),
  (666, 'NPC_WIDESTONE', 'Wide Petrify', ''),
  (667, 'NPC_WIDECONFUSE', 'Wide Confusion', ''),
  (668, 'NPC_WIDESLEEP', 'Wide Sleep', ''),
  (669, 'NPC_WIDESIGHT', 'Wide Sight', ''),
  (670, 'NPC_EVILLAND', 'Evil Land', ''),
  (671, 'NPC_MAGICMIRROR', 'Magic Mirror', ''),
  (672, 'NPC_SLOWCAST', 'Slow Cast', ''),
  (673, 'NPC_CRITICALWOUND', 'Critical Wounds', ''),
  (674, 'NPC_EXPULSION', 'Expulsion', ''),
  (675, 'NPC_STONESKIN', 'Stone Skin', ''),
  (676, 'NPC_ANTIMAGIC', 'Anti Magic', ''),
  (677, 'NPC_WIDECURSE', 'Wide Curse', ''),
  (678, 'NPC_WIDESTUN', 'Wide Stun', ''),
  (679, 'NPC_VAMPIRE_GIFT', 'Vampire Gift', ''),
  (680, 'NPC_WIDESOULDRAIN', 'Wide Soul Drain', ''),
  (681, 'ALL_INCCARRY', 'Increase Weight Limit R', ''),
  (682, 'NPC_TALK', 'Talk', ''),
  (683, 'NPC_HELLPOWER', 'Hell Power', ''),
  (684, 'NPC_WIDEHELLDIGNITY', 'Hell Dignity', ''),
  (685, 'NPC_INVINCIBLE', 'Invincible', ''),
  (686, 'NPC_INVINCIBLEOFF', 'Invincible off', ''),
  (687, 'NPC_ALLHEAL', 'Full Heal', ''),
  (688, 'GM_SANDMAN', 'GM Sandman', ''),
  (689, 'CASH_BLESSING', 'Party Blessing', ''),
  (690, 'CASH_INCAGI', 'Party Increase AGI', ''),
  (691, 'CASH_ASSUMPTIO', 'Party Assumptio', ''),
  (692, 'ALL_CATCRY', 'Cat Cry', ''),
  (693, 'ALL_PARTYFLEE', 'Party Flee', ''),
  (694, 'ALL_ANGEL_PROTECT', 'Angel''s Protection', ''),
  (695, 'ALL_DREAM_SUMMERNIGHT', 'Summer Night Dream', ''),
  (697, 'ALL_REVERSEORCISH', 'Reverse Orcish', ''),
  (698, 'ALL_WEWISH', 'Christmas Carol', ''),
  (706, 'NPC_VENOMFOG', 'Venom Fog', ''),
  (707, 'NPC_MILLENNIUMSHIELD', 'Millenium Shield 2', ''),
  (708, 'NPC_COMET', 'Comet 2', ''),
  (709, 'NPC_ICEMINE', 'Ice Mine', ''),
  (711, 'NPC_FLAMECROSS', 'Flame Cross', ''),
  (712, 'NPC_PULSESTRIKE2', 'Pulse Strike 2', ''),
  (713, 'NPC_DANCINGBLADE', 'Dancing Blade', ''),
  (714, 'NPC_DANCINGBLADE_ATK', 'Dancing Blade Attack', ''),
  (715, 'NPC_DARKPIERCING', 'Dark Piercing', ''),
  (716, 'NPC_MAXPAIN', 'Max Pain', ''),
  (717, 'NPC_MAXPAIN_ATK', 'Max Pain Attack', ''),
  (718, 'NPC_DEATHSUMMON', 'Death Summon', ''),
  (719, 'NPC_HELLBURNING', 'Hell Burning', ''),
  (720, 'NPC_JACKFROST', 'Jack Frost 2', ''),
  (721, 'NPC_WIDEWEB', 'Wide Web', ''),
  (722, 'NPC_WIDESUCK', 'Wide Suck', ''),
  (723, 'NPC_STORMGUST2', 'Storm Gust 2', ''),
  (724, 'NPC_FIRESTORM', 'Fire Storm', ''),
  (725, 'NPC_REVERBERATION', 'Reverberation 2', ''),
  (726, 'NPC_REVERBERATION_ATK', 'Reverberation Attack', ''),
  (727, 'NPC_LEX_AETERNA', 'Lex Aeterna 2', ''),
  (728, 'NPC_ARROWSTORM', 'NPC Arrow Storm', ''),
  (729, 'NPC_CHEAL', 'NPC Coluceo Heal', ''),
  (730, 'NPC_SR_CURSEDCIRCLE', 'Cursed Circle', ''),
  (731, 'NPC_DRAGONBREATH', 'NPC Dragon Breath', ''),
  (732, 'NPC_FATALMENACE', 'Fatal Menace', ''),
  (733, 'NPC_MAGMA_ERUPTION', 'NPC Magma Eruption', ''),
  (734, 'NPC_MAGMA_ERUPTION_DOTDAMAGE', 'NPC Magma Eruption Dot Damage', ''),
  (735, 'NPC_MANDRAGORA', 'NPC Howling of Mandragora', ''),
  (736, 'NPC_PSYCHIC_WAVE', 'Psychic Wave', ''),
  (737, 'NPC_RAYOFGENESIS', 'NPC Ray of Genesis', ''),
  (738, 'NPC_VENOMIMPRESS', 'NPC Venom Impress', ''),
  (739, 'NPC_CLOUD_KILL', 'Cloud Kill', ''),
  (740, 'NPC_IGNITIONBREAK', 'Ignition Break', ''),
  (741, 'NPC_PHANTOMTHRUST', 'Phantom Thrust', ''),
  (742, 'NPC_POISON_BUSTER', 'Poison Buster', ''),
  (743, 'NPC_HALLUCINATIONWALK', 'Hallucination Walk', ''),
  (744, 'NPC_ELECTRICWALK', 'Electric Walk', ''),
  (745, 'NPC_FIREWALK', 'Fire Walk', ''),
  (747, 'NPC_LEASH', 'Leash', ''),
  (748, 'NPC_WIDELEASH', 'Wide Leash', ''),
  (749, 'NPC_WIDECRITICALWOUND', 'Wide Critical Wounds', ''),
  (751, 'NPC_ALL_STAT_DOWN', 'Decrease All Stats', ''),
  (752, 'NPC_GRADUAL_GRAVITY', 'Increased Gravity', ''),
  (753, 'NPC_DAMAGE_HEAL', 'Damage Heal', ''),
  (754, 'NPC_IMMUNE_PROPERTY', 'Property Immune', ''),
  (755, 'NPC_MOVE_COORDINATE', 'Change Location', ''),
  (756, 'NPC_WIDEBLEEDING2', 'Wide Bleeding', ''),
  (757, 'NPC_WIDESILENCE2', 'Wide Silence', ''),
  (758, 'NPC_WIDESTUN2', 'Wide Stun', ''),
  (759, 'NPC_WIDESTONE2', 'Wide Petrify', ''),
  (760, 'NPC_WIDESLEEP2', 'Wide Sleep', ''),
  (761, 'NPC_WIDECURSE2', 'Wide Curse', ''),
  (762, 'NPC_WIDECONFUSE2', 'Wide Confusion', ''),
  (763, 'NPC_WIDEFREEZE2', 'Wide Freeze', ''),
  (764, 'NPC_BLEEDING2', 'Bleeding', ''),
  (765, 'NPC_ICEBREATH2', 'Ice Breath', ''),
  (768, 'NPC_HELLJUDGEMENT2', 'Hell''s Judgement', ''),
  (769, 'NPC_RAINOFMETEOR', 'Rain of Meteor', ''),
  (770, 'NPC_GROUNDDRIVE', 'Ground Drive', ''),
  (771, 'NPC_RELIEVE_ON', 'NPC_RELIEVE_ON', ''),
  (772, 'NPC_RELIEVE_OFF', 'NPC_RELIEVE_OFF', ''),
  (776, 'NPC_DEADLYCURSE', 'Deadly Curse', ''),
  (779, 'NPC_DEADLYCURSE2', 'Deadly Curse 2', ''),
  (780, 'NPC_CANE_OF_EVIL_EYE', 'Cane of evil eye', ''),
  (783, 'NPC_KILLING_AURA', 'Killing Aura', ''),
  (784, 'ALL_EVENT_20TH_ANNIVERSARY', 'RO 20th Anniversary Firecracker', ''),
  (1001, 'KN_CHARGEATK', 'Charge Attack', ''),
  (1002, 'CR_SHRINK', 'Shrink', ''),
  (1003, 'AS_SONICACCEL', 'Sonic Acceleration', ''),
  (1004, 'AS_VENOMKNIFE', 'Throw Venom Knife', ''),
  (1005, 'RG_CLOSECONFINE', 'Close Confine', ''),
  (1006, 'WZ_SIGHTBLASTER', 'Sight Blaster', ''),
  (1007, 'SA_CREATECON', 'Create Elemental Converter', ''),
  (1008, 'SA_ELEMENTWATER', 'Elemental Change Water', ''),
  (1009, 'HT_PHANTASMIC', 'Phantasmic Arrow', ''),
  (1010, 'BA_PANGVOICE', 'Pang Voice', ''),
  (1011, 'DC_WINKCHARM', 'Wink of Charm', ''),
  (1012, 'BS_UNFAIRLYTRICK', 'Unfair Trick', ''),
  (1013, 'BS_GREED', 'Greed', ''),
  (1014, 'PR_REDEMPTIO', 'Redemptio', ''),
  (1015, 'MO_KITRANSLATION', 'Ki Translation', ''),
  (1016, 'MO_BALKYOUNG', 'Ki Explosion', ''),
  (1017, 'SA_ELEMENTGROUND', 'Elemental Change Earth', ''),
  (1018, 'SA_ELEMENTFIRE', 'Elemental Change Fire', ''),
  (1019, 'SA_ELEMENTWIND', 'Elemental Change Wind', ''),
  (2001, 'RK_ENCHANTBLADE', 'Enchant Blade', ''),
  (2002, 'RK_SONICWAVE', 'Sonic Wave', ''),
  (2003, 'RK_DEATHBOUND', 'Death Bound', ''),
  (2004, 'RK_HUNDREDSPEAR', 'Hundred Spear', ''),
  (2005, 'RK_WINDCUTTER', 'Wind Cutter', ''),
  (2006, 'RK_IGNITIONBREAK', 'Ignition Break', ''),
  (2007, 'RK_DRAGONTRAINING', 'Dragon Training', ''),
  (2008, 'RK_DRAGONBREATH', 'Dragon Breath', ''),
  (2009, 'RK_DRAGONHOWLING', 'Dragon Howling', ''),
  (2010, 'RK_RUNEMASTERY', 'Rune Mastery', ''),
  (2011, 'RK_MILLENNIUMSHIELD', 'Millenium Shield', ''),
  (2012, 'RK_CRUSHSTRIKE', 'Crush Strike', ''),
  (2013, 'RK_REFRESH', 'Refresh', ''),
  (2014, 'RK_GIANTGROWTH', 'Giant Growth', ''),
  (2015, 'RK_STONEHARDSKIN', 'Stone Hard Skin', ''),
  (2016, 'RK_VITALITYACTIVATION', 'Vitality Activation', ''),
  (2017, 'RK_STORMBLAST', 'Storm Blast', ''),
  (2018, 'RK_FIGHTINGSPIRIT', 'Fighting Spirit', ''),
  (2019, 'RK_ABUNDANCE', 'Abundance', ''),
  (2020, 'RK_PHANTOMTHRUST', 'Phantom Thrust', ''),
  (2201, 'WL_WHITEIMPRISON', 'White Imprison', ''),
  (2202, 'WL_SOULEXPANSION', 'Soul Expansion', ''),
  (2203, 'WL_FROSTMISTY', 'Frosty Misty', ''),
  (2204, 'WL_JACKFROST', 'Jack Frost', ''),
  (2205, 'WL_MARSHOFABYSS', 'Marsh of Abyss', ''),
  (2206, 'WL_RECOGNIZEDSPELL', 'Recognized Spell', ''),
  (2207, 'WL_SIENNAEXECRATE', 'Sienna Execrate', ''),
  (2208, 'WL_RADIUS', 'Radius', ''),
  (2209, 'WL_STASIS', 'Stasis', ''),
  (2210, 'WL_DRAINLIFE', 'Drain Life', ''),
  (2211, 'WL_CRIMSONROCK', 'Crimson Rock', ''),
  (2212, 'WL_HELLINFERNO', 'Hell Inferno', ''),
  (2213, 'WL_COMET', 'Comet', ''),
  (2214, 'WL_CHAINLIGHTNING', 'Chain Lightning', ''),
  (2215, 'WL_CHAINLIGHTNING_ATK', 'Chain Lightning Attack', ''),
  (2216, 'WL_EARTHSTRAIN', 'Earth Strain', ''),
  (2217, 'WL_TETRAVORTEX', 'Tetra Vortex', ''),
  (2218, 'WL_TETRAVORTEX_FIRE', 'Tetra Vortex Fire', ''),
  (2219, 'WL_TETRAVORTEX_WATER', 'Tetra Vortex Water', ''),
  (2220, 'WL_TETRAVORTEX_WIND', 'Tetra Vortex Wind', ''),
  (2221, 'WL_TETRAVORTEX_GROUND', 'Tetra Vortex Earth', ''),
  (2222, 'WL_SUMMONFB', 'Summon Fire Ball', ''),
  (2223, 'WL_SUMMONBL', 'Summon Lightning Ball', ''),
  (2224, 'WL_SUMMONWB', 'Summon Water Ball', ''),
  (2225, 'WL_SUMMON_ATK_FIRE', 'Summon Attack Fire', ''),
  (2226, 'WL_SUMMON_ATK_WIND', 'Summon Attack Wind', ''),
  (2227, 'WL_SUMMON_ATK_WATER', 'Summon Attack Water', ''),
  (2228, 'WL_SUMMON_ATK_GROUND', 'Summon Attack Earth', ''),
  (2229, 'WL_SUMMONSTONE', 'Summon Stone', ''),
  (2230, 'WL_RELEASE', 'Release', ''),
  (2231, 'WL_READING_SB', 'Reading Spellbook', ''),
  (2232, 'WL_FREEZE_SP', 'Freeze Spell', ''),
  (2021, 'GC_VENOMIMPRESS', 'Venom Impress', ''),
  (2022, 'GC_CROSSIMPACT', 'Cross Impact', ''),
  (2023, 'GC_DARKILLUSION', 'Dark Illusion', ''),
  (2024, 'GC_RESEARCHNEWPOISON', 'Research New Poison', ''),
  (2025, 'GC_CREATENEWPOISON', 'Create New Poison', ''),
  (2026, 'GC_ANTIDOTE', 'Antidote', ''),
  (2027, 'GC_POISONINGWEAPON', 'Poisoning Weapon', ''),
  (2028, 'GC_WEAPONBLOCKING', 'Weapon Blocking', ''),
  (2029, 'GC_COUNTERSLASH', 'Counter Slash', ''),
  (2030, 'GC_WEAPONCRUSH', 'Weapon Crush', ''),
  (2031, 'GC_VENOMPRESSURE', 'Venom Pressure', ''),
  (2032, 'GC_POISONSMOKE', 'Poison Smoke', ''),
  (2033, 'GC_CLOAKINGEXCEED', 'Cloaking Exceed', ''),
  (2034, 'GC_PHANTOMMENACE', 'Phantom Menace', ''),
  (2035, 'GC_HALLUCINATIONWALK', 'Hallucination Walk', ''),
  (2036, 'GC_ROLLINGCUTTER', 'Rolling Cutter', ''),
  (2037, 'GC_CROSSRIPPERSLASHER', 'Cross Ripper Slasher', ''),
  (2038, 'AB_JUDEX', 'Judex', ''),
  (2039, 'AB_ANCILLA', 'Ancilla', ''),
  (2040, 'AB_ADORAMUS', 'Adoramus', ''),
  (2041, 'AB_CLEMENTIA', 'Crementia', ''),
  (2042, 'AB_CANTO', 'Canto Candidus', ''),
  (2043, 'AB_CHEAL', 'Coluceo Heal', ''),
  (2044, 'AB_EPICLESIS', 'Epiclesis', ''),
  (2045, 'AB_PRAEFATIO', 'Praefatio', ''),
  (2046, 'AB_ORATIO', 'Oratio', ''),
  (2047, 'AB_LAUDAAGNUS', 'Lauda Agnus', ''),
  (2048, 'AB_LAUDARAMUS', 'Lauda Ramus', ''),
  (2049, 'AB_EUCHARISTICA', 'Eucharistica', ''),
  (2050, 'AB_RENOVATIO', 'Renovatio', ''),
  (2051, 'AB_HIGHNESSHEAL', 'Highness Heal', ''),
  (2052, 'AB_CLEARANCE', 'Clearance', ''),
  (2053, 'AB_EXPIATIO', 'Expiatio', ''),
  (2054, 'AB_DUPLELIGHT', 'Duple Light', ''),
  (2055, 'AB_DUPLELIGHT_MELEE', 'Duple Light Melee', ''),
  (2056, 'AB_DUPLELIGHT_MAGIC', 'Duple Light Magic', ''),
  (2057, 'AB_SILENTIUM', 'Silentium', ''),
  (2515, 'AB_SECRAMENT', 'Secrament', ''),
  (2233, 'RA_ARROWSTORM', 'Arrow Storm', ''),
  (2234, 'RA_FEARBREEZE', 'Fear Breeze', ''),
  (2235, 'RA_RANGERMAIN', 'Ranger Main', ''),
  (2236, 'RA_AIMEDBOLT', 'Aimed Bolt', ''),
  (2237, 'RA_DETONATOR', 'Detonator', ''),
  (2238, 'RA_ELECTRICSHOCKER', 'Electric Shocker', ''),
  (2239, 'RA_CLUSTERBOMB', 'Cluster Bomb', ''),
  (2240, 'RA_WUGMASTERY', 'Warg Mastery', ''),
  (2241, 'RA_WUGRIDER', 'Warg Rider', ''),
  (2242, 'RA_WUGDASH', 'Warg Dash', ''),
  (2243, 'RA_WUGSTRIKE', 'Warg Strike', ''),
  (2244, 'RA_WUGBITE', 'Warg Bite', ''),
  (2245, 'RA_TOOTHOFWUG', 'Tooth of Warg', ''),
  (2246, 'RA_SENSITIVEKEEN', 'Sensitive Keen', ''),
  (2247, 'RA_CAMOUFLAGE', 'Camouflage', ''),
  (2248, 'RA_RESEARCHTRAP', 'Research Trap', ''),
  (2249, 'RA_MAGENTATRAP', 'Magenta Trap', ''),
  (2250, 'RA_COBALTTRAP', 'Cobalt Trap', ''),
  (2251, 'RA_MAIZETRAP', 'Maize Trap', ''),
  (2252, 'RA_VERDURETRAP', 'Verdure Trap', ''),
  (2253, 'RA_FIRINGTRAP', 'Firing Trap', ''),
  (2254, 'RA_ICEBOUNDTRAP', 'Icebound Trap', ''),
  (2255, 'NC_MADOLICENCE', 'Mado License', ''),
  (2256, 'NC_BOOSTKNUCKLE', 'Boost Knuckle', ''),
  (2257, 'NC_PILEBUNKER', 'Pile Bunker', ''),
  (2258, 'NC_VULCANARM', 'Vulcan Arm', ''),
  (2259, 'NC_FLAMELAUNCHER', 'Flame Launcher', ''),
  (2260, 'NC_COLDSLOWER', 'Cold Slower', ''),
  (2261, 'NC_ARMSCANNON', 'Arm Cannon', ''),
  (2262, 'NC_ACCELERATION', 'Acceleration', ''),
  (2263, 'NC_HOVERING', 'Hovering', ''),
  (2264, 'NC_F_SIDESLIDE', 'Front-Side Slide', ''),
  (2265, 'NC_B_SIDESLIDE', 'Back-Side Slide', ''),
  (2266, 'NC_MAINFRAME', 'Mainframe Restructure', ''),
  (2267, 'NC_SELFDESTRUCTION', 'Self Destruction', ''),
  (2268, 'NC_SHAPESHIFT', 'Shape Shift', ''),
  (2269, 'NC_EMERGENCYCOOL', 'Emergency Cool', ''),
  (2270, 'NC_INFRAREDSCAN', 'Infrared Scan', ''),
  (2271, 'NC_ANALYZE', 'Analyze', ''),
  (2272, 'NC_MAGNETICFIELD', 'Magnetic Field', ''),
  (2273, 'NC_NEUTRALBARRIER', 'Neutral Barrier', ''),
  (2274, 'NC_STEALTHFIELD', 'Stealth Field', ''),
  (2275, 'NC_REPAIR', 'Repair', ''),
  (2276, 'NC_TRAININGAXE', 'Axe Training', ''),
  (2277, 'NC_RESEARCHFE', 'Research Fire/Earth', ''),
  (2278, 'NC_AXEBOOMERANG', 'Axe Boomerang', ''),
  (2279, 'NC_POWERSWING', 'Power Swing', ''),
  (2280, 'NC_AXETORNADO', 'Axe Tornado', ''),
  (2281, 'NC_SILVERSNIPER', 'FAW - Silver Sniper', ''),
  (2282, 'NC_MAGICDECOY', 'FAW - Magic Decoy', ''),
  (2283, 'NC_DISJOINT', 'FAW Removal', ''),
  (2284, 'SC_FATALMENACE', 'Fatal Menace', ''),
  (2285, 'SC_REPRODUCE', 'Reproduce', ''),
  (2286, 'SC_AUTOSHADOWSPELL', 'Auto Shadow Spell', ''),
  (2287, 'SC_SHADOWFORM', 'Shadow Form', ''),
  (2288, 'SC_TRIANGLESHOT', 'Triangle Shot', ''),
  (2289, 'SC_BODYPAINT', 'Body Painting', ''),
  (2290, 'SC_INVISIBILITY', 'Invisibility', ''),
  (2291, 'SC_DEADLYINFECT', 'Deadly Infect', ''),
  (2292, 'SC_ENERVATION', 'Masquerade - Enervation', ''),
  (2293, 'SC_GROOMY', 'Masquerade - Gloomy', ''),
  (2294, 'SC_IGNORANCE', 'Masquerade - Ignorance', ''),
  (2295, 'SC_LAZINESS', 'Masquerade - Laziness', ''),
  (2296, 'SC_UNLUCKY', 'Masquerade - Unlucky', ''),
  (2297, 'SC_WEAKNESS', 'Masquerade - Weakness', ''),
  (2298, 'SC_STRIPACCESSARY', 'Strip Accessory', ''),
  (2299, 'SC_MANHOLE', 'Man Hole', ''),
  (2300, 'SC_DIMENSIONDOOR', 'Dimension Door', ''),
  (2301, 'SC_CHAOSPANIC', 'Chaos Panic', ''),
  (2302, 'SC_MAELSTROM', 'Maelstrom', ''),
  (2303, 'SC_BLOODYLUST', 'Bloody Lust', ''),
  (2304, 'SC_FEINTBOMB', 'Feint Bomb', ''),
  (2307, 'LG_CANNONSPEAR', 'Cannon Spear', ''),
  (2308, 'LG_BANISHINGPOINT', 'Banishing Point', ''),
  (2309, 'LG_TRAMPLE', 'Trample', ''),
  (2310, 'LG_SHIELDPRESS', 'Shield Press', ''),
  (2311, 'LG_REFLECTDAMAGE', 'Reflect Damage Reduction', ''),
  (2312, 'LG_PINPOINTATTACK', 'Pinpoint Attack', ''),
  (2313, 'LG_FORCEOFVANGUARD', 'Force of Vanguard', ''),
  (2314, 'LG_RAGEBURST', 'Rage Burst', ''),
  (2315, 'LG_SHIELDSPELL', 'Shield Spell', ''),
  (2316, 'LG_EXEEDBREAK', 'Exceed Break', ''),
  (2317, 'LG_OVERBRAND', 'Over Brand', ''),
  (2318, 'LG_PRESTIGE', 'Prestige', ''),
  (2319, 'LG_BANDING', 'Banding', ''),
  (2320, 'LG_MOONSLASHER', 'Moon Slasher', ''),
  (2321, 'LG_RAYOFGENESIS', 'Ray of Genesis', ''),
  (2322, 'LG_PIETY', 'Piety', ''),
  (2323, 'LG_EARTHDRIVE', 'Earth Drive', ''),
  (2324, 'LG_HESPERUSLIT', 'Hesperus Lit', ''),
  (2325, 'LG_INSPIRATION', 'Inspiration', ''),
  (2519, 'LG_OVERBRAND_BRANDISH', 'Overbrand Brandish', ''),
  (2520, 'LG_OVERBRAND_PLUSATK', 'Overbrand Plus Attack', ''),
  (2326, 'SR_DRAGONCOMBO', 'Dragon Combo', ''),
  (2327, 'SR_SKYNETBLOW', 'Sky Net Blow', ''),
  (2328, 'SR_EARTHSHAKER', 'Earth Shaker', ''),
  (2329, 'SR_FALLENEMPIRE', 'Fallen Empire', ''),
  (2330, 'SR_TIGERCANNON', 'Tiger Cannon', ''),
  (2331, 'SR_HELLGATE', 'Hell Gate', ''),
  (2332, 'SR_RAMPAGEBLASTER', 'Rampage Blaster', ''),
  (2333, 'SR_CRESCENTELBOW', 'Crescent Elbow', ''),
  (2334, 'SR_CURSEDCIRCLE', 'Cursed Circle', ''),
  (2335, 'SR_LIGHTNINGWALK', 'Lightning Walk', ''),
  (2336, 'SR_KNUCKLEARROW', 'Knuckle Arrow', ''),
  (2337, 'SR_WINDMILL', 'Windmill', ''),
  (2338, 'SR_RAISINGDRAGON', 'Raising Dragon', ''),
  (2339, 'SR_GENTLETOUCH', 'Gentle Touch', ''),
  (2340, 'SR_ASSIMILATEPOWER', 'Assimilate Power', ''),
  (2341, 'SR_POWERVELOCITY', 'Power Velocity', ''),
  (2342, 'SR_CRESCENTELBOW_AUTOSPELL', 'Crescent Elbow Autospell', ''),
  (2343, 'SR_GATEOFHELL', 'Gate of Hell', ''),
  (2344, 'SR_GENTLETOUCH_QUIET', 'Gentle Touch - Quiet', ''),
  (2345, 'SR_GENTLETOUCH_CURE', 'Gentle Touch - Cure', ''),
  (2346, 'SR_GENTLETOUCH_ENERGYGAIN', 'Gentle Touch - Energy Gain', ''),
  (2347, 'SR_GENTLETOUCH_CHANGE', 'Gentle Touch - Change', ''),
  (2348, 'SR_GENTLETOUCH_REVITALIZE', 'Gentle Touch - Revitalize', ''),
  (2517, 'SR_HOWLINGOFLION', 'Howling of Lion', ''),
  (2518, 'SR_RIDEINLIGHTNING', 'Ride In Lightening', ''),
  (2350, 'WA_SWING_DANCE', 'Swing Dance', ''),
  (2351, 'WA_SYMPHONY_OF_LOVER', 'Symphony of Lovers', ''),
  (2352, 'WA_MOONLIT_SERENADE', 'Moonlit Serenade', ''),
  (2381, 'MI_RUSH_WINDMILL', 'Windmill Rush Attack', ''),
  (2382, 'MI_ECHOSONG', 'Echo Song', ''),
  (2383, 'MI_HARMONIZE', 'Harmonize', ''),
  (2412, 'WM_LESSON', 'Lesson', ''),
  (2413, 'WM_METALICSOUND', 'Metallic Sound', ''),
  (2414, 'WM_REVERBERATION', 'Reverberation', ''),
  (2415, 'WM_REVERBERATION_MELEE', 'Reverberation Melee', ''),
  (2416, 'WM_REVERBERATION_MAGIC', 'Reverberation Magic', ''),
  (2417, 'WM_DOMINION_IMPULSE', 'Dominion Impulse', ''),
  (2418, 'WM_SEVERE_RAINSTORM', 'Severe Rainstorm', ''),
  (2419, 'WM_POEMOFNETHERWORLD', 'Poem of The Netherworld', ''),
  (2420, 'WM_VOICEOFSIREN', 'Voice of Siren', ''),
  (2421, 'WM_DEADHILLHERE', 'Valley of Death', ''),
  (2422, 'WM_LULLABY_DEEPSLEEP', 'Deep Sleep Lullaby', ''),
  (2423, 'WM_SIRCLEOFNATURE', 'Circle of Nature''s Sound', ''),
  (2424, 'WM_RANDOMIZESPELL', 'Improvised Song', ''),
  (2425, 'WM_GLOOMYDAY', 'Gloomy Day', ''),
  (2426, 'WM_GREAT_ECHO', 'Great Echo', ''),
  (2427, 'WM_SONG_OF_MANA', 'Song of Mana', ''),
  (2428, 'WM_DANCE_WITH_WUG', 'Dance With A Warg', ''),
  (2429, 'WM_SOUND_OF_DESTRUCTION', 'Sound of Destruction', ''),
  (2430, 'WM_SATURDAY_NIGHT_FEVER', 'Saturday Night Fever', ''),
  (2431, 'WM_LERADS_DEW', 'Lerad''s Dew', ''),
  (2432, 'WM_MELODYOFSINK', 'Melody of Sink', ''),
  (2433, 'WM_BEYOND_OF_WARCRY', 'Warcry of Beyond', ''),
  (2434, 'WM_UNLIMITED_HUMMING_VOICE', 'Unlimited Humming Voice', ''),
  (2516, 'WM_SEVERE_RAINSTORM_MELEE', 'Severe Rainstorm Melee', ''),
  (2443, 'SO_FIREWALK', 'Fire Walk', ''),
  (2444, 'SO_ELECTRICWALK', 'Electric Walk', ''),
  (2445, 'SO_SPELLFIST', 'Spell Fist', ''),
  (2446, 'SO_EARTHGRAVE', 'Earth Grave', ''),
  (2447, 'SO_DIAMONDDUST', 'Diamond Dust', ''),
  (2448, 'SO_POISON_BUSTER', 'Poison Buster', ''),
  (2449, 'SO_PSYCHIC_WAVE', 'Psychic Wave', ''),
  (2450, 'SO_CLOUD_KILL', 'Cloud Kill', ''),
  (2451, 'SO_STRIKING', 'Striking', ''),
  (2452, 'SO_WARMER', 'Warmer', ''),
  (2453, 'SO_VACUUM_EXTREME', 'Vacuum Extreme', ''),
  (2454, 'SO_VARETYR_SPEAR', 'Varetyr Spear', ''),
  (2455, 'SO_ARRULLO', 'Arrullo', ''),
  (2456, 'SO_EL_CONTROL', 'Spirit Control', ''),
  (2457, 'SO_SUMMON_AGNI', 'Summon Fire Spirit Agni', ''),
  (2458, 'SO_SUMMON_AQUA', 'Summon Water Spirit Aqua', ''),
  (2459, 'SO_SUMMON_VENTUS', 'Summon Wind Spirit Ventus', ''),
  (2460, 'SO_SUMMON_TERA', 'Summon Earth Spirit Tera', ''),
  (2461, 'SO_EL_ACTION', 'Elemental Action', ''),
  (2462, 'SO_EL_ANALYSIS', 'Four Spirit Analysis', ''),
  (2463, 'SO_EL_SYMPATHY', 'Spirit Sympathy', ''),
  (2464, 'SO_EL_CURE', 'Spirit Recovery', ''),
  (2465, 'SO_FIRE_INSIGNIA', 'Fire Insignia', ''),
  (2466, 'SO_WATER_INSIGNIA', 'Water Insignia', ''),
  (2467, 'SO_WIND_INSIGNIA', 'Wind Insignia', ''),
  (2468, 'SO_EARTH_INSIGNIA', 'Earth Insignia', ''),
  (2474, 'GN_TRAINING_SWORD', 'Sword Training', ''),
  (2475, 'GN_REMODELING_CART', 'Cart Remodeling', ''),
  (2476, 'GN_CART_TORNADO', 'Cart Tornado', ''),
  (2477, 'GN_CARTCANNON', 'Cart Cannon', ''),
  (2478, 'GN_CARTBOOST', 'Cart Boost', ''),
  (2479, 'GN_THORNS_TRAP', 'Thorn Trap', ''),
  (2480, 'GN_BLOOD_SUCKER', 'Blood Sucker', ''),
  (2481, 'GN_SPORE_EXPLOSION', 'Spore Explosion', ''),
  (2482, 'GN_WALLOFTHORN', 'Wall of Thorns', ''),
  (2483, 'GN_CRAZYWEED', 'Crazy Weed', ''),
  (2484, 'GN_CRAZYWEED_ATK', 'Crazy Weed Attack', ''),
  (2485, 'GN_DEMONIC_FIRE', 'Demonic Fire', ''),
  (2486, 'GN_FIRE_EXPANSION', 'Fire Expansion', ''),
  (2487, 'GN_FIRE_EXPANSION_SMOKE_POWDER', 'Fire Expansion Smoke Powder', ''),
  (2488, 'GN_FIRE_EXPANSION_TEAR_GAS', 'Fire Expansion Tear Gas', ''),
  (2489, 'GN_FIRE_EXPANSION_ACID', 'Fire Expansion Acid', ''),
  (2490, 'GN_HELLS_PLANT', 'Hell''s Plant', ''),
  (2491, 'GN_HELLS_PLANT_ATK', 'Hell''s Plant Attack', ''),
  (2492, 'GN_MANDRAGORA', 'Howling of Mandragora', ''),
  (2493, 'GN_SLINGITEM', 'Sling Item', ''),
  (2494, 'GN_CHANGEMATERIAL', 'Change Material', ''),
  (2495, 'GN_MIX_COOKING', 'Mix Cooking', ''),
  (2496, 'GN_MAKEBOMB', 'Create Bomb', ''),
  (2497, 'GN_S_PHARMACY', 'Special Pharmacy', ''),
  (2498, 'GN_SLINGITEM_RANGEMELEEATK', 'Sling Item Attack', ''),
  (2533, 'ALL_ODINS_RECALL', 'Odin''s Recall', ''),
  (2534, 'RETURN_TO_ELDICASTES', 'Return To Eldicastes', ''),
  (2535, 'ALL_BUYING_STORE', 'Open Buying Store', ''),
  (2536, 'ALL_GUARDIAN_RECALL', 'Guardian''s Recall', ''),
  (2537, 'ALL_ODINS_POWER', 'Odin''s Power', ''),
  (2543, 'ALL_RAY_OF_PROTECTION', 'Ray of Protection', ''),
  (2544, 'MC_CARTDECORATE', 'Decorate Cart', ''),
  (2552, 'RL_RICHS_COIN', 'Rich''s Coin', ''),
  (2553, 'RL_MASS_SPIRAL', 'Mass Spiral', ''),
  (2554, 'RL_BANISHING_BUSTER', 'Banishing Buster', ''),
  (2555, 'RL_B_TRAP', 'Bind Trap', ''),
  (2556, 'RL_FLICKER', 'Flicker', ''),
  (2557, 'RL_S_STORM', 'Shatter Storm', ''),
  (2558, 'RL_E_CHAIN', 'Eternal Chain', ''),
  (2559, 'RL_QD_SHOT', 'Quick Draw Shot', ''),
  (2560, 'RL_C_MARKER', 'Crimson Marker', ''),
  (2561, 'RL_FIREDANCE', 'Fire Dance', ''),
  (2562, 'RL_H_MINE', 'Howling Mine', ''),
  (2563, 'RL_P_ALTER', 'Platinum Alter', ''),
  (2564, 'RL_FALLEN_ANGEL', 'Fallen Angel', ''),
  (2565, 'RL_R_TRIP', 'Round Trip', ''),
  (2566, 'RL_D_TAIL', 'Dragon Tail', ''),
  (2567, 'RL_FIRE_RAIN', 'Fire Rain', ''),
  (2568, 'RL_HEAT_BARREL', 'Heat Barrel', ''),
  (2569, 'RL_AM_BLAST', 'Anti-Material Blast', ''),
  (2570, 'RL_SLUGSHOT', 'Slug Shot', ''),
  (2571, 'RL_HAMMER_OF_GOD', 'Hammer of God', ''),
  (2572, 'RL_R_TRIP_PLUSATK', 'Round Trip Plus Attack', ''),
  (2574, 'SJ_LIGHTOFMOON', 'Light of Moon', ''),
  (2575, 'SJ_LUNARSTANCE', 'Lunar Stance', ''),
  (2576, 'SJ_FULLMOONKICK', 'Full Moon Kick', ''),
  (2577, 'SJ_LIGHTOFSTAR', 'Light of Star', ''),
  (2578, 'SJ_STARSTANCE', 'Star Stance', ''),
  (2579, 'SJ_NEWMOONKICK', 'New Moon Kick', ''),
  (2580, 'SJ_FLASHKICK', 'Flash Kick', ''),
  (2581, 'SJ_STAREMPEROR', 'Star Emperor Advent', ''),
  (2582, 'SJ_NOVAEXPLOSING', 'Nova Explosion', ''),
  (2583, 'SJ_UNIVERSESTANCE', 'Universe Stance', ''),
  (2584, 'SJ_FALLINGSTAR', 'Falling Star', ''),
  (2585, 'SJ_GRAVITYCONTROL', 'Gravity Control', ''),
  (2586, 'SJ_BOOKOFDIMENSION', 'Book of Dimension', ''),
  (2587, 'SJ_BOOKOFCREATINGSTAR', 'Book of Creating Star', ''),
  (2588, 'SJ_DOCUMENT', 'Document of Sun Moon and Star', ''),
  (2589, 'SJ_PURIFY', 'Purification of Sun Moon and Star', ''),
  (2590, 'SJ_LIGHTOFSUN', 'Light of Sun', ''),
  (2591, 'SJ_SUNSTANCE', 'Sun Stance', ''),
  (2592, 'SJ_SOLARBURST', 'Solar Burst', ''),
  (2593, 'SJ_PROMINENCEKICK', 'Prominence Kick', ''),
  (2594, 'SJ_FALLINGSTAR_ATK', 'Falling Star Attack', ''),
  (2595, 'SJ_FALLINGSTAR_ATK2', 'Falling Star Attack 2', ''),
  (2596, 'SP_SOULGOLEM', 'Golem''s Soul', ''),
  (2597, 'SP_SOULSHADOW', 'Shadow''s Soul', ''),
  (2598, 'SP_SOULFALCON', 'Falcon''s Soul', ''),
  (2599, 'SP_SOULFAIRY', 'Fairy''s Soul', ''),
  (2600, 'SP_CURSEEXPLOSION', 'Curse Explosion', ''),
  (2601, 'SP_SOULCURSE', 'Soul Curse', ''),
  (2602, 'SP_SPA', 'Espa', ''),
  (2603, 'SP_SHA', 'Esha', ''),
  (2604, 'SP_SWHOO', 'Eswhoo', ''),
  (2605, 'SP_SOULUNITY', 'Soul Unity', ''),
  (2606, 'SP_SOULDIVISION', 'Soul Division', ''),
  (2607, 'SP_SOULREAPER', 'Soul Reaper', ''),
  (2608, 'SP_SOULREVOLVE', 'Soul Revolution', ''),
  (2609, 'SP_SOULCOLLECT', 'Soul Collect', ''),
  (2610, 'SP_SOULEXPLOSION', 'Soul Explosion', ''),
  (2611, 'SP_SOULENERGY', 'Soul Energy Research', ''),
  (2612, 'SP_KAUTE', 'Kaute', ''),
  (3001, 'KO_YAMIKUMO', 'Shadow Hiding', ''),
  (3002, 'KO_RIGHT', 'Right Hand Mastery', ''),
  (3003, 'KO_LEFT', 'Left Hand Mastery', ''),
  (3004, 'KO_JYUMONJIKIRI', 'Cross Slash', ''),
  (3005, 'KO_SETSUDAN', 'Soul Cutter', ''),
  (3006, 'KO_BAKURETSU', 'Kunai Explosion', ''),
  (3007, 'KO_HAPPOKUNAI', 'Kunai Splash', ''),
  (3008, 'KO_MUCHANAGE', 'Rapid Throw', ''),
  (3009, 'KO_HUUMARANKA', 'Swirling Petal', ''),
  (3010, 'KO_MAKIBISHI', 'Makibishi', ''),
  (3011, 'KO_MEIKYOUSISUI', 'Pure Soul', ''),
  (3012, 'KO_ZANZOU', 'Illusion - Shadow', ''),
  (3013, 'KO_KYOUGAKU', 'Illusion - Shock', ''),
  (3014, 'KO_JYUSATSU', 'Illusion - Death', ''),
  (3015, 'KO_KAHU_ENTEN', 'Fire Charm', ''),
  (3016, 'KO_HYOUHU_HUBUKI', 'Ice Charm', ''),
  (3017, 'KO_KAZEHU_SEIRAN', 'Wind Charm', ''),
  (3018, 'KO_DOHU_KOUKAI', 'Earth Charm', ''),
  (3019, 'KO_KAIHOU', 'Release Ninja Spell', ''),
  (3020, 'KO_ZENKAI', 'Cast Ninja Spell', ''),
  (3021, 'KO_GENWAKU', 'Illusion - Bewitch', ''),
  (3022, 'KO_IZAYOI', '16th Night', ''),
  (3023, 'KG_KAGEHUMI', 'Shadow Trampling', ''),
  (3024, 'KG_KYOMU', 'Empty Shadow', ''),
  (3025, 'KG_KAGEMUSYA', 'Shadow Warrior', ''),
  (3026, 'OB_ZANGETSU', 'Distorted Crescent', ''),
  (3027, 'OB_OBOROGENSOU', 'Moonlight Fantasy', ''),
  (3028, 'OB_OBOROGENSOU_TRANSITION_ATK', 'Moonlight Fantasy Transition Attack', ''),
  (3029, 'OB_AKAITSUKI', 'Ominous Moonlight', ''),
  (3031, 'ECL_SNOWFLIP', 'Snow Flip', ''),
  (3032, 'ECL_PEONYMAMY', 'Peony Mamy', ''),
  (3033, 'ECL_SADAGUI', 'Sadagui', ''),
  (3034, 'ECL_SEQUOIADUST', 'Sequoia Dust', ''),
  (3035, 'ECLAGE_RECALL', 'Return To Eclage', ''),
  (3041, 'ALL_NIFLHEIM_RECALL', 'Niflheim Recall', ''),
  (3042, 'ALL_PRONTERA_RECALL', 'Prontera Recall', ''),
  (3043, 'ALL_GLASTHEIM_RECALL', 'Return To Glast Heim', ''),
  (3044, 'ALL_THANATOS_RECALL', 'Return To Thanatos', ''),
  (3045, 'ALL_LIGHTHALZEN_RECALL', 'Return To Lighthalzen', ''),
  (5001, 'GC_DARKCROW', 'Dark Claw', ''),
  (5002, 'RA_UNLIMIT', 'Unlimited', ''),
  (5003, 'GN_ILLUSIONDOPING', 'Illusion Doping', ''),
  (5004, 'RK_DRAGONBREATH_WATER', 'Dragon Breath - Water', ''),
  (5005, 'RK_LUXANIMA', 'Lux Anima', ''),
  (5006, 'NC_MAGMA_ERUPTION', 'Magma Eruption', ''),
  (5007, 'WM_FRIGG_SONG', 'Frigg''s Song', ''),
  (5008, 'SO_ELEMENTAL_SHIELD', 'Elemental Shield', ''),
  (5009, 'SR_FLASHCOMBO', 'Flash Combo', ''),
  (5010, 'SC_ESCAPE', 'Emergency Escape', ''),
  (5011, 'AB_OFFERTORIUM', 'Offertorium', ''),
  (5012, 'WL_TELEKINESIS_INTENSE', 'Intense Telekinesis', ''),
  (5013, 'LG_KINGS_GRACE', 'King''s Grace', ''),
  (5014, 'ALL_FULL_THROTTLE', 'Full Throttle', ''),
  (5015, 'NC_MAGMA_ERUPTION_DOTDAMAGE', 'Magma Eruption Dot Damage', ''),
  (5018, 'SU_BASIC_SKILL', 'New Basic Skill', ''),
  (5019, 'SU_BITE', 'Bite', ''),
  (5020, 'SU_HIDE', 'Hide', ''),
  (5021, 'SU_SCRATCH', 'Scratch', ''),
  (5022, 'SU_STOOP', 'Stoop', ''),
  (5023, 'SU_LOPE', 'Lope', ''),
  (5024, 'SU_SPRITEMABLE', 'Spirit Marble', ''),
  (5025, 'SU_POWEROFLAND', 'Power of Land', ''),
  (5026, 'SU_SV_STEMSPEAR', 'Silvervine Stem Spear', ''),
  (5027, 'SU_CN_POWDERING', 'Catnip Powdering', ''),
  (5028, 'SU_CN_METEOR', 'Catnip Meteor', ''),
  (5029, 'SU_SV_ROOTTWIST', 'Silvervine Root Twist', ''),
  (5030, 'SU_SV_ROOTTWIST_ATK', 'Silver Vine Root Twist Attack', ''),
  (5031, 'SU_POWEROFLIFE', 'Power of Life', ''),
  (5032, 'SU_SCAROFTAROU', 'Scar of Tarou', ''),
  (5033, 'SU_PICKYPECK', 'Picky Peck', ''),
  (5034, 'SU_PICKYPECK_DOUBLE_ATK', 'Picky Peck Double Attack', ''),
  (5035, 'SU_ARCLOUSEDASH', 'Arclouse Dash', ''),
  (5036, 'SU_LUNATICCARROTBEAT', 'Lunatic Carrot Beat', ''),
  (5037, 'SU_POWEROFSEA', 'Power of Sea', ''),
  (5038, 'SU_TUNABELLY', 'Tuna Belly', ''),
  (5039, 'SU_TUNAPARTY', 'Tuna Party', ''),
  (5040, 'SU_BUNCHOFSHRIMP', 'Bunch of Shrimp', ''),
  (5041, 'SU_FRESHSHRIMP', 'Fresh Shrimp', ''),
  (5042, 'SU_CN_METEOR2', 'Catnip Meteor 2', ''),
  (5043, 'SU_LUNATICCARROTBEAT2', 'Lunatic Carrot Beat 2', ''),
  (5044, 'SU_SOULATTACK', 'Soul Attack', ''),
  (5045, 'SU_POWEROFFLOCK', 'Power of Flock', ''),
  (5046, 'SU_SVG_SPIRIT', 'Spirit of Savage', ''),
  (5047, 'SU_HISS', 'Hiss', ''),
  (5048, 'SU_NYANGGRASS', 'Nyang Grass', ''),
  (5049, 'SU_GROOMING', 'Grooming', ''),
  (5050, 'SU_PURRING', 'Purring', ''),
  (5051, 'SU_SHRIMPARTY', 'Tasty Shrimp Party', ''),
  (5052, 'SU_SPIRITOFLIFE', 'Spirit of Life', ''),
  (5053, 'SU_MEOWMEOW', 'Meow Meow', ''),
  (5054, 'SU_SPIRITOFLAND', 'Spirit of Land', ''),
  (5055, 'SU_CHATTERING', 'Chattering', ''),
  (5056, 'SU_SPIRITOFSEA', 'Spirit of Sea', ''),
  (5063, 'WE_CALLALLFAMILY', 'Call All Family', ''),
  (5064, 'WE_ONEFOREVER', 'One Forever', ''),
  (5065, 'WE_CHEERUP', 'Cheer Up', ''),
  (5067, 'ALL_EQSWITCH', 'Equip Switch', ''),
  (5068, 'CG_SPECIALSINGER', 'Skilled Special Singer', ''),
  (5072, 'AB_VITUPERATUM', 'Vituperatum', ''),
  (5073, 'AB_CONVENIO', 'Convenio', ''),
  (5075, 'NV_BREAKTHROUGH', 'Break Through', ''),
  (5076, 'NV_HELPANGEL', 'Help Angel', ''),
  (5077, 'NV_TRANSCENDENCE', 'Transcendence', ''),
  (5078, 'WL_READING_SB_READING', 'Reading Spellbook', ''),
  (5201, 'DK_SERVANTWEAPON', 'Servant Weapon', ''),
  (5202, 'DK_SERVANTWEAPON_ATK', 'Servant Weapon Attack', ''),
  (5203, 'DK_SERVANT_W_SIGN', 'Servant Weapon Sign', ''),
  (5204, 'DK_SERVANT_W_PHANTOM', 'Servant Weapon Phantom', ''),
  (5205, 'DK_SERVANT_W_DEMOL', 'Servant Weapon Demolition', ''),
  (5206, 'DK_CHARGINGPIERCE', 'Charging Pierce', ''),
  (5207, 'DK_TWOHANDDEF', 'Two Hand Def', ''),
  (5208, 'DK_HACKANDSLASHER', 'Hack And Slasher', ''),
  (5209, 'DK_HACKANDSLASHER_ATK', 'Hack And Slasher Attack', ''),
  (5210, 'DK_DRAGONIC_AURA', 'Dragonic Aura', ''),
  (5211, 'DK_MADNESS_CRUSHER', 'Madness Crusher', ''),
  (5212, 'DK_VIGOR', 'Vigor', ''),
  (5213, 'DK_STORMSLASH', 'Storm Slash', ''),
  (5214, 'AG_DEADLY_PROJECTION', 'Deadly Projection', ''),
  (5215, 'AG_DESTRUCTIVE_HURRICANE', 'Destructive Hurricane', ''),
  (5216, 'AG_RAIN_OF_CRYSTAL', 'Rain Of Crystal', ''),
  (5217, 'AG_MYSTERY_ILLUSION', 'Mystery Illusion', ''),
  (5218, 'AG_VIOLENT_QUAKE', 'Violent Quake', ''),
  (5219, 'AG_VIOLENT_QUAKE_ATK', 'Violent Quake Attack', ''),
  (5220, 'AG_SOUL_VC_STRIKE', 'Soul Vulcan Strike', ''),
  (5221, 'AG_STRANTUM_TREMOR', 'Strantum Tremor', ''),
  (5222, 'AG_ALL_BLOOM', 'All Bloom', ''),
  (5223, 'AG_ALL_BLOOM_ATK', 'All Bloom Attack', ''),
  (5224, 'AG_ALL_BLOOM_ATK2', 'All Bloom Attack 2', ''),
  (5225, 'AG_CRYSTAL_IMPACT', 'Crystal Impact', ''),
  (5226, 'AG_CRYSTAL_IMPACT_ATK', 'Crystal Impact Attack', ''),
  (5227, 'AG_TORNADO_STORM', 'Tornado Storm', ''),
  (5228, 'AG_TWOHANDSTAFF', 'Two Hand Staff Mastery', ''),
  (5229, 'AG_FLORAL_FLARE_ROAD', 'Floral Flare Road', ''),
  (5230, 'AG_ASTRAL_STRIKE', 'Astral Strike', ''),
  (5231, 'AG_ASTRAL_STRIKE_ATK', 'Astral Strike Attack', ''),
  (5232, 'AG_CLIMAX', 'Climax', ''),
  (5233, 'AG_ROCK_DOWN', 'Rock Down', ''),
  (5234, 'AG_STORM_CANNON', 'Storm Cannon', ''),
  (5235, 'AG_CRIMSON_ARROW', 'Crimson Arrow', ''),
  (5236, 'AG_CRIMSON_ARROW_ATK', 'Crimson Arrow Attack', ''),
  (5237, 'AG_FROZEN_SLASH', 'Frozen Slash', ''),
  (5238, 'IQ_POWERFUL_FAITH', 'Powerful Faith', ''),
  (5239, 'IQ_FIRM_FAITH', 'Firm Faith', ''),
  (5240, 'IQ_WILL_OF_FAITH', 'Will Of Faith', ''),
  (5241, 'IQ_OLEUM_SANCTUM', 'Oleum Sanctum', ''),
  (5242, 'IQ_SINCERE_FAITH', 'Sincere Faith', ''),
  (5243, 'IQ_MASSIVE_F_BLASTER', 'Massive Flame Blaster', ''),
  (5244, 'IQ_EXPOSION_BLASTER', 'Explosion Blaster', ''),
  (5245, 'IQ_FIRST_BRAND', 'First Brand', ''),
  (5246, 'IQ_FIRST_FAITH_POWER', 'First Faith Power', ''),
  (5247, 'IQ_JUDGE', 'Judge', ''),
  (5248, 'IQ_SECOND_FLAME', 'Second Flame', ''),
  (5249, 'IQ_SECOND_FAITH', 'Second Faith', ''),
  (5250, 'IQ_SECOND_JUDGEMENT', 'Second Judgement', ''),
  (5251, 'IQ_THIRD_PUNISH', 'Third Punish', ''),
  (5252, 'IQ_THIRD_FLAME_BOMB', 'Third Flame Bomb', ''),
  (5253, 'IQ_THIRD_CONSECRATION', 'Third Consecration', ''),
  (5254, 'IQ_THIRD_EXOR_FLAME', 'Third Exorcism Flame', ''),
  (5255, 'IG_GUARD_STANCE', 'Guard Stance', ''),
  (5256, 'IG_GUARDIAN_SHIELD', 'Guardian Shield', ''),
  (5257, 'IG_REBOUND_SHIELD', 'Rebound Shield', ''),
  (5258, 'IG_SHIELD_MASTERY', 'Shield Mastery', ''),
  (5259, 'IG_SPEAR_SWORD_M', 'Spear And Sword Mastery', ''),
  (5260, 'IG_ATTACK_STANCE', 'Attack Stance', ''),
  (5261, 'IG_ULTIMATE_SACRIFICE', 'Ultimate Sacrifice', ''),
  (5262, 'IG_HOLY_SHIELD', 'Holy Shield', ''),
  (5263, 'IG_GRAND_JUDGEMENT', 'Grand Judgement', ''),
  (5264, 'IG_JUDGEMENT_CROSS', 'Judgement Cross', ''),
  (5265, 'IG_SHIELD_SHOOTING', 'Shield Shooting', ''),
  (5266, 'IG_OVERSLASH', 'Overslash', ''),
  (5267, 'IG_CROSS_RAIN', 'Cross Rain', ''),
  (5268, 'CD_REPARATIO', 'Reparatio', ''),
  (5269, 'CD_MEDIALE_VOTUM', 'Mediale Votum', ''),
  (5270, 'CD_MACE_BOOK_M', 'Mace Book Mastery', ''),
  (5271, 'CD_ARGUTUS_VITA', 'Argutus Vita', ''),
  (5272, 'CD_ARGUTUS_TELUM', 'Argutus Telum', ''),
  (5273, 'CD_ARBITRIUM', 'Arbitrium', ''),
  (5274, 'CD_ARBITRIUM_ATK', 'Arbitrium Attack', ''),
  (5275, 'CD_PRESENS_ACIES', 'Presens Acies', ''),
  (5276, 'CD_FIDUS_ANIMUS', 'Fidus Animus', ''),
  (5277, 'CD_EFFLIGO', 'Effligo', ''),
  (5278, 'CD_COMPETENTIA', 'Competentia', ''),
  (5279, 'CD_PNEUMATICUS_PROCELLA', 'Pneumaticus Procella', ''),
  (5280, 'CD_DILECTIO_HEAL', 'Dilectio Heal', ''),
  (5281, 'CD_RELIGIO', 'Religio', ''),
  (5282, 'CD_BENEDICTUM', 'Benedictum', ''),
  (5283, 'CD_PETITIO', 'Petitio', ''),
  (5284, 'CD_FRAMEN', 'Framen', ''),
  (5285, 'SHC_SHADOW_EXCEED', 'Shadow Exceed', ''),
  (5286, 'SHC_DANCING_KNIFE', 'Dancing Knife', ''),
  (5287, 'SHC_SAVAGE_IMPACT', 'Savage Impact', ''),
  (5288, 'SHC_SHADOW_SENSE', 'Shadow Sense', ''),
  (5289, 'SHC_ETERNAL_SLASH', 'Eternal Slash', ''),
  (5290, 'SHC_POTENT_VENOM', 'Potent Venom', ''),
  (5291, 'SHC_SHADOW_STAB', 'Shadow Stab', ''),
  (5292, 'SHC_IMPACT_CRATER', 'Impact Crater', ''),
  (5293, 'SHC_ENCHANTING_SHADOW', 'Enchanting Shadow', ''),
  (5294, 'SHC_FATAL_SHADOW_CROW', 'Fatal Shadow Crow', ''),
  (5295, 'MT_AXE_STOMP', 'Axe Stomp', ''),
  (5296, 'MT_RUSH_QUAKE', 'Rush Quake', ''),
  (5297, 'MT_M_MACHINE', 'Manufacture Machine', ''),
  (5298, 'MT_A_MACHINE', 'Attack Machine', ''),
  (5299, 'MT_D_MACHINE', 'Defense Machine', ''),
  (5300, 'MT_TWOAXEDEF', 'Two Hand Axe Def', ''),
  (5301, 'MT_ABR_M', 'ABR Mastery', ''),
  (5302, 'MT_SUMMON_ABR_BATTLE_WARIOR', 'ABR Battle Warior', ''),
  (5303, 'MT_SUMMON_ABR_DUAL_CANNON', 'ABR Dual Cannon', ''),
  (5304, 'MT_SUMMON_ABR_MOTHER_NET', 'ABR Mother Net', ''),
  (5305, 'MT_SUMMON_ABR_INFINITY', 'ABR Infinity', ''),
  (5306, 'AG_DESTRUCTIVE_HURRICANE_CLIMAX', 'Destructive Hurricane Climax', ''),
  (5307, 'BO_ACIDIFIED_ZONE_WATER_ATK', 'Actified Zone Water Attack', ''),
  (5308, 'BO_ACIDIFIED_ZONE_GROUND_ATK', 'Actified Zone Ground Attack', ''),
  (5309, 'BO_ACIDIFIED_ZONE_WIND_ATK', 'Actified Zone Wind Attack', ''),
  (5310, 'BO_ACIDIFIED_ZONE_FIRE_ATK', 'Actified Zone Fire Attack', ''),
  (5311, 'ABC_DAGGER_AND_BOW_M', 'Dagger And Bow Mastery', ''),
  (5312, 'ABC_MAGIC_SWORD_M', 'Magic Sword Mastery', ''),
  (5313, 'ABC_STRIP_SHADOW', 'Strip Shadow', ''),
  (5314, 'ABC_ABYSS_DAGGER', 'Abyss Dagger', ''),
  (5315, 'ABC_UNLUCKY_RUSH', 'Unlucky Rush', ''),
  (5316, 'ABC_CHAIN_REACTION_SHOT', 'Chain Reaction Shot', ''),
  (5317, 'ABC_FROM_THE_ABYSS', 'From The Abyss', ''),
  (5318, 'ABC_ABYSS_SLAYER', 'Abyss Slayer', ''),
  (5319, 'ABC_ABYSS_STRIKE', 'Omega Abyss Strike', ''),
  (5320, 'ABC_DEFT_STAB', 'Deft Stab', ''),
  (5321, 'ABC_ABYSS_SQUARE', 'Abyss Square', ''),
  (5322, 'ABC_FRENZY_SHOT', 'Frenzy Shot', ''),
  (5323, 'WH_ADVANCED_TRAP', 'Advanced Trap', ''),
  (5324, 'WH_WIND_SIGN', 'Wind Sign', ''),
  (5325, 'WH_NATUREFRIENDLY', 'Nature Friendly', ''),
  (5326, 'WH_HAWKRUSH', 'Hawk Rush', ''),
  (5327, 'WH_HAWK_M', 'Hawk Mastery', ''),
  (5328, 'WH_CALAMITYGALE', 'Calamity Gale', ''),
  (5329, 'WH_HAWKBOOMERANG', 'Hawk Boomerang', ''),
  (5330, 'WH_GALESTORM', 'Gale Storm', ''),
  (5331, 'WH_DEEPBLINDTRAP', 'Deep Blind Trap', ''),
  (5332, 'WH_SOLIDTRAP', 'Solid Trap', ''),
  (5333, 'WH_SWIFTTRAP', 'Swift Trap', ''),
  (5334, 'WH_CRESCIVE_BOLT', 'Crescive Bolt', ''),
  (5335, 'WH_FLAMETRAP', 'Flame Trap', ''),
  (5336, 'BO_BIONIC_PHARMACY', 'Bionic Pharmacy', ''),
  (5337, 'BO_BIONICS_M', 'Bionics Mastery', ''),
  (5338, 'BO_THE_WHOLE_PROTECTION', 'The Whole Protection', ''),
  (5339, 'BO_ADVANCE_PROTECTION', 'Advance Protection', ''),
  (5340, 'BO_ACIDIFIED_ZONE_WATER', 'Acidified Zone Water', ''),
  (5341, 'BO_ACIDIFIED_ZONE_GROUND', 'Acidified Zone Ground', ''),
  (5342, 'BO_ACIDIFIED_ZONE_WIND', 'Acidified Zone Wind', ''),
  (5343, 'BO_ACIDIFIED_ZONE_FIRE', 'Acidified Zone Fire', ''),
  (5344, 'BO_WOODENWARRIOR', 'Wooden Warrior', ''),
  (5345, 'BO_WOODEN_FAIRY', 'Wooden Fairy', ''),
  (5346, 'BO_CREEPER', 'Creeper', ''),
  (5347, 'BO_RESEARCHREPORT', 'Research Report', ''),
  (5348, 'BO_HELLTREE', 'Hell Tree', ''),
  (5349, 'TR_STAGE_MANNER', 'Stage Manner', ''),
  (5350, 'TR_RETROSPECTION', 'Retrospection', ''),
  (5351, 'TR_MYSTIC_SYMPHONY', 'Mystic Symphony', ''),
  (5352, 'TR_KVASIR_SONATA', 'Kvasir Sonata', ''),
  (5353, 'TR_ROSEBLOSSOM', 'Rose Blossom', ''),
  (5354, 'TR_ROSEBLOSSOM_ATK', 'Rose Blossom Attack', ''),
  (5355, 'TR_RHYTHMSHOOTING', 'Rhythm Shooting', ''),
  (5356, 'TR_METALIC_FURY', 'Metallic Fury', ''),
  (5357, 'TR_SOUNDBLEND', 'Sound Blend', ''),
  (5358, 'TR_GEF_NOCTURN', 'Geffenia Nocturn', ''),
  (5359, 'TR_ROKI_CAPRICCIO', 'Roki Capriccio', ''),
  (5360, 'TR_AIN_RHAPSODY', 'Ain Rhapsody', ''),
  (5361, 'TR_MUSICAL_INTERLUDE', 'Musical Interlude', ''),
  (5362, 'TR_JAWAII_SERENADE', 'Jawaii Serenade', ''),
  (5363, 'TR_NIPELHEIM_REQUIEM', 'Nipelheim Requiem', ''),
  (5364, 'TR_PRON_MARCH', 'Pron March', ''),
  (5365, 'EM_MAGIC_BOOK_M', 'Magic Book Mastery', ''),
  (5366, 'EM_SPELL_ENCHANTING', 'Spell Enchanting', ''),
  (5367, 'EM_ACTIVITY_BURN', 'Activity Burn', ''),
  (5368, 'EM_INCREASING_ACTIVITY', 'Increasing Activity', ''),
  (5369, 'EM_DIAMOND_STORM', 'Diamond Storm', ''),
  (5370, 'EM_LIGHTNING_LAND', 'Lightning Land', ''),
  (5371, 'EM_VENOM_SWAMP', 'Venom Swamp', ''),
  (5372, 'EM_CONFLAGRATION', 'Conflagration', ''),
  (5373, 'EM_TERRA_DRIVE', 'Terra Drive', ''),
  (5374, 'EM_ELEMENTAL_SPIRIT_M', 'Elemental Spirit Mastery', ''),
  (5375, 'EM_SUMMON_ELEMENTAL_ARDOR', 'Summon Elemental Ardor', ''),
  (5376, 'EM_SUMMON_ELEMENTAL_DILUVIO', 'Summon Elemental Diluvio', ''),
  (5377, 'EM_SUMMON_ELEMENTAL_PROCELLA', 'Summon Elemental Procella', ''),
  (5378, 'EM_SUMMON_ELEMENTAL_TERREMOTUS', 'Summon Elemental Terremotus', ''),
  (5379, 'EM_SUMMON_ELEMENTAL_SERPENS', 'Summon Elemental Serpens', ''),
  (5380, 'EM_ELEMENTAL_BUSTER', 'Elemental Buster', ''),
  (5381, 'EM_ELEMENTAL_VEIL', 'Elemental Veil', ''),
  (5382, 'ABC_CHAIN_REACTION_SHOT_ATK', 'Chain Reaction Shot Attack', ''),
  (5383, 'ABC_FROM_THE_ABYSS_ATK', 'From The Abyss Attack', ''),
  (5384, 'BO_WOODEN_THROWROCK', 'Wooden Throw Rock', ''),
  (5385, 'BO_WOODEN_ATTACK', 'Wooden Attack', ''),
  (5386, 'BO_HELL_HOWLING', 'Hell Howling', ''),
  (5387, 'BO_HELL_DUSTY', 'Hell Dusty', ''),
  (5388, 'BO_FAIRY_DUSTY', 'Fairy Dusty', ''),
  (5389, 'EM_ELEMENTAL_BUSTER_FIRE', 'Elemental Buster Fire', ''),
  (5390, 'EM_ELEMENTAL_BUSTER_WATER', 'Elemental Buster Water', ''),
  (5391, 'EM_ELEMENTAL_BUSTER_WIND', 'Elemental Buster Wind', ''),
  (5392, 'EM_ELEMENTAL_BUSTER_GROUND', 'Elemental Buster Ground', ''),
  (5393, 'EM_ELEMENTAL_BUSTER_POISON', 'Elemental Buster Poison', ''),
  (5433, 'SH_MYSTICAL_CREATURE_MASTERY', 'Mystical Creature Mastery', ''),
  (5434, 'SH_COMMUNE_WITH_CHUL_HO', 'Commune with Chulho', ''),
  (5435, 'SH_CHUL_HO_SONIC_CLAW', 'Chulho Sonic Claw', ''),
  (5436, 'SH_HOWLING_OF_CHUL_HO', 'Howling of Chulho', ''),
  (5437, 'SH_HOGOGONG_STRIKE', 'Hogogong Strike', ''),
  (5438, 'SH_COMMUNE_WITH_KI_SUL', 'Commune with Kisul', ''),
  (5439, 'SH_KI_SUL_WATER_SPRAYING', 'Kisul Water Spraying', ''),
  (5440, 'SH_MARINE_FESTIVAL_OF_KI_SUL', 'Marine Festival of Kisul', ''),
  (5441, 'SH_SANDY_FESTIVAL_OF_KI_SUL', 'Sandy Festival of Kisul', ''),
  (5442, 'SH_KI_SUL_RAMPAGE', 'Kisul Rampage', ''),
  (5443, 'SH_COMMUNE_WITH_HYUN_ROK', 'Commune with Hyunrok', ''),
  (5444, 'SH_COLORS_OF_HYUN_ROK', 'Colors of Hyunrok', ''),
  (5445, 'SH_HYUN_ROKS_BREEZE', 'Hyunrok Breeze', ''),
  (5446, 'SH_HYUN_ROK_CANNON', 'Hyunrok Cannon', ''),
  (5447, 'SH_TEMPORARY_COMMUNION', 'Temporary Communion', ''),
  (5448, 'SH_BLESSING_OF_MYSTICAL_CREATURES', 'Blessing of Mystical Creatures', ''),
  (5401, 'NW_P_F_I', 'P.F.I', ''),
  (5402, 'NW_GRENADE_MASTERY', 'Grenade Mastery', ''),
  (5403, 'NW_INTENSIVE_AIM', 'Intensive Aim', ''),
  (5404, 'NW_GRENADE_FRAGMENT', 'Grenade Fragment', ''),
  (5405, 'NW_THE_VIGILANTE_AT_NIGHT', 'The Vigilante at Night', ''),
  (5406, 'NW_ONLY_ONE_BULLET', 'Only One Bullet', ''),
  (5407, 'NW_SPIRAL_SHOOTING', 'Spiral Shooting', ''),
  (5408, 'NW_MAGAZINE_FOR_ONE', 'Magazine for One', ''),
  (5409, 'NW_WILD_FIRE', 'Wild Fire', ''),
  (5410, 'NW_BASIC_GRENADE', 'Basic Grenade', ''),
  (5411, 'NW_HASTY_FIRE_IN_THE_HOLE', 'Hasty Fire in the Hole', ''),
  (5412, 'NW_GRENADES_DROPPING', 'Grenades Dropping', ''),
  (5413, 'NW_AUTO_FIRING_LAUNCHER', 'Auto Firing Launcher', ''),
  (5414, 'NW_HIDDEN_CARD', 'Hidden Card', ''),
  (5415, 'NW_MISSION_BOMBARD', 'Mission Bombard', ''),
  (5416, 'SOA_TALISMAN_MASTERY', 'Talisman Mastery', ''),
  (5417, 'SOA_SOUL_MASTERY', 'Soul Mastery', ''),
  (5418, 'SOA_TALISMAN_OF_PROTECTION', 'Talisman Of Protection', ''),
  (5419, 'SOA_TALISMAN_OF_WARRIOR', 'Talisman Of Warrior', ''),
  (5420, 'SOA_TALISMAN_OF_MAGICIAN', 'Talisman Of Magician', ''),
  (5421, 'SOA_SOUL_GATHERING', 'Soul Gathering', ''),
  (5422, 'SOA_TOTEM_OF_TUTELARY', 'Totem Of Tutelary', ''),
  (5423, 'SOA_TALISMAN_OF_FIVE_ELEMENTS', 'Talisman Of Five Elements', ''),
  (5424, 'SOA_TALISMAN_OF_SOUL_STEALING', 'Talisman Of Soul Stealing', ''),
  (5425, 'SOA_EXORCISM_OF_MALICIOUS_SOUL', 'Exorcism Of Malicious Soul', ''),
  (5426, 'SOA_TALISMAN_OF_BLUE_DRAGON', 'Talisman Of Blue Dragon', ''),
  (5427, 'SOA_TALISMAN_OF_WHITE_TIGER', 'Talisman Of White Tiger', ''),
  (5428, 'SOA_TALISMAN_OF_RED_PHOENIX', 'Talisman Of Red Phoenix', ''),
  (5429, 'SOA_TALISMAN_OF_BLACK_TORTOISE', 'Talisman Of Black Tortoise', ''),
  (5430, 'SOA_TALISMAN_OF_FOUR_BEARING_GOD', 'Talisman Of Four Bearing God', ''),
  (5431, 'SOA_CIRCLE_OF_DIRECTIONS_AND_ELEMENTALS', 'Circle Of Directions And Elementals', ''),
  (5432, 'SOA_SOUL_OF_HEAVEN_AND_EARTH', 'Soul Of Heaven And Earth', ''),
  (5449, 'HN_SELFSTUDY_TATICS', 'Self Study Tactics', ''),
  (5450, 'HN_SELFSTUDY_SOCERY', 'Self Study Sorcery', ''),
  (5451, 'HN_DOUBLEBOWLINGBASH', 'Double Bowling Bash', ''),
  (5452, 'HN_MEGA_SONIC_BLOW', 'Mega Sonic Blow', ''),
  (5453, 'HN_SHIELD_CHAIN_RUSH', 'Shield Chain Rush', ''),
  (5454, 'HN_SPIRAL_PIERCE_MAX', 'Spiral Pierce Max', ''),
  (5455, 'HN_METEOR_STORM_BUSTER', 'Meteor Storm Buster', ''),
  (5456, 'HN_JUPITEL_THUNDER_STORM', 'Jupitel Thunderstorm', ''),
  (5457, 'HN_JACK_FROST_NOVA', 'Jack Frost Nova', ''),
  (5458, 'HN_HELLS_DRIVE', 'Hell''s Drive', ''),
  (5459, 'HN_GROUND_GRAVITATION', 'Ground Gravitation', ''),
  (5460, 'HN_NAPALM_VULCAN_STRIKE', 'Napalm Vulcan Strike', ''),
  (5461, 'HN_BREAKINGLIMIT', 'Breaking Limit', ''),
  (5462, 'HN_RULEBREAK', 'Rule Break', ''),
  (5463, 'SKE_SKY_MASTERY', 'Sky Mastery', ''),
  (5464, 'SKE_WAR_BOOK_MASTERY', 'War Book Mastery', ''),
  (5465, 'SKE_RISING_SUN', 'Rising Sun', ''),
  (5466, 'SKE_NOON_BLAST', 'Noon Blast', ''),
  (5467, 'SKE_SUNSET_BLAST', 'Sunset Blast', ''),
  (5468, 'SKE_RISING_MOON', 'Rising Moon', ''),
  (5469, 'SKE_MIDNIGHT_KICK', 'Midnight Kick', ''),
  (5470, 'SKE_DAWN_BREAK', 'Dawn Break', ''),
  (5471, 'SKE_TWINKLING_GALAXY', 'Twinkling Galaxy', ''),
  (5472, 'SKE_STAR_BURST', 'Star Burst', ''),
  (5473, 'SKE_STAR_CANNON', 'Star Cannon', ''),
  (5474, 'SKE_ALL_IN_THE_SKY', 'All in the Sky', ''),
  (5475, 'SKE_ENCHANTING_SKY', 'Enchanting Sky', ''),
  (5476, 'SS_TOKEDASU', 'Melt Away', ''),
  (5477, 'SS_SHIMIRU', 'Infiltrate', ''),
  (5478, 'SS_AKUMUKESU', 'Nightmare Erasion', ''),
  (5479, 'SS_SHINKIROU', 'Mirage', ''),
  (5480, 'SS_KAGEGARI', 'Shadow Hunting', ''),
  (5481, 'SS_KAGENOMAI', 'Shadow Dance', ''),
  (5482, 'SS_KAGEGISSEN', 'Shadow Flash', ''),
  (5483, 'SS_FUUMASHOUAKU', 'Huuma Shuriken - Grasp', ''),
  (5484, 'SS_FUUMAKOUCHIKU', 'Huuma Shuriken - Construct', ''),
  (5485, 'SS_KUNAIWAIKYOKU', 'Kunai - Distortion', ''),
  (5486, 'SS_KUNAIKAITEN', 'Kunai - Rotation', ''),
  (5487, 'SS_KUNAIKUSSETSU', 'Kunai - Refraction', ''),
  (5488, 'SS_SEKIENHOU', 'Red Flame Cannon', ''),
  (5489, 'SS_REIKETSUHOU', 'Cold Blooded Cannon', ''),
  (5490, 'SS_RAIDENPOU', 'Thundering Cannon', ''),
  (5491, 'SS_KINRYUUHOU', 'Golden Dragon Cannon', ''),
  (5492, 'SS_ANTENPOU', 'Darkening Cannon', ''),
  (5493, 'SS_KAGEAKUMU', 'Shadow - Nightmare', ''),
  (5494, 'SS_HITOUAKUMU', 'Kunai - Nightmare', ''),
  (5495, 'SS_ANKOKURYUUAKUMU', 'Dark Dragon - Nightmare', ''),
  (5496, 'NW_THE_VIGILANTE_AT_NIGHT_GUN_GATLING', 'The Vigilante At Night Gun Gatling', ''),
  (5497, 'NW_THE_VIGILANTE_AT_NIGHT_GUN_SHOTGUN', 'The Vigilante At Night Gun Shotgun', ''),
  (5499, 'SS_FOUR_CHARM', 'Four Colors Charm', ''),
  (5500, 'NW_WILD_SHOT', 'Wild Shot', ''),
  (5501, 'NW_MIDNIGHT_FALLEN', 'Midnight Fallen', ''),
  (5502, 'SKE_SKY_SUN', 'Sky Sun', ''),
  (5503, 'SKE_SKY_MOON', 'Sky Moon', ''),
  (5504, 'SKE_STAR_LIGHT_KICK', 'Star Light Kick', ''),
  (5506, 'SH_CHUL_HO_BATTERING', 'Chulho Battering', ''),
  (5507, 'SH_HYUN_ROK_SPIRIT_POWER', 'Hyunrok Spirit Power', ''),
  (5505, 'HN_OVERCOMING_CRISIS', 'Overcoming Crisis', ''),
  (6001, 'DK_DRAGONIC_BREATH', 'Dragonic Breath', ''),
  (6002, 'MT_SPARK_BLASTER', 'Spark Blaster', ''),
  (6003, 'MT_TRIPLE_LASER', 'Triple Laser', ''),
  (6004, 'MT_MIGHTY_SMASH', 'Mighty Smash', ''),
  (6005, 'BO_EXPLOSIVE_POWDER', 'Explosive Powder', ''),
  (6006, 'BO_MAYHEMIC_THORNS', 'Mayhemic Thorns', ''),
  (6502, 'DK_DRAGONIC_PIERCE', 'Dragonic Pierce', ''),
  (6503, 'IG_RADIANT_SPEAR', 'Radiant Spear', ''),
  (6504, 'IG_IMPERIAL_CROSS', 'Imperial Cross', ''),
  (6505, 'IG_IMPERIAL_PRESSURE', 'Imperial Pressure', ''),
  (6506, 'MT_RUSH_STRIKE', 'Rush Strike', ''),
  (6507, 'MT_POWERFUL_SWING', 'Powerful Swing', ''),
  (6508, 'MT_ENERGY_CANNONADE', 'Energy Cannonade', ''),
  (6509, 'BO_MYSTERY_POWDER', 'Mystery Powder', ''),
  (6510, 'BO_DUST_EXPLOSION', 'Dust Explosion', ''),
  (6512, 'ABC_HIT_AND_SLIDING', 'Hit And Sliding', ''),
  (6513, 'ABC_CHASING_BREAK', 'Chasing Break', ''),
  (6514, 'ABC_CHASING_SHOT', 'Chasing Shot', ''),
  (6516, 'AG_ENERGY_CONVERSION', 'Energy Conversion', ''),
  (6511, 'SHC_CROSS_SLASH', 'Cross Slash', ''),
  (6515, 'ABC_ABYSS_FLAME', 'Abyss Flame', ''),
  (6517, 'EM_PSYCHIC_STREAM', 'Psychic Stream', ''),
  (6518, 'CD_DIVINUS_FLOS', 'Divinus Flos', ''),
  (6519, 'IQ_BLAZING_FLAME_BLAST', 'Blazing Flame Blast', ''),
  (6520, 'WH_WILD_WALK', 'Wild Walk', ''),
  (6521, 'TR_RHYTHMICAL_WAVE', 'Rhythmical Wave', ''),
  (6522, 'ABC_ABYSS_FLAME_ATK', 'Abyss Flame Attack', ''),
  (8001, 'HLIF_HEAL', 'Healing Touch', ''),
  (8002, 'HLIF_AVOID', 'Avoid', ''),
  (8003, 'HLIF_BRAIN', 'Brain Surgery', ''),
  (8004, 'HLIF_CHANGE', 'Change', ''),
  (8005, 'HAMI_CASTLE', 'Castling', ''),
  (8006, 'HAMI_DEFENCE', 'Defense', ''),
  (8007, 'HAMI_SKIN', 'Adamantium Skin', ''),
  (8008, 'HAMI_BLOODLUST', 'Bloodlust', ''),
  (8009, 'HFLI_MOON', 'Moonlight', ''),
  (8010, 'HFLI_FLEET', 'Fleeting Move', ''),
  (8011, 'HFLI_SPEED', 'Speed', ''),
  (8012, 'HFLI_SBR44', 'S.B.R.44', ''),
  (8013, 'HVAN_CAPRICE', 'Caprice', ''),
  (8014, 'HVAN_CHAOTIC', 'Benediction of Chaos', ''),
  (8015, 'HVAN_INSTRUCT', 'Instruct', ''),
  (8016, 'HVAN_EXPLOSION', 'Bio Explosion', ''),
  (8018, 'MH_SUMMON_LEGION', 'Summon Legion', ''),
  (8019, 'MH_NEEDLE_OF_PARALYZE', 'Needle of Paralyze', ''),
  (8020, 'MH_POISON_MIST', 'Poison Mist', ''),
  (8021, 'MH_PAIN_KILLER', 'Pain Killer', ''),
  (8022, 'MH_LIGHT_OF_REGENE', 'Light of Regene', ''),
  (8023, 'MH_OVERED_BOOST', 'Overed Boost', ''),
  (8024, 'MH_ERASER_CUTTER', 'Eraser Cutter', ''),
  (8025, 'MH_XENO_SLASHER', 'Xeno Slasher', ''),
  (8026, 'MH_SILENT_BREEZE', 'Silent Breeze', ''),
  (8027, 'MH_STYLE_CHANGE', 'Style Change', ''),
  (8028, 'MH_SONIC_CRAW', 'Sonic Claw', ''),
  (8029, 'MH_SILVERVEIN_RUSH', 'Silver Bain Rush', ''),
  (8030, 'MH_MIDNIGHT_FRENZY', 'Midnight Frenzy', ''),
  (8031, 'MH_STAHL_HORN', 'Steel Horn', ''),
  (8032, 'MH_GOLDENE_FERSE', 'Golden Heel', ''),
  (8033, 'MH_STEINWAND', 'Stone Wall', ''),
  (8034, 'MH_HEILIGE_STANGE', 'Holy Pole', ''),
  (8035, 'MH_ANGRIFFS_MODUS', 'Attack Mode', ''),
  (8036, 'MH_TINDER_BREAKER', 'Tinder Breaker', ''),
  (8037, 'MH_CBC', 'Continual Break Combo', ''),
  (8038, 'MH_EQC', 'Eternal Quick Combo', ''),
  (8039, 'MH_MAGMA_FLOW', 'Magma Flow', ''),
  (8040, 'MH_GRANITIC_ARMOR', 'Granitic Armor', ''),
  (8041, 'MH_LAVA_SLIDE', 'Lava Slide', ''),
  (8042, 'MH_PYROCLASTIC', 'Pyroclastic', ''),
  (8043, 'MH_VOLCANIC_ASH', 'Volcanic Ash', ''),
  (8044, 'MH_BLAST_FORGE', 'Blast Forge', ''),
  (8045, 'MH_TEMPERING', 'Tempering', ''),
  (8046, 'MH_CLASSY_FLUTTER', 'Classy Flutter', ''),
  (8047, 'MH_TWISTER_CUTTER', 'Twister Cutter', ''),
  (8048, 'MH_ABSOLUTE_ZEPHYR', 'Absolute Zephyr', ''),
  (8049, 'MH_BRUSHUP_CLAW', 'Brushup Claw', ''),
  (8050, 'MH_BLAZING_AND_FURIOUS', 'Blazing And Furious', ''),
  (8051, 'MH_THE_ONE_FIGHTER_RISES', 'The One Fighter Rises', ''),
  (8052, 'MH_POLISHING_NEEDLE', 'Polishing Needle', ''),
  (8053, 'MH_TOXIN_OF_MANDARA', 'Toxin Of Mandara', ''),
  (8054, 'MH_NEEDLE_STINGER', 'Needle Stinger', ''),
  (8055, 'MH_LICHT_GEHORN', 'Licht Gehorn', ''),
  (8056, 'MH_GLANZEN_SPIES', 'Glanzen Spies', ''),
  (8057, 'MH_HEILIGE_PFERD', 'Heilige Pferd', ''),
  (8058, 'MH_GOLDENE_TONE', 'Goldene Tone', ''),
  (8059, 'MH_BLAZING_LAVA', 'Blazing Lava', ''),
  (8201, 'MS_BASH', 'Bash', ''),
  (8202, 'MS_MAGNUM', 'Magnum_Break', ''),
  (8203, 'MS_BOWLINGBASH', 'Bowling_Bash', ''),
  (8204, 'MS_PARRYING', 'Parry', ''),
  (8205, 'MS_REFLECTSHIELD', 'Shield_Reflect', ''),
  (8206, 'MS_BERSERK', 'Frenzy', ''),
  (8207, 'MA_DOUBLE', 'Double_Strafe', ''),
  (8208, 'MA_SHOWER', 'Arrow_Shower', ''),
  (8209, 'MA_SKIDTRAP', 'Skid_Trap', ''),
  (8210, 'MA_LANDMINE', 'Land_Mine', ''),
  (8211, 'MA_SANDMAN', 'Sandman', ''),
  (8212, 'MA_FREEZINGTRAP', 'Freezing_Trap', ''),
  (8213, 'MA_REMOVETRAP', 'Remove_Trap', ''),
  (8214, 'MA_CHARGEARROW', 'Arrow_Repel', ''),
  (8215, 'MA_SHARPSHOOTING', 'Focused_Arrow_Strike', ''),
  (8216, 'ML_PIERCE', 'Pierce', ''),
  (8217, 'ML_BRANDISH', 'Brandish_Spear', ''),
  (8218, 'ML_SPIRALPIERCE', 'Spiral_Pierce', ''),
  (8219, 'ML_DEFENDER', 'Defending_Aura', ''),
  (8220, 'ML_AUTOGUARD', 'Guard', ''),
  (8221, 'ML_DEVOTION', 'Sacrifice', ''),
  (8222, 'MER_MAGNIFICAT', 'Magnificat', ''),
  (8223, 'MER_QUICKEN', 'Two-Hand_Quicken', ''),
  (8224, 'MER_SIGHT', 'Sight', ''),
  (8225, 'MER_CRASH', 'Crash', ''),
  (8226, 'MER_REGAIN', 'Regain', ''),
  (8227, 'MER_TENDER', 'Tender', ''),
  (8228, 'MER_BENEDICTION', 'Benediction', ''),
  (8229, 'MER_RECUPERATE', 'Recuperate', ''),
  (8230, 'MER_MENTALCURE', 'Mental_Cure', ''),
  (8231, 'MER_COMPRESS', 'Compress', ''),
  (8232, 'MER_PROVOKE', 'Provoke', ''),
  (8233, 'MER_AUTOBERSERK', 'Berserk', ''),
  (8234, 'MER_DECAGI', 'Decrease_AGI', ''),
  (8235, 'MER_SCAPEGOAT', 'Scapegoat', ''),
  (8236, 'MER_LEXDIVINA', 'Lex_Divina', ''),
  (8237, 'MER_ESTIMATION', 'Sense', ''),
  (8238, 'MER_KYRIE', 'Kyrie Eleison', ''),
  (8239, 'MER_BLESSING', 'Blessing', ''),
  (8240, 'MER_INCAGI', 'Increase Agility', ''),
  (8241, 'MER_INVINCIBLEOFF2', 'Mind Blaster', ''),
  (8401, 'EL_CIRCLE_OF_FIRE', 'Circle of Fire', ''),
  (8402, 'EL_FIRE_CLOAK', 'Fire Cloak', ''),
  (8403, 'EL_FIRE_MANTLE', 'Fire Mantle', ''),
  (8404, 'EL_WATER_SCREEN', 'Water Screen', ''),
  (8405, 'EL_WATER_DROP', 'Water Drop', ''),
  (8406, 'EL_WATER_BARRIER', 'Water Barrier', ''),
  (8407, 'EL_WIND_STEP', 'Wind Step', ''),
  (8408, 'EL_WIND_CURTAIN', 'Wind Curtain', ''),
  (8409, 'EL_ZEPHYR', 'Zephyr', ''),
  (8410, 'EL_SOLID_SKIN', 'Solid Skin', ''),
  (8411, 'EL_STONE_SHIELD', 'Stone Shield', ''),
  (8412, 'EL_POWER_OF_GAIA', 'Power of Gaia', ''),
  (8413, 'EL_PYROTECHNIC', 'Pyrotechnic', ''),
  (8414, 'EL_HEATER', 'Heater', ''),
  (8415, 'EL_TROPIC', 'Tropic', ''),
  (8416, 'EL_AQUAPLAY', 'Aqua Play', ''),
  (8417, 'EL_COOLER', 'Cooler', ''),
  (8418, 'EL_CHILLY_AIR', 'Cool Air', ''),
  (8419, 'EL_GUST', 'Gust', ''),
  (8420, 'EL_BLAST', 'Blast', ''),
  (8421, 'EL_WILD_STORM', 'Wild Storm', ''),
  (8422, 'EL_PETROLOGY', 'Petrology', ''),
  (8423, 'EL_CURSED_SOIL', 'Cursed Soil', ''),
  (8424, 'EL_UPHEAVAL', 'Upheaval', ''),
  (8425, 'EL_FIRE_ARROW', 'Fire Arrow', ''),
  (8426, 'EL_FIRE_BOMB', 'Fire Bomb', ''),
  (8427, 'EL_FIRE_BOMB_ATK', 'Fire Bomb Attack', ''),
  (8428, 'EL_FIRE_WAVE', 'Fire Wave', ''),
  (8429, 'EL_FIRE_WAVE_ATK', 'Fire Wave Attack', ''),
  (8430, 'EL_ICE_NEEDLE', 'Ice Needle', ''),
  (8431, 'EL_WATER_SCREW', 'Water Screw', ''),
  (8432, 'EL_WATER_SCREW_ATK', 'Water Screw Attack', ''),
  (8433, 'EL_TIDAL_WEAPON', 'Tidal Weapon', ''),
  (8434, 'EL_WIND_SLASH', 'Wind Slasher', ''),
  (8435, 'EL_HURRICANE', 'Hurricane Rage', ''),
  (8436, 'EL_HURRICANE_ATK', 'Hurricane Rage Attack', ''),
  (8437, 'EL_TYPOON_MIS', 'Typhoon Missile', ''),
  (8438, 'EL_TYPOON_MIS_ATK', 'Typhoon Missile Attack', ''),
  (8439, 'EL_STONE_HAMMER', 'Stone Hammer', ''),
  (8440, 'EL_ROCK_CRUSHER', 'Rock Launcher', ''),
  (8441, 'EL_ROCK_CRUSHER_ATK', 'Rock Launcher Attack', ''),
  (8442, 'EL_STONE_RAIN', 'Stone Rain', ''),
  (8443, 'EM_EL_FLAMETECHNIC', 'Flame Technic', ''),
  (8444, 'EM_EL_FLAMEARMOR', 'Flame Armor', ''),
  (8445, 'EM_EL_FLAMEROCK', 'Flame Rock', ''),
  (8446, 'EM_EL_COLD_FORCE', 'Cold Force', ''),
  (8447, 'EM_EL_CRYSTAL_ARMOR', 'Crystal Armor', ''),
  (8448, 'EM_EL_AGE_OF_ICE', 'Age Of Ice', ''),
  (8449, 'EM_EL_GRACE_BREEZE', 'Grace Breeze', ''),
  (8450, 'EM_EL_EYES_OF_STORM', 'Eyes Of Storm', ''),
  (8451, 'EM_EL_STORM_WIND', 'Storm Wind', ''),
  (8452, 'EM_EL_EARTH_CARE', 'Earth Care', ''),
  (8453, 'EM_EL_STRONG_PROTECTION', 'Strong Protection', ''),
  (8454, 'EM_EL_AVALANCHE', 'Avalanche', ''),
  (8455, 'EM_EL_DEEP_POISONING', 'Deep Poisoning', ''),
  (8456, 'EM_EL_POISON_SHIELD', 'Poison Shield', ''),
  (8457, 'EM_EL_DEADLY_POISON', 'Deadly Poison', ''),
  (8601, 'ABR_BATTLE_BUSTER', 'Battle Buster', ''),
  (8602, 'ABR_DUAL_CANNON_FIRE', 'Dual Cannon Fire', ''),
  (8603, 'ABR_NET_REPAIR', 'Net Repair', ''),
  (8604, 'ABR_NET_SUPPORT', 'Net Support', ''),
  (8605, 'ABR_INFINITY_BUSTER', 'Infinity Buster', ''),
  (10000, 'GD_APPROVAL', 'Official Guild Approval', ''),
  (10001, 'GD_KAFRACONTRACT', 'Kafra Contract', ''),
  (10002, 'GD_GUARDRESEARCH', 'Guardian Research', ''),
  (10003, 'GD_GUARDUP', 'Strengthen Guardians', ''),
  (10004, 'GD_EXTENSION', 'Guild Extension', ''),
  (10005, 'GD_GLORYGUILD', 'Guild''s Glory', ''),
  (10006, 'GD_LEADERSHIP', 'Great Leadership', ''),
  (10007, 'GD_GLORYWOUNDS', 'Glorious Wounds', ''),
  (10008, 'GD_SOULCOLD', 'Cold Heart', ''),
  (10009, 'GD_HAWKEYES', 'Sharp Gaze', ''),
  (10010, 'GD_BATTLEORDER', 'Battle Orders', ''),
  (10011, 'GD_REGENERATION', 'Regeneration', ''),
  (10012, 'GD_RESTORE', 'Restoration', ''),
  (10013, 'GD_EMERGENCYCALL', 'Urgent Call', ''),
  (10014, 'GD_DEVELOPMENT', 'Permanent Development', ''),
  (10015, 'GD_ITEMEMERGENCYCALL', 'Item Emergency Call', ''),
  (10016, 'GD_GUILD_STORAGE', 'Guild Storage Expansion', ''),
  (10017, 'GD_CHARGESHOUT_FLAG', 'Charge Shout Flag', ''),
  (10018, 'GD_CHARGESHOUT_BEATING', 'Charge Shout Beating', ''),
  (10019, 'GD_EMERGENCY_MOVE', 'Emergency Move', '')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    type = EXCLUDED.type;
