package com.ragnarok.application.service;

import com.ragnarok.AbstractIntegrationTest;
import com.ragnarok.domain.exception.GameException;
import com.ragnarok.domain.model.EquipSlot;
import com.ragnarok.domain.model.Item;
import com.ragnarok.domain.model.ItemType;
import com.ragnarok.infrastructure.persistence.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class ItemServiceIntegrationTest extends AbstractIntegrationTest {

    @Autowired private ItemService itemService;
    @Autowired private PlayerRepository playerRepository;
    @Autowired private ItemRepository itemRepository;
    @Autowired private PlayerItemRepository playerItemRepository;

    @Test
    @DisplayName("Deve persistir item diretamente no repositório e recuperá-lo corretamente")
    @Transactional
    void devePersistirERecuperarItem() {
        createMockItem(9999L, "Espada Lendária", EquipSlot.HAND_R);

        ItemEntity salvo = itemRepository.findById(9999L).orElseThrow();
        assertEquals("Espada Lendária", salvo.getName());
        assertEquals(ItemType.WEAPON, salvo.getType());
        assertEquals(EquipSlot.HAND_R, salvo.getEquipSlot());
    }

    @Test
    @DisplayName("Deve realizar o ciclo completo: Dar item, Equipar e Trocar (Swap)")
    @Transactional
    void deveGerenciarEquipamentoETroca() {
        // 1. Setup: Cria Jogador usando Setters (Mais seguro)
        PlayerEntity player = new PlayerEntity();
        player.setName("Hero");
        player.setJobClass("Knight");
        // O ID é gerado automaticamente ao salvar, ou null se não for AutoGenerated.
        // Se sua entidade usa GenerationType.IDENTITY, não sete o ID.

        player = playerRepository.save(player);

        // Cria Definições no banco
        createMockItem(101L, "Espada de Madeira", EquipSlot.HAND_R);
        createMockItem(102L, "Espada de Ferro", EquipSlot.HAND_R);

        // 2. Dar os itens ao jogador
        itemService.darItemAoJogador(player.getId(), 101L, 1);
        itemService.darItemAoJogador(player.getId(), 102L, 1);

        // Recupera os IDs das instâncias físicas (UUIDs)
        List<PlayerItemEntity> inventario = playerItemRepository.findByPlayerId(player.getId());
        UUID idEspadaMadeira = inventario.stream().filter(i -> i.getItem().getId().equals(101L)).findFirst().get().getId();
        UUID idEspadaFerro = inventario.stream().filter(i -> i.getItem().getId().equals(102L)).findFirst().get().getId();

        // 3. Equipa a Espada de Madeira
        itemService.equiparItem(player.getId(), idEspadaMadeira);

        // Valida: Madeira Equipado? SIM. Ferro Equipado? NÃO.
        assertTrue(playerItemRepository.findById(idEspadaMadeira).get().getEquipped());
        assertFalse(playerItemRepository.findById(idEspadaFerro).get().getEquipped());
        System.out.println("✅ Passo 1: Espada de Madeira equipada.");

        // 4. A Grande Prova: Equipa a Espada de Ferro (Deve desequipar a Madeira)
        itemService.equiparItem(player.getId(), idEspadaFerro);

        // Valida: Madeira Equipado? NÃO. Ferro Equipado? SIM.
        assertFalse(playerItemRepository.findById(idEspadaMadeira).get().getEquipped(), "Espada de madeira deveria ter sido desequipada!");
        assertTrue(playerItemRepository.findById(idEspadaFerro).get().getEquipped(), "Espada de ferro deveria estar equipada!");

        System.out.println("✅ Passo 2: Swap automático funcionou perfeitamente.");
    }

    @Test
    @DisplayName("Erro: Não deve permitir equipar item de outro jogador")
    @Transactional
    void naoDeveEquiparItemDeOutroJogador() {
        // Setup: 2 Jogadores usando Setters
        PlayerEntity ladrao = new PlayerEntity();
        ladrao.setName("Ladrão");
        ladrao.setJobClass("Thief");
        ladrao = playerRepository.save(ladrao);

        PlayerEntity vitima = new PlayerEntity();
        vitima.setName("Vítima");
        vitima.setJobClass("Novice");
        vitima = playerRepository.save(vitima);

        createMockItem(500L, "Adaga", EquipSlot.HAND_R);

        // Dá o item para a Vítima
        itemService.darItemAoJogador(vitima.getId(), 500L, 1);
        UUID idItemDaVitima = playerItemRepository.findByPlayerId(vitima.getId()).get(0).getId();

        // Ladrão tenta equipar o item da Vítima
        Long idLadrao = ladrao.getId(); // Variavel local para usar no lambda
        assertThrows(GameException.class, () -> {
            itemService.equiparItem(idLadrao, idItemDaVitima);
        });
        System.out.println("✅ Segurança validada: Ladrão não conseguiu equipar item alheio.");
    }

    @Test
    @DisplayName("Erro: Não deve permitir equipar item que não é equipamento (Ex: Jellopy)")
    @Transactional
    void naoDeveEquiparItemNaoEquipavel() {
        // Setup Player
        PlayerEntity player = new PlayerEntity();
        player.setName("Noob");
        player.setJobClass("Novice");
        player = playerRepository.save(player);

        // Cria um Jellopy (EquipSlot.NONE)
        createMockItem(909L, "Jellopy", EquipSlot.NONE);

        itemService.darItemAoJogador(player.getId(), 909L, 100);
        UUID idJellopy = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        // Tenta equipar
        Long idPlayer = player.getId();
        assertThrows(GameException.class, () -> {
            itemService.equiparItem(idPlayer, idJellopy);
        });
        System.out.println("✅ Validação de Tipo: Não é possível equipar Jellopy.");
    }

    @Test
    @DisplayName("equiparItem lança exceção quando item não é equipamento (CONSUMABLE)")
    @Transactional
    void equiparItem_tipoInvalido_lancaExcecao() {
        // Cria item CONSUMABLE
        ItemEntity consumable = new ItemEntity();
        consumable.setId(88801L);
        consumable.setName("Red Potion");
        consumable.setType(ItemType.CONSUMABLE);
        itemRepository.save(consumable);

        PlayerEntity player = playerRepository.findById(1L).orElseThrow();
        itemService.darItemAoJogador(player.getId(), 88801L, 1);

        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId())
                .stream()
                .filter(pi -> pi.getItem().getId().equals(88801L))
                .findFirst()
                .orElseThrow()
                .getId();

        assertThrows(GameException.class,
                () -> itemService.equiparItem(player.getId(), playerItemId));
    }

    @Test
    @DisplayName("ItemEntity persiste todos os campos flat corretamente (flattening)")
    @Transactional
    void itemEntity_verificaFlatteningCompleto() {
        ItemEntity entity = new ItemEntity();
        entity.setId(88803L);
        entity.setName("TestSword");
        entity.setAttack(100);
        entity.setDefense(0);
        entity.setSlots(2);
        entity.setWeight(10);
        entity.setPrice(100);
        entity.setType(ItemType.WEAPON);
        entity.setEquipSlot(EquipSlot.HAND_R);
        itemRepository.save(entity);

        ItemEntity salvo = itemRepository.findById(88803L).orElseThrow();
        assertEquals("TestSword", salvo.getName());
        assertEquals(100, salvo.getAttack(), "attack deve ser 100");
        assertEquals(0, salvo.getDefense(), "defense deve ser 0");
        assertEquals(2, salvo.getSlots(), "slots deve ser 2");
        assertEquals(ItemType.WEAPON, salvo.getType(), "type deve ser WEAPON");
        assertEquals(EquipSlot.HAND_R, salvo.getEquipSlot(), "equipSlot deve ser HAND_R");
    }

    @Test
    @DisplayName("usarItem com CONSUMABLE (script itemheal) cura HP do player")
    @Transactional
    void usarItem_consumable_script_healsHP() {
        // Cria item consumível com script
        ItemEntity potion = new ItemEntity();
        potion.setId(88820L);
        potion.setName("Red Potion");
        potion.setType(ItemType.CONSUMABLE);
        potion.setScript("itemheal 50, 0");
        itemRepository.save(potion);

        // Cria player com HP parcial
        PlayerEntity player = new PlayerEntity();
        player.setName("TestHeal");
        player.setHpCurrent(30);
        player.setHpMax(100);
        player.setSpCurrent(20);
        player.setSpMax(40);
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88820L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        String result = itemService.usarItem(playerItemId);

        assertTrue(result.contains("50 de HP"), "Deve reportar 50 HP curado");
        PlayerEntity updated = playerRepository.findById(player.getId()).orElseThrow();
        assertEquals(80, updated.getHpCurrent(), "HP deve ser 80 após cura");
    }

    @Test
    @DisplayName("usarItem com CONSUMABLE (script itemheal) e HP cheio retorna mensagem de cheio")
    @Transactional
    void usarItem_consumable_hpFull_retornaMensagemCheio() {
        ItemEntity potion = new ItemEntity();
        potion.setId(88821L);
        potion.setName("HP Potion Full");
        potion.setType(ItemType.CONSUMABLE);
        potion.setScript("itemheal 50, 0");
        itemRepository.save(potion);

        PlayerEntity player = new PlayerEntity();
        player.setName("TestFull");
        player.setHpCurrent(100);
        player.setHpMax(100);
        player.setSpCurrent(20);
        player.setSpMax(40);
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88821L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        String result = itemService.usarItem(playerItemId);

        assertEquals("Seu HP já está cheio!", result);
    }

    @Test
    @DisplayName("usarItem com CONSUMABLE (script itemheal) e SP cheio retorna mensagem de cheio")
    @Transactional
    void usarItem_consumable_spFull_retornaMensagemCheio() {
        ItemEntity spPotion = new ItemEntity();
        spPotion.setId(88822L);
        spPotion.setName("SP Potion Full");
        spPotion.setType(ItemType.CONSUMABLE);
        spPotion.setScript("itemheal 0, 20");
        itemRepository.save(spPotion);

        PlayerEntity player = new PlayerEntity();
        player.setName("TestSPFull");
        player.setHpCurrent(50);
        player.setHpMax(100);
        player.setSpCurrent(40);
        player.setSpMax(40);
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88822L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        String result = itemService.usarItem(playerItemId);

        assertEquals("Seu SP já está cheio!", result);
    }

    @Test
    @DisplayName("usarItem com CONSUMABLE (script itemheal) cura HP e SP quando ambos parciais")
    @Transactional
    void usarItem_consumable_healsHpAndSp() {
        ItemEntity combo = new ItemEntity();
        combo.setId(88823L);
        combo.setName("Combo Potion");
        combo.setType(ItemType.CONSUMABLE);
        combo.setScript("itemheal 30, 10");
        itemRepository.save(combo);

        PlayerEntity player = new PlayerEntity();
        player.setName("TestCombo");
        player.setHpCurrent(50);
        player.setHpMax(100);
        player.setSpCurrent(20);
        player.setSpMax(40);
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88823L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        String result = itemService.usarItem(playerItemId);

        assertTrue(result.contains("de HP e"), "Deve reportar cura de HP e SP juntos");
    }

    @Test
    @DisplayName("usarItem com CONSUMABLE (script itemheal) cura apenas SP")
    @Transactional
    void usarItem_consumable_healsSpOnly() {
        ItemEntity spPotion = new ItemEntity();
        spPotion.setId(88824L);
        spPotion.setName("SP Potion");
        spPotion.setType(ItemType.CONSUMABLE);
        spPotion.setScript("itemheal 0, 20");
        itemRepository.save(spPotion);

        PlayerEntity player = new PlayerEntity();
        player.setName("TestSP");
        player.setHpCurrent(100);
        player.setHpMax(100);
        player.setSpCurrent(10);
        player.setSpMax(40);
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88824L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        String result = itemService.usarItem(playerItemId);

        assertTrue(result.contains("de SP"), "Deve reportar cura de SP");
    }

    @Test
    @DisplayName("usarItem com CONSUMABLE e HP+SP ambos cheios retorna mensagem de ambos cheios")
    @Transactional
    void usarItem_consumable_ambosCheioss_retornaMensagem() {
        ItemEntity combo = new ItemEntity();
        combo.setId(88825L);
        combo.setName("Full Potion");
        combo.setType(ItemType.CONSUMABLE);
        combo.setScript("itemheal 30, 10");
        itemRepository.save(combo);

        PlayerEntity player = new PlayerEntity();
        player.setName("TestBothFull");
        player.setHpCurrent(100);
        player.setHpMax(100);
        player.setSpCurrent(40);
        player.setSpMax(40);
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88825L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        String result = itemService.usarItem(playerItemId);

        assertEquals("HP e SP já estão cheios!", result);
    }

    @Test
    @DisplayName("usarItem com CONSUMABLE sem script e sem efeito retorna sem efeito")
    @Transactional
    void usarItem_consumable_semEfeito_retornaMensagem() {
        ItemEntity noEffect = new ItemEntity();
        noEffect.setId(88826L);
        noEffect.setName("Useless Item");
        noEffect.setType(ItemType.CONSUMABLE);
        // sem script, sem efeito, sem bonusSp
        itemRepository.save(noEffect);

        PlayerEntity player = new PlayerEntity();
        player.setName("TestNoEffect");
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88826L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        String result = itemService.usarItem(playerItemId);

        assertEquals("Este item não tem efeito.", result);
    }

    @Test
    @DisplayName("usarItem com CONSUMABLE legacy (efeito HP) cura via campo efeito")
    @Transactional
    void usarItem_consumable_legacyEfeito_healsHP() {
        ItemEntity legacyPotion = new ItemEntity();
        legacyPotion.setId(88827L);
        legacyPotion.setName("Legacy HP Potion");
        legacyPotion.setType(ItemType.CONSUMABLE);
        legacyPotion.setEfeito(40); // efeito = HP heal
        // sem script → fallback legado
        itemRepository.save(legacyPotion);

        PlayerEntity player = new PlayerEntity();
        player.setName("TestLegacy");
        player.setHpCurrent(20);
        player.setHpMax(100);
        player.setSpCurrent(20);
        player.setSpMax(40);
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88827L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        String result = itemService.usarItem(playerItemId);

        assertTrue(result.contains("40 de HP"), "Deve curar 40 HP via campo efeito");
    }

    @Test
    @DisplayName("usarItem desequipa item quando já equipado (unequip path)")
    @Transactional
    void usarItem_equippedWeapon_unequips() {
        createMockItem(88828L, "TestSword", EquipSlot.HAND_R);

        PlayerEntity player = new PlayerEntity();
        player.setName("TestUnequip");
        player = playerRepository.save(player);

        itemService.darItemAoJogador(player.getId(), 88828L, 1);
        UUID playerItemId = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        // Equipa primeiro
        itemService.equiparItem(player.getId(), playerItemId);
        assertTrue(playerItemRepository.findById(playerItemId).orElseThrow().getEquipped());

        // Usa novamente → deve desequipar
        String result = itemService.usarItem(playerItemId);

        assertTrue(result.contains("desequipado"), "Deve retornar mensagem de desequipar");
        assertFalse(playerItemRepository.findById(playerItemId).orElseThrow().getEquipped());
    }

    // --- Helper para criar itens no banco rapidamente ---
    private void createMockItem(Long id, String name, EquipSlot slot) {
        ItemEntity item = new ItemEntity();
        item.setId(id);
        item.setName(name);
        // Define o tipo baseado no slot (simplificação para teste)
        item.setType(slot == EquipSlot.NONE ? ItemType.ETC : ItemType.WEAPON);
        item.setEquipSlot(slot);
        item.setWeight(10);
        item.setPrice(10);
        // Campos obrigatórios para evitar NullPointerException se houver validação
        item.setAttack(0);
        item.setDefense(0);

        itemRepository.save(item);
    }
}