package com.ragnarok.application.service;

import com.ragnarok.domain.model.EquipSlot;
import com.ragnarok.domain.model.Item;
import com.ragnarok.domain.model.ItemType;
import com.ragnarok.infrastructure.persistence.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@TestPropertySource(properties = {
        "DB_USER=postgres",
        "DB_PASSWORD=postgre"
})
class ItemServiceIntegrationTest {

    @Autowired private ItemService itemService;
    @Autowired private PlayerRepository playerRepository;
    @Autowired private ItemRepository itemRepository;
    @Autowired private PlayerItemRepository playerItemRepository;

    @Test
    @DisplayName("Deve criar um item de teste (Definição) corretamente")
    @Transactional
    void deveCriarItemDeTeste() {
        // Executa
        Item itemDomain = itemService.criarItemDeTeste(9999L, "Espada Lendária", 500);

        // Valida no Banco
        ItemEntity salvo = itemRepository.findById(9999L).orElseThrow();
        assertEquals("Espada Lendária", salvo.getName());
        assertEquals(500, salvo.getAttack());
        System.out.println("✅ Item criado e validado.");
    }

    @Test
    @DisplayName("Deve realizar o ciclo completo: Dar item, Equipar e Trocar (Swap)")
    @Transactional
    void deveGerenciarEquipamentoETroca() {
        // 1. Setup: Cria Jogador usando Setters (Mais seguro)
        PlayerEntity player = new PlayerEntity();
        player.setName("Hero");
        player.setJobClass("Knight");
        // O ID é gerado automaticamente ao salvar, ou null se não for AutoGenerated.
        // Se sua entidade usa GenerationType.IDENTITY, não sete o ID.

        player = playerRepository.save(player);

        // Cria Definições no banco
        createMockItem(101L, "Espada de Madeira", EquipSlot.HAND_R);
        createMockItem(102L, "Espada de Ferro", EquipSlot.HAND_R);

        // 2. Dar os itens ao jogador
        itemService.darItemAoJogador(player.getId(), 101L, 1);
        itemService.darItemAoJogador(player.getId(), 102L, 1);

        // Recupera os IDs das instâncias físicas (UUIDs)
        List<PlayerItemEntity> inventario = playerItemRepository.findByPlayerId(player.getId());
        UUID idEspadaMadeira = inventario.stream().filter(i -> i.getItem().getId().equals(101L)).findFirst().get().getId();
        UUID idEspadaFerro = inventario.stream().filter(i -> i.getItem().getId().equals(102L)).findFirst().get().getId();

        // 3. Equipa a Espada de Madeira
        itemService.equiparItem(player.getId(), idEspadaMadeira);

        // Valida: Madeira Equipado? SIM. Ferro Equipado? NÃO.
        assertTrue(playerItemRepository.findById(idEspadaMadeira).get().getEquipped());
        assertFalse(playerItemRepository.findById(idEspadaFerro).get().getEquipped());
        System.out.println("✅ Passo 1: Espada de Madeira equipada.");

        // 4. A Grande Prova: Equipa a Espada de Ferro (Deve desequipar a Madeira)
        itemService.equiparItem(player.getId(), idEspadaFerro);

        // Valida: Madeira Equipado? NÃO. Ferro Equipado? SIM.
        assertFalse(playerItemRepository.findById(idEspadaMadeira).get().getEquipped(), "Espada de madeira deveria ter sido desequipada!");
        assertTrue(playerItemRepository.findById(idEspadaFerro).get().getEquipped(), "Espada de ferro deveria estar equipada!");

        System.out.println("✅ Passo 2: Swap automático funcionou perfeitamente.");
    }

    @Test
    @DisplayName("Erro: Não deve permitir equipar item de outro jogador")
    @Transactional
    void naoDeveEquiparItemDeOutroJogador() {
        // Setup: 2 Jogadores usando Setters
        PlayerEntity ladrao = new PlayerEntity();
        ladrao.setName("Ladrão");
        ladrao.setJobClass("Thief");
        ladrao = playerRepository.save(ladrao);

        PlayerEntity vitima = new PlayerEntity();
        vitima.setName("Vítima");
        vitima.setJobClass("Novice");
        vitima = playerRepository.save(vitima);

        createMockItem(500L, "Adaga", EquipSlot.HAND_R);

        // Dá o item para a Vítima
        itemService.darItemAoJogador(vitima.getId(), 500L, 1);
        UUID idItemDaVitima = playerItemRepository.findByPlayerId(vitima.getId()).get(0).getId();

        // Ladrão tenta equipar o item da Vítima
        Long idLadrao = ladrao.getId(); // Variavel local para usar no lambda
        assertThrows(IllegalStateException.class, () -> {
            itemService.equiparItem(idLadrao, idItemDaVitima);
        });
        System.out.println("✅ Segurança validada: Ladrão não conseguiu equipar item alheio.");
    }

    @Test
    @DisplayName("Erro: Não deve permitir equipar item que não é equipamento (Ex: Jellopy)")
    @Transactional
    void naoDeveEquiparItemNaoEquipavel() {
        // Setup Player
        PlayerEntity player = new PlayerEntity();
        player.setName("Noob");
        player.setJobClass("Novice");
        player = playerRepository.save(player);

        // Cria um Jellopy (EquipSlot.NONE)
        createMockItem(909L, "Jellopy", EquipSlot.NONE);

        itemService.darItemAoJogador(player.getId(), 909L, 100);
        UUID idJellopy = playerItemRepository.findByPlayerId(player.getId()).get(0).getId();

        // Tenta equipar
        Long idPlayer = player.getId();
        assertThrows(IllegalArgumentException.class, () -> {
            itemService.equiparItem(idPlayer, idJellopy);
        });
        System.out.println("✅ Validação de Tipo: Não é possível equipar Jellopy.");
    }

    // --- Helper para criar itens no banco rapidamente ---
    private void createMockItem(Long id, String name, EquipSlot slot) {
        ItemEntity item = new ItemEntity();
        item.setId(id);
        item.setName(name);
        // Define o tipo baseado no slot (simplificação para teste)
        item.setType(slot == EquipSlot.NONE ? ItemType.ETC : ItemType.WEAPON);
        item.setEquipSlot(slot);
        item.setWeight(10);
        item.setPrice(10);
        // Campos obrigatórios para evitar NullPointerException se houver validação
        item.setAttack(0);
        item.setDefense(0);

        itemRepository.save(item);
    }
}