-- Gerado automaticamente pelo skill_parser.py

CREATE TABLE IF NOT EXISTS skills (
    id          BIGINT PRIMARY KEY,
    aegis_name  VARCHAR(100) NOT NULL,
    name        VARCHAR(150),
    type        VARCHAR(100),
    script      TEXT
);

ALTER TABLE skills ADD COLUMN IF NOT EXISTS script TEXT;

INSERT INTO skills (id, aegis_name, name, type, script) VALUES
  (1, 'NV_BASIC', 'Basic Skill', '', NULL),
  (2, 'SM_SWORD', 'Sword Mastery', '', NULL),
  (3, 'SM_TWOHAND', 'Two-Handed Sword Mastery', '', NULL),
  (4, 'SM_RECOVERY', 'Increase HP Recovery', '', NULL),
  (5, 'SM_BASH', 'Bash', '', NULL),
  (6, 'SM_PROVOKE', 'Provoke', '', NULL),
  (7, 'SM_MAGNUM', 'Magnum Break', '', NULL),
  (8, 'SM_ENDURE', 'Endure', '', NULL),
  (9, 'MG_SRECOVERY', 'Increase SP Recovery', '', NULL),
  (10, 'MG_SIGHT', 'Sight', '', NULL),
  (11, 'MG_NAPALMBEAT', 'Napalm Beat', '', NULL),
  (12, 'MG_SAFETYWALL', 'Safety Wall', '', NULL),
  (13, 'MG_SOULSTRIKE', 'Soul Strike', '', NULL),
  (14, 'MG_COLDBOLT', 'Cold Bolt', '', NULL),
  (15, 'MG_FROSTDIVER', 'Frost Diver', '', NULL),
  (16, 'MG_STONECURSE', 'Stone Curse', '', NULL),
  (17, 'MG_FIREBALL', 'Fire Ball', '', NULL),
  (18, 'MG_FIREWALL', 'Fire Wall', '', NULL),
  (19, 'MG_FIREBOLT', 'Fire Bolt', '', NULL),
  (20, 'MG_LIGHTNINGBOLT', 'Lightning Bolt', '', NULL),
  (21, 'MG_THUNDERSTORM', 'Thunderstorm', '', NULL),
  (22, 'AL_DP', 'Divine Protection', '', NULL),
  (23, 'AL_DEMONBANE', 'Demon Bane', '', NULL),
  (24, 'AL_RUWACH', 'Ruwach', '', NULL),
  (25, 'AL_PNEUMA', 'Pneuma', '', NULL),
  (26, 'AL_TELEPORT', 'Teleport', '', NULL),
  (27, 'AL_WARP', 'Warp Portal', '', NULL),
  (28, 'AL_HEAL', 'Heal', '', NULL),
  (29, 'AL_INCAGI', 'Increase AGI', '', NULL),
  (30, 'AL_DECAGI', 'Decrease AGI', '', NULL),
  (31, 'AL_HOLYWATER', 'Aqua Benedicta', '', NULL),
  (32, 'AL_CRUCIS', 'Signum Crucis', '', NULL),
  (33, 'AL_ANGELUS', 'Angelus', '', NULL),
  (34, 'AL_BLESSING', 'Blessing', '', NULL),
  (35, 'AL_CURE', 'Cure', '', NULL),
  (36, 'MC_INCCARRY', 'Enlarge Weight Limit', '', NULL),
  (37, 'MC_DISCOUNT', 'Discount', '', NULL),
  (38, 'MC_OVERCHARGE', 'Overcharge', '', NULL),
  (39, 'MC_PUSHCART', 'Pushcart', '', NULL),
  (40, 'MC_IDENTIFY', 'Item Appraisal', '', NULL),
  (41, 'MC_VENDING', 'Vending', '', NULL),
  (42, 'MC_MAMMONITE', 'Mammonite', '', NULL),
  (43, 'AC_OWL', 'Owl''s Eye', '', NULL),
  (44, 'AC_VULTURE', 'Vulture''s Eye', '', NULL),
  (45, 'AC_CONCENTRATION', 'Improve Concentration', '', NULL),
  (46, 'AC_DOUBLE', 'Double Strafe', '', NULL),
  (47, 'AC_SHOWER', 'Arrow Shower', '', NULL),
  (48, 'TF_DOUBLE', 'Double Attack', '', NULL),
  (49, 'TF_MISS', 'Improve Dodge', '', NULL),
  (50, 'TF_STEAL', 'Steal', '', NULL),
  (51, 'TF_HIDING', 'Hiding', '', NULL),
  (52, 'TF_POISON', 'Envenom', '', NULL),
  (53, 'TF_DETOXIFY', 'Detoxify', '', NULL),
  (54, 'ALL_RESURRECTION', 'Resurrection', '', NULL),
  (55, 'KN_SPEARMASTERY', 'Spear Mastery', '', NULL),
  (56, 'KN_PIERCE', 'Pierce', '', NULL),
  (57, 'KN_BRANDISHSPEAR', 'Brandish Spear', '', NULL),
  (58, 'KN_SPEARSTAB', 'Spear Stab', '', NULL),
  (59, 'KN_SPEARBOOMERANG', 'Spear Boomerang', '', NULL),
  (60, 'KN_TWOHANDQUICKEN', 'Twohand Quicken', '', NULL),
  (61, 'KN_AUTOCOUNTER', 'Counter Attack', '', NULL),
  (62, 'KN_BOWLINGBASH', 'Bowling Bash', '', NULL),
  (63, 'KN_RIDING', 'Peco Peco Riding', '', NULL),
  (64, 'KN_CAVALIERMASTERY', 'Cavalier Mastery', '', NULL),
  (65, 'PR_MACEMASTERY', 'Mace Mastery', '', NULL),
  (66, 'PR_IMPOSITIO', 'Impositio Manus', '', NULL),
  (67, 'PR_SUFFRAGIUM', 'Suffragium', '', NULL),
  (68, 'PR_ASPERSIO', 'Aspersio', '', NULL),
  (69, 'PR_BENEDICTIO', 'B.S. Sacramenti', '', NULL),
  (70, 'PR_SANCTUARY', 'Sanctuary', '', NULL),
  (71, 'PR_SLOWPOISON', 'Slow Poison', '', NULL),
  (72, 'PR_STRECOVERY', 'Status Recovery', '', NULL),
  (73, 'PR_KYRIE', 'Kyrie Eleison', '', NULL),
  (74, 'PR_MAGNIFICAT', 'Magnificat', '', NULL),
  (75, 'PR_GLORIA', 'Gloria', '', NULL),
  (76, 'PR_LEXDIVINA', 'Lex Divina', '', NULL),
  (77, 'PR_TURNUNDEAD', 'Turn Undead', '', NULL),
  (78, 'PR_LEXAETERNA', 'Lex Aeterna', '', NULL),
  (79, 'PR_MAGNUS', 'Magnus Exorcismus', '', NULL),
  (80, 'WZ_FIREPILLAR', 'Fire Pillar', '', NULL),
  (81, 'WZ_SIGHTRASHER', 'Sightrasher', '', NULL),
  (83, 'WZ_METEOR', 'Meteor Storm', '', NULL),
  (84, 'WZ_JUPITEL', 'Jupitel Thunder', '', NULL),
  (85, 'WZ_VERMILION', 'Lord of Vermilion', '', NULL),
  (86, 'WZ_WATERBALL', 'Water Ball', '', NULL),
  (87, 'WZ_ICEWALL', 'Ice Wall', '', NULL),
  (88, 'WZ_FROSTNOVA', 'Frost Nova', '', NULL),
  (89, 'WZ_STORMGUST', 'Storm Gust', '', NULL),
  (90, 'WZ_EARTHSPIKE', 'Earth Spike', '', NULL),
  (91, 'WZ_HEAVENDRIVE', 'Heaven''s Drive', '', NULL),
  (92, 'WZ_QUAGMIRE', 'Quagmire', '', NULL),
  (93, 'WZ_ESTIMATION', 'Sense', '', NULL),
  (94, 'BS_IRON', 'Iron Tempering', '', NULL),
  (95, 'BS_STEEL', 'Steel Tempering', '', NULL),
  (96, 'BS_ENCHANTEDSTONE', 'Enchanted Stone Craft', '', NULL),
  (97, 'BS_ORIDEOCON', 'Oridecon Research', '', NULL),
  (98, 'BS_DAGGER', 'Smith Dagger', '', NULL),
  (99, 'BS_SWORD', 'Smith Sword', '', NULL),
  (100, 'BS_TWOHANDSWORD', 'Smith Two-handed Sword', '', NULL),
  (101, 'BS_AXE', 'Smith Axe', '', NULL),
  (102, 'BS_MACE', 'Smith Mace', '', NULL),
  (103, 'BS_KNUCKLE', 'Smith Knucklebrace', '', NULL),
  (104, 'BS_SPEAR', 'Smith Spear', '', NULL),
  (105, 'BS_HILTBINDING', 'Hilt Binding', '', NULL),
  (106, 'BS_FINDINGORE', 'Ore Discovery', '', NULL),
  (107, 'BS_WEAPONRESEARCH', 'Weaponry Research', '', NULL),
  (108, 'BS_REPAIRWEAPON', 'Weapon Repair', '', NULL),
  (109, 'BS_SKINTEMPER', 'Skin Tempering', '', NULL),
  (110, 'BS_HAMMERFALL', 'Hammer Fall', '', NULL),
  (111, 'BS_ADRENALINE', 'Adrenaline Rush', '', NULL),
  (112, 'BS_WEAPONPERFECT', 'Weapon Perfection', '', NULL),
  (113, 'BS_OVERTHRUST', 'Power-Thrust', '', NULL),
  (114, 'BS_MAXIMIZE', 'Maximize Power', '', NULL),
  (115, 'HT_SKIDTRAP', 'Skid Trap', '', NULL),
  (116, 'HT_LANDMINE', 'Land Mine', '', NULL),
  (117, 'HT_ANKLESNARE', 'Ankle Snare', '', NULL),
  (118, 'HT_SHOCKWAVE', 'Shockwave Trap', '', NULL),
  (119, 'HT_SANDMAN', 'Sandman', '', NULL),
  (120, 'HT_FLASHER', 'Flasher', '', NULL),
  (121, 'HT_FREEZINGTRAP', 'Freezing Trap', '', NULL),
  (122, 'HT_BLASTMINE', 'Blast Mine', '', NULL),
  (123, 'HT_CLAYMORETRAP', 'Claymore Trap', '', NULL),
  (124, 'HT_REMOVETRAP', 'Remove Trap', '', NULL),
  (125, 'HT_TALKIEBOX', 'Talkie Box', '', NULL),
  (126, 'HT_BEASTBANE', 'Beast Bane', '', NULL),
  (127, 'HT_FALCON', 'Falconry Mastery', '', NULL),
  (128, 'HT_STEELCROW', 'Steel Crow', '', NULL),
  (129, 'HT_BLITZBEAT', 'Blitz Beat', '', NULL),
  (130, 'HT_DETECTING', 'Detect', '', NULL),
  (131, 'HT_SPRINGTRAP', 'Spring Trap', '', NULL),
  (132, 'AS_RIGHT', 'Righthand Mastery', '', NULL),
  (133, 'AS_LEFT', 'Lefthand Mastery', '', NULL),
  (134, 'AS_KATAR', 'Katar Mastery', '', NULL),
  (135, 'AS_CLOAKING', 'Cloaking', '', NULL),
  (136, 'AS_SONICBLOW', 'Sonic Blow', '', NULL),
  (137, 'AS_GRIMTOOTH', 'Grimtooth', '', NULL),
  (138, 'AS_ENCHANTPOISON', 'Enchant Poison', '', NULL),
  (139, 'AS_POISONREACT', 'Poison React', '', NULL),
  (140, 'AS_VENOMDUST', 'Venom Dust', '', NULL),
  (141, 'AS_SPLASHER', 'Venom Splasher', '', NULL),
  (142, 'NV_FIRSTAID', 'First Aid', '', NULL),
  (143, 'NV_TRICKDEAD', 'Play Dead', '', NULL),
  (144, 'SM_MOVINGRECOVERY', 'Moving HP-Recovery', '', NULL),
  (145, 'SM_FATALBLOW', 'Fatal Blow', '', NULL),
  (146, 'SM_AUTOBERSERK', 'Auto Berserk', '', NULL),
  (147, 'AC_MAKINGARROW', 'Arrow Crafting', '', NULL),
  (148, 'AC_CHARGEARROW', 'Arrow Repel', '', NULL),
  (149, 'TF_SPRINKLESAND', 'Sand Attack', '', NULL),
  (150, 'TF_BACKSLIDING', 'Back Slide', '', NULL),
  (151, 'TF_PICKSTONE', 'Find Stone', '', NULL),
  (152, 'TF_THROWSTONE', 'Stone Fling', '', NULL),
  (153, 'MC_CARTREVOLUTION', 'Cart Revolution', '', NULL),
  (154, 'MC_CHANGECART', 'Change Cart', '', NULL),
  (155, 'MC_LOUD', 'Crazy Uproar', '', NULL),
  (156, 'AL_HOLYLIGHT', 'Holy Light', '', NULL),
  (157, 'MG_ENERGYCOAT', 'Energy Coat', '', NULL),
  (158, 'NPC_PIERCINGATT', 'Piercing Attack', '', NULL),
  (159, 'NPC_MENTALBREAKER', 'Spirit Destruction', '', NULL),
  (160, 'NPC_RANGEATTACK', 'Stand off attack', '', NULL),
  (161, 'NPC_ATTRICHANGE', 'Attribute Change', '', NULL),
  (162, 'NPC_CHANGEWATER', 'Water Attribute Change', '', NULL),
  (163, 'NPC_CHANGEGROUND', 'Earth Attribute Change', '', NULL),
  (164, 'NPC_CHANGEFIRE', 'Fire Attribute Change', '', NULL),
  (165, 'NPC_CHANGEWIND', 'Wind Attribute Change', '', NULL),
  (166, 'NPC_CHANGEPOISON', 'Poison Attribute Change', '', NULL),
  (167, 'NPC_CHANGEHOLY', 'Holy Attribute Change', '', NULL),
  (168, 'NPC_CHANGEDARKNESS', 'Shadow Attribute Change', '', NULL),
  (169, 'NPC_CHANGETELEKINESIS', 'Ghost Attribute Change', '', NULL),
  (170, 'NPC_CRITICALSLASH', 'Defense disregard attack', '', NULL),
  (171, 'NPC_COMBOATTACK', 'Multi-stage Attack', '', NULL),
  (172, 'NPC_GUIDEDATTACK', 'Guided Attack', '', NULL),
  (173, 'NPC_SELFDESTRUCTION', 'Suicide bombing', '', NULL),
  (174, 'NPC_SPLASHATTACK', 'Splash attack', '', NULL),
  (175, 'NPC_SUICIDE', 'Suicide', '', NULL),
  (176, 'NPC_POISON', 'Poison Attack', '', NULL),
  (177, 'NPC_BLINDATTACK', 'Blind Attack', '', NULL),
  (178, 'NPC_SILENCEATTACK', 'Silence Attack', '', NULL),
  (179, 'NPC_STUNATTACK', 'Stun Attack', '', NULL),
  (180, 'NPC_PETRIFYATTACK', 'Petrify Attack', '', NULL),
  (181, 'NPC_CURSEATTACK', 'Curse Attack', '', NULL),
  (182, 'NPC_SLEEPATTACK', 'Sleep attack', '', NULL),
  (183, 'NPC_RANDOMATTACK', 'Random Attack', '', NULL),
  (184, 'NPC_WATERATTACK', 'Water Attribute Attack', '', NULL),
  (185, 'NPC_GROUNDATTACK', 'Earth Attribute Attack', '', NULL),
  (186, 'NPC_FIREATTACK', 'Fire Attribute Attack', '', NULL),
  (187, 'NPC_WINDATTACK', 'Wind Attribute Attack', '', NULL),
  (188, 'NPC_POISONATTACK', 'Poison Attribute Attack', '', NULL),
  (189, 'NPC_HOLYATTACK', 'Holy Attribute Attack', '', NULL),
  (190, 'NPC_DARKNESSATTACK', 'Shadow Attribute Attack', '', NULL),
  (191, 'NPC_TELEKINESISATTACK', 'Ghost Attribute Attack', '', NULL),
  (192, 'NPC_MAGICALATTACK', 'Demon Shock Attack', '', NULL),
  (193, 'NPC_METAMORPHOSIS', 'Metamorphosis', '', NULL),
  (194, 'NPC_PROVOCATION', 'Provocation', '', NULL),
  (195, 'NPC_SMOKING', 'Smoking', '', NULL),
  (196, 'NPC_SUMMONSLAVE', 'Follower Summons', '', NULL),
  (197, 'NPC_EMOTION', 'Emotion', '', NULL),
  (198, 'NPC_TRANSFORMATION', 'Transformation', '', NULL),
  (199, 'NPC_BLOODDRAIN', 'Sucking Blood', '', NULL),
  (200, 'NPC_ENERGYDRAIN', 'Energy Drain', '', NULL),
  (201, 'NPC_KEEPING', 'Keeping', '', NULL),
  (202, 'NPC_DARKBREATH', 'Dark Breath', '', NULL),
  (203, 'NPC_DARKBLESSING', 'Dark Blessing', '', NULL),
  (204, 'NPC_BARRIER', 'Barrier', '', NULL),
  (205, 'NPC_DEFENDER', 'Defender', '', NULL),
  (206, 'NPC_LICK', 'Lick', '', NULL),
  (207, 'NPC_HALLUCINATION', 'Hallucination', '', NULL),
  (208, 'NPC_REBIRTH', 'Rebirth', '', NULL),
  (209, 'NPC_SUMMONMONSTER', 'Monster Summons', '', NULL),
  (210, 'RG_SNATCHER', 'Gank', '', NULL),
  (211, 'RG_STEALCOIN', 'Mug', '', NULL),
  (212, 'RG_BACKSTAP', 'Back Stab', '', NULL),
  (213, 'RG_TUNNELDRIVE', 'Stalk', '', NULL),
  (214, 'RG_RAID', 'Sightless Mind', '', NULL),
  (215, 'RG_STRIPWEAPON', 'Divest Weapon', '', NULL),
  (216, 'RG_STRIPSHIELD', 'Divest Shield', '', NULL),
  (217, 'RG_STRIPARMOR', 'Divest Armor', '', NULL),
  (218, 'RG_STRIPHELM', 'Divest Helm', '', NULL),
  (219, 'RG_INTIMIDATE', 'Snatch', '', NULL),
  (220, 'RG_GRAFFITI', 'Scribble', '', NULL),
  (221, 'RG_FLAGGRAFFITI', 'Piece', '', NULL),
  (222, 'RG_CLEANER', 'Remover', '', NULL),
  (223, 'RG_GANGSTER', 'Slyness', '', NULL),
  (224, 'RG_COMPULSION', 'Haggle', '', NULL),
  (225, 'RG_PLAGIARISM', 'Intimidate', '', NULL),
  (226, 'AM_AXEMASTERY', 'Axe Mastery', '', NULL),
  (227, 'AM_LEARNINGPOTION', 'Potion Research', '', NULL),
  (228, 'AM_PHARMACY', 'Prepare Potion', '', NULL),
  (229, 'AM_DEMONSTRATION', 'Bomb', '', NULL),
  (230, 'AM_ACIDTERROR', 'Acid Terror', '', NULL),
  (231, 'AM_POTIONPITCHER', 'Aid Potion', '', NULL),
  (232, 'AM_CANNIBALIZE', 'Summon Flora', '', NULL),
  (233, 'AM_SPHEREMINE', 'Summon Marine Sphere', '', NULL),
  (234, 'AM_CP_WEAPON', 'Alchemical Weapon', '', NULL),
  (235, 'AM_CP_SHIELD', 'Synthesized Shield', '', NULL),
  (236, 'AM_CP_ARMOR', 'Synthetic Armor', '', NULL),
  (237, 'AM_CP_HELM', 'Biochemical Helm', '', NULL),
  (238, 'AM_BIOETHICS', 'Bioethics', '', NULL),
  (243, 'AM_CALLHOMUN', 'Call Homunculus', '', NULL),
  (244, 'AM_REST', 'Vaporize', '', NULL),
  (247, 'AM_RESURRECTHOMUN', 'Homunculus Resurrection', '', NULL),
  (248, 'CR_TRUST', 'Faith', '', NULL),
  (249, 'CR_AUTOGUARD', 'Guard', '', NULL),
  (250, 'CR_SHIELDCHARGE', 'Smite', '', NULL),
  (251, 'CR_SHIELDBOOMERANG', 'Shield Boomerang', '', NULL),
  (252, 'CR_REFLECTSHIELD', 'Shield Reflect', '', NULL),
  (253, 'CR_HOLYCROSS', 'Holy Cross', '', NULL),
  (254, 'CR_GRANDCROSS', 'Grand Cross', '', NULL),
  (255, 'CR_DEVOTION', 'Sacrifice', '', NULL),
  (256, 'CR_PROVIDENCE', 'Resistant Souls', '', NULL),
  (257, 'CR_DEFENDER', 'Defending Aura', '', NULL),
  (258, 'CR_SPEARQUICKEN', 'Spear Quicken', '', NULL),
  (259, 'MO_IRONHAND', 'Iron Fists', '', NULL),
  (260, 'MO_SPIRITSRECOVERY', 'Spiritual Cadence', '', NULL),
  (261, 'MO_CALLSPIRITS', 'Summon Spirit Sphere', '', NULL),
  (262, 'MO_ABSORBSPIRITS', 'Absorb Spirit Sphere', '', NULL),
  (263, 'MO_TRIPLEATTACK', 'Raging Trifecta Blow', '', NULL),
  (264, 'MO_BODYRELOCATION', 'Snap', '', NULL),
  (265, 'MO_DODGE', 'Dodge', '', NULL),
  (266, 'MO_INVESTIGATE', 'Occult Impaction', '', NULL),
  (267, 'MO_FINGEROFFENSIVE', 'Throw Spirit Sphere', '', NULL),
  (268, 'MO_STEELBODY', 'Mental Strength', '', NULL),
  (269, 'MO_BLADESTOP', 'Root', '', NULL),
  (270, 'MO_EXPLOSIONSPIRITS', 'Fury', '', NULL),
  (271, 'MO_EXTREMITYFIST', 'Asura Strike', '', NULL),
  (272, 'MO_CHAINCOMBO', 'Raging Quadruple Blow', '', NULL),
  (273, 'MO_COMBOFINISH', 'Raging Thrust', '', NULL),
  (274, 'SA_ADVANCEDBOOK', 'Study', '', NULL),
  (275, 'SA_CASTCANCEL', 'Cast Cancel', '', NULL),
  (276, 'SA_MAGICROD', 'Magic Rod', '', NULL),
  (277, 'SA_SPELLBREAKER', 'Spell Breaker', '', NULL),
  (278, 'SA_FREECAST', 'Free Cast', '', NULL),
  (279, 'SA_AUTOSPELL', 'Hindsight', '', NULL),
  (280, 'SA_FLAMELAUNCHER', 'Endow Blaze', '', NULL),
  (281, 'SA_FROSTWEAPON', 'Endow Tsunami', '', NULL),
  (282, 'SA_LIGHTNINGLOADER', 'Endow Tornado', '', NULL),
  (283, 'SA_SEISMICWEAPON', 'Endow Quake', '', NULL),
  (284, 'SA_DRAGONOLOGY', 'Dragonology', '', NULL),
  (285, 'SA_VOLCANO', 'Volcano', '', NULL),
  (286, 'SA_DELUGE', 'Deluge', '', NULL),
  (287, 'SA_VIOLENTGALE', 'Whirlwind', '', NULL),
  (288, 'SA_LANDPROTECTOR', 'Magnetic Earth', '', NULL),
  (289, 'SA_DISPELL', 'Dispell', '', NULL),
  (290, 'SA_ABRACADABRA', 'Hocus-pocus', '', NULL),
  (291, 'SA_MONOCELL', 'Monocell', '', NULL),
  (292, 'SA_CLASSCHANGE', 'Class Change', '', NULL),
  (293, 'SA_SUMMONMONSTER', 'Monster Chant', '', NULL),
  (294, 'SA_REVERSEORCISH', 'Grampus Morph', '', NULL),
  (295, 'SA_DEATH', 'Grim Reaper', '', NULL),
  (296, 'SA_FORTUNE', 'Gold Digger', '', NULL),
  (297, 'SA_TAMINGMONSTER', 'Beastly Hypnosis', '', NULL),
  (298, 'SA_QUESTION', 'Questioning', '', NULL),
  (299, 'SA_GRAVITY', 'Gravity', '', NULL),
  (300, 'SA_LEVELUP', 'Leveling', '', NULL),
  (301, 'SA_INSTANTDEATH', 'Suicide', '', NULL),
  (302, 'SA_FULLRECOVERY', 'Rejuvenation', '', NULL),
  (303, 'SA_COMA', 'Coma', '', NULL),
  (304, 'BD_ADAPTATION', 'Amp', '', NULL),
  (305, 'BD_ENCORE', 'Encore', '', NULL),
  (306, 'BD_LULLABY', 'Lullaby', '', NULL),
  (307, 'BD_RICHMANKIM', 'Mental Sensing', '', NULL),
  (308, 'BD_ETERNALCHAOS', 'Down Tempo', '', NULL),
  (309, 'BD_DRUMBATTLEFIELD', 'Battle Theme', '', NULL),
  (310, 'BD_RINGNIBELUNGEN', 'Harmonic Lick', '', NULL),
  (311, 'BD_ROKISWEIL', 'Classical Pluck', '', NULL),
  (312, 'BD_INTOABYSS', 'Power Chord', '', NULL),
  (313, 'BD_SIEGFRIED', 'Acoustic Rhythm', '', NULL),
  (315, 'BA_MUSICALLESSON', 'Music Lessons', '', NULL),
  (316, 'BA_MUSICALSTRIKE', 'Melody Strike', '', NULL),
  (317, 'BA_DISSONANCE', 'Unchained Serenade', '', NULL),
  (318, 'BA_FROSTJOKER', 'Unbarring Octave', '', NULL),
  (319, 'BA_WHISTLE', 'Perfect Tablature', '', NULL),
  (320, 'BA_ASSASSINCROSS', 'Impressive Riff', '', NULL),
  (321, 'BA_POEMBRAGI', 'Magic Strings', '', NULL),
  (322, 'BA_APPLEIDUN', 'Song of Lutie', '', NULL),
  (323, 'DC_DANCINGLESSON', 'Dance Lessons', '', NULL),
  (324, 'DC_THROWARROW', 'Slinging Arrow', '', NULL),
  (325, 'DC_UGLYDANCE', 'Hip Shaker', '', NULL),
  (326, 'DC_SCREAM', 'Dazzler', '', NULL),
  (327, 'DC_HUMMING', 'Focus Ballet', '', NULL),
  (328, 'DC_DONTFORGETME', 'Slow Grace', '', NULL),
  (329, 'DC_FORTUNEKISS', 'Lady Luck', '', NULL),
  (330, 'DC_SERVICEFORYOU', 'Gypsy''s Kiss', '', NULL),
  (331, 'NPC_RANDOMMOVE', 'Random Move', '', NULL),
  (332, 'NPC_SPEEDUP', 'Speed UP', '', NULL),
  (333, 'NPC_REVENGE', 'Revenge', '', NULL),
  (334, 'WE_MALE', 'I Will Protect You', '', NULL),
  (335, 'WE_FEMALE', 'I Look up to You', '', NULL),
  (336, 'WE_CALLPARTNER', 'I miss You', '', NULL),
  (337, 'ITM_TOMAHAWK', 'Throw Tomahawk', '', NULL),
  (338, 'NPC_DARKCROSS', 'Cross of Darkness', '', NULL),
  (339, 'NPC_GRANDDARKNESS', 'Grand cross of Darkness', '', NULL),
  (340, 'NPC_DARKSTRIKE', 'Soul Strike of Darkness', '', NULL),
  (341, 'NPC_DARKTHUNDER', 'Darkness Jupitel', '', NULL),
  (342, 'NPC_STOP', 'Stop', '', NULL),
  (343, 'NPC_WEAPONBRAKER', 'Break weapon', '', NULL),
  (344, 'NPC_ARMORBRAKE', 'Break armor', '', NULL),
  (345, 'NPC_HELMBRAKE', 'Break helm', '', NULL),
  (346, 'NPC_SHIELDBRAKE', 'Break shield', '', NULL),
  (347, 'NPC_UNDEADATTACK', 'Undead Element Attack', '', NULL),
  (348, 'NPC_CHANGEUNDEAD', 'Undead Attribute Change', '', NULL),
  (349, 'NPC_POWERUP', 'Power Up', '', NULL),
  (350, 'NPC_AGIUP', 'Agility Up', '', NULL),
  (351, 'NPC_SIEGEMODE', 'Siege Mode', '', NULL),
  (352, 'NPC_CALLSLAVE', 'Recall Slaves', '', NULL),
  (353, 'NPC_INVISIBLE', 'Invisible', '', NULL),
  (354, 'NPC_RUN', 'Run', '', NULL),
  (355, 'LK_AURABLADE', 'Aura Blade', '', NULL),
  (356, 'LK_PARRYING', 'Parrying', '', NULL),
  (357, 'LK_CONCENTRATION', 'Concentration', '', NULL),
  (358, 'LK_TENSIONRELAX', 'Relax', '', NULL),
  (359, 'LK_BERSERK', 'Frenzy', '', NULL),
  (360, 'LK_FURY', 'Fury', '', NULL),
  (361, 'HP_ASSUMPTIO', 'Assumptio', '', NULL),
  (362, 'HP_BASILICA', 'Basilica', '', NULL),
  (363, 'HP_MEDITATIO', 'Meditatio', '', NULL),
  (364, 'HW_SOULDRAIN', 'Soul Drain', '', NULL),
  (365, 'HW_MAGICCRASHER', 'Stave Crasher', '', NULL),
  (366, 'HW_MAGICPOWER', 'Mystical Amplification', '', NULL),
  (367, 'PA_PRESSURE', 'Gloria Domini', '', NULL),
  (368, 'PA_SACRIFICE', 'Martyr''s Reckoning', '', NULL),
  (369, 'PA_GOSPEL', 'Battle Chant', '', NULL),
  (370, 'CH_PALMSTRIKE', 'Raging Palm Strike', '', NULL),
  (371, 'CH_TIGERFIST', 'Glacier Fist', '', NULL),
  (372, 'CH_CHAINCRUSH', 'Chain Crush Combo', '', NULL),
  (373, 'PF_HPCONVERSION', 'Indulge', '', NULL),
  (374, 'PF_SOULCHANGE', 'Soul Exhale', '', NULL),
  (375, 'PF_SOULBURN', 'Soul Siphon', '', NULL),
  (376, 'ASC_KATAR', 'Advanced Katar Mastery', '', NULL),
  (378, 'ASC_EDP', 'Enchant Deadly Poison', '', NULL),
  (379, 'ASC_BREAKER', 'Soul Destroyer', '', NULL),
  (380, 'SN_SIGHT', 'Falcon Eyes', '', NULL),
  (381, 'SN_FALCONASSAULT', 'Falcon Assault', '', NULL),
  (382, 'SN_SHARPSHOOTING', 'Focused Arrow Strike', '', NULL),
  (383, 'SN_WINDWALK', 'Wind Walker', '', NULL),
  (384, 'WS_MELTDOWN', 'Shattering Strike', '', NULL),
  (385, 'WS_CREATECOIN', 'Create Coins', '', NULL),
  (386, 'WS_CREATENUGGET', 'Create Nuggets', '', NULL),
  (387, 'WS_CARTBOOST', 'Cart Boost', '', NULL),
  (388, 'WS_SYSTEMCREATE', 'Auto Attack System', '', NULL),
  (389, 'ST_CHASEWALK', 'Stealth', '', NULL),
  (390, 'ST_REJECTSWORD', 'Counter Instinct', '', NULL),
  (392, 'CR_ALCHEMY', 'Alchemy', '', NULL),
  (393, 'CR_SYNTHESISPOTION', 'Potion Synthesis', '', NULL),
  (394, 'CG_ARROWVULCAN', 'Vulcan Arrow', '', NULL),
  (395, 'CG_MOONLIT', 'Sheltering Bliss', '', NULL),
  (396, 'CG_MARIONETTE', 'Marionette Control', '', NULL),
  (397, 'LK_SPIRALPIERCE', 'Spiral Pierce', '', NULL),
  (398, 'LK_HEADCRUSH', 'Traumatic Blow', '', NULL),
  (399, 'LK_JOINTBEAT', 'Vital Strike', '', NULL),
  (400, 'HW_NAPALMVULCAN', 'Napalm Vulcan', '', NULL),
  (401, 'CH_SOULCOLLECT', 'Zen', '', NULL),
  (402, 'PF_MINDBREAKER', 'Mind Breaker', '', NULL),
  (403, 'PF_MEMORIZE', 'Foresight', '', NULL),
  (404, 'PF_FOGWALL', 'Blinding Mist', '', NULL),
  (405, 'PF_SPIDERWEB', 'Fiber Lock', '', NULL),
  (406, 'ASC_METEORASSAULT', 'Meteor Assault', '', NULL),
  (407, 'ASC_CDP', 'Create Deadly Poison', '', NULL),
  (408, 'WE_BABY', 'Baby', '', NULL),
  (409, 'WE_CALLPARENT', 'Call Parent', '', NULL),
  (410, 'WE_CALLBABY', 'Call Baby', '', NULL),
  (411, 'TK_RUN', 'Running', '', NULL),
  (412, 'TK_READYSTORM', 'Tornado Stance', '', NULL),
  (413, 'TK_STORMKICK', 'Tornado Kick', '', NULL),
  (414, 'TK_READYDOWN', 'Heel Drop Stance', '', NULL),
  (415, 'TK_DOWNKICK', 'Heel Drop', '', NULL),
  (416, 'TK_READYTURN', 'Roundhouse Stance', '', NULL),
  (417, 'TK_TURNKICK', 'Roundhouse Kick', '', NULL),
  (418, 'TK_READYCOUNTER', 'Counter Kick Stance', '', NULL),
  (419, 'TK_COUNTER', 'Counter Kick', '', NULL),
  (420, 'TK_DODGE', 'Tumbling', '', NULL),
  (421, 'TK_JUMPKICK', 'Flying Kick', '', NULL),
  (422, 'TK_HPTIME', 'Peaceful Break', '', NULL),
  (423, 'TK_SPTIME', 'Happy Break', '', NULL),
  (424, 'TK_POWER', 'Kihop', '', NULL),
  (425, 'TK_SEVENWIND', 'Mild Wind', '', NULL),
  (426, 'TK_HIGHJUMP', 'Taekwon Jump', '', NULL),
  (427, 'SG_FEEL', 'Feeling the Sun Moon and Stars', '', NULL),
  (428, 'SG_SUN_WARM', 'Warmth of the Sun', '', NULL),
  (429, 'SG_MOON_WARM', 'Warmth of the Moon', '', NULL),
  (430, 'SG_STAR_WARM', 'Warmth of the Stars', '', NULL),
  (431, 'SG_SUN_COMFORT', 'Comfort of the Sun', '', NULL),
  (432, 'SG_MOON_COMFORT', 'Comfort of the Moon', '', NULL),
  (433, 'SG_STAR_COMFORT', 'Comfort of the Stars', '', NULL),
  (434, 'SG_HATE', 'Hatred of the Sun Moon and Stars', '', NULL),
  (435, 'SG_SUN_ANGER', 'Anger of the Sun', '', NULL),
  (436, 'SG_MOON_ANGER', 'Anger of the Moon', '', NULL),
  (437, 'SG_STAR_ANGER', 'Anger of the Stars', '', NULL),
  (438, 'SG_SUN_BLESS', 'Blessing of the Sun', '', NULL),
  (439, 'SG_MOON_BLESS', 'Blessing of the Moon', '', NULL),
  (440, 'SG_STAR_BLESS', 'Blessing of the Stars', '', NULL),
  (441, 'SG_DEVIL', 'Demon of the Sun Moon and Stars', '', NULL),
  (442, 'SG_FRIEND', 'Friend of the Sun Moon and Stars', '', NULL),
  (443, 'SG_KNOWLEDGE', 'Knowledge of the Sun Moon and Stars', '', NULL),
  (444, 'SG_FUSION', 'Union of the Sun Moon and Stars', '', NULL),
  (445, 'SL_ALCHEMIST', 'Spirit of the Alchemist', '', NULL),
  (446, 'AM_BERSERKPITCHER', 'Aid Berserk Potion', '', NULL),
  (447, 'SL_MONK', 'Spirit of the Monk', '', NULL),
  (448, 'SL_STAR', 'Spirit of the Star Gladiator', '', NULL),
  (449, 'SL_SAGE', 'Spirit of the Sage', '', NULL),
  (450, 'SL_CRUSADER', 'Spirit of the Crusader', '', NULL),
  (451, 'SL_SUPERNOVICE', 'Spirit of the Supernovice', '', NULL),
  (452, 'SL_KNIGHT', 'Spirit of the Knight', '', NULL),
  (453, 'SL_WIZARD', 'Spirit of the Wizard', '', NULL),
  (454, 'SL_PRIEST', 'Spirit of the Priest', '', NULL),
  (455, 'SL_BARDDANCER', 'Spirit of the Artist', '', NULL),
  (456, 'SL_ROGUE', 'Spirit of the Rogue', '', NULL),
  (457, 'SL_ASSASIN', 'Spirit of the Assasin', '', NULL),
  (458, 'SL_BLACKSMITH', 'Spirit of the Blacksmith', '', NULL),
  (459, 'BS_ADRENALINE2', 'Advanced Adrenaline Rush', '', NULL),
  (460, 'SL_HUNTER', 'Spirit of the Hunter', '', NULL),
  (461, 'SL_SOULLINKER', 'Spirit of the Soul Linker', '', NULL),
  (462, 'SL_KAIZEL', 'Kaizel', '', NULL),
  (463, 'SL_KAAHI', 'Kaahi', '', NULL),
  (464, 'SL_KAUPE', 'Kaupe', '', NULL),
  (465, 'SL_KAITE', 'Kaite', '', NULL),
  (466, 'SL_KAINA', 'Kaina', '', NULL),
  (467, 'SL_STIN', 'Estin', '', NULL),
  (468, 'SL_STUN', 'Estun', '', NULL),
  (469, 'SL_SMA', 'Esma', '', NULL),
  (470, 'SL_SWOO', 'Eswoo', '', NULL),
  (471, 'SL_SKE', 'Eske', '', NULL),
  (472, 'SL_SKA', 'Eska', '', NULL),
  (473, 'SM_SELFPROVOKE', 'Provoke Self', '', NULL),
  (474, 'NPC_EMOTION_ON', 'Emotion ON', '', NULL),
  (475, 'ST_PRESERVE', 'Preserve', '', NULL),
  (476, 'ST_FULLSTRIP', 'Divest All', '', NULL),
  (477, 'WS_WEAPONREFINE', 'Upgrade Weapon', '', NULL),
  (478, 'CR_SLIMPITCHER', 'Aid Condensed Potion', '', NULL),
  (479, 'CR_FULLPROTECTION', 'Full Protection', '', NULL),
  (480, 'PA_SHIELDCHAIN', 'Shield Chain', '', NULL),
  (481, 'HP_MANARECHARGE', 'Mana Recharge', '', NULL),
  (482, 'PF_DOUBLECASTING', 'Double Casting', '', NULL),
  (483, 'HW_GANBANTEIN', 'Ganbantein', '', NULL),
  (484, 'HW_GRAVITATION', 'Gravitation Field', '', NULL),
  (485, 'WS_CARTTERMINATION', 'Cart Termination', '', NULL),
  (486, 'WS_OVERTHRUSTMAX', 'Maximum Power Thrust', '', NULL),
  (488, 'CG_HERMODE', 'Wand of Hermode', '', NULL),
  (489, 'CG_TAROTCARD', 'Tarot Card of Fate', '', NULL),
  (490, 'CR_ACIDDEMONSTRATION', 'Acid Demonstration', '', NULL),
  (491, 'CR_CULTIVATION', 'Plant Cultivation', '', NULL),
  (492, 'ITEM_ENCHANTARMS', 'Weapon Enchantment', '', NULL),
  (493, 'TK_MISSION', 'Taekwon Mission', '', NULL),
  (494, 'SL_HIGH', 'Spirit of Rebirth', '', NULL),
  (495, 'KN_ONEHAND', 'Onehand Quicken', '', NULL),
  (496, 'AM_TWILIGHT1', 'Twilight Alchemy 1', '', NULL),
  (497, 'AM_TWILIGHT2', 'Twilight Alchemy 2', '', NULL),
  (498, 'AM_TWILIGHT3', 'Twilight Alchemy 3', '', NULL),
  (499, 'HT_POWER', 'Beast Strafing', '', NULL),
  (500, 'GS_GLITTERING', 'Flip the Coin', '', NULL),
  (501, 'GS_FLING', 'Fling', '', NULL),
  (502, 'GS_TRIPLEACTION', 'Triple Action', '', NULL),
  (503, 'GS_BULLSEYE', 'Bulls Eye', '', NULL),
  (504, 'GS_MADNESSCANCEL', 'Madness Canceller', '', NULL),
  (505, 'GS_ADJUSTMENT', 'Adjustment', '', NULL),
  (506, 'GS_INCREASING', 'Increasing Accuracy', '', NULL),
  (507, 'GS_MAGICALBULLET', 'Magical Bullet', '', NULL),
  (508, 'GS_CRACKER', 'Cracker', '', NULL),
  (509, 'GS_SINGLEACTION', 'Single Action', '', NULL),
  (510, 'GS_SNAKEEYE', 'Snake Eye', '', NULL),
  (511, 'GS_CHAINACTION', 'Chain Action', '', NULL),
  (512, 'GS_TRACKING', 'Tracking', '', NULL),
  (513, 'GS_DISARM', 'Disarm', '', NULL),
  (514, 'GS_PIERCINGSHOT', 'Piercing Shot', '', NULL),
  (515, 'GS_RAPIDSHOWER', 'Rapid Shower', '', NULL),
  (516, 'GS_DESPERADO', 'Desperado', '', NULL),
  (517, 'GS_GATLINGFEVER', 'Gatling Fever', '', NULL),
  (518, 'GS_DUST', 'Dust', '', NULL),
  (519, 'GS_FULLBUSTER', 'Full Buster', '', NULL),
  (520, 'GS_SPREADATTACK', 'Spread Attack', '', NULL),
  (521, 'GS_GROUNDDRIFT', 'Ground Drift', '', NULL),
  (522, 'NJ_TOBIDOUGU', 'Shuriken Training', '', NULL),
  (523, 'NJ_SYURIKEN', 'Throw Shuriken', '', NULL),
  (524, 'NJ_KUNAI', 'Throw Kunai', '', NULL),
  (525, 'NJ_HUUMA', 'Throw Huuma Shuriken', '', NULL),
  (526, 'NJ_ZENYNAGE', 'Throw Zeny', '', NULL),
  (527, 'NJ_TATAMIGAESHI', 'Improvised Defense', '', NULL),
  (528, 'NJ_KASUMIKIRI', 'Vanishing Slash', '', NULL),
  (529, 'NJ_SHADOWJUMP', 'Shadow Leap', '', NULL),
  (530, 'NJ_KIRIKAGE', 'Shadow Slash', '', NULL),
  (531, 'NJ_UTSUSEMI', 'Cicada Skin Sheeding', '', NULL),
  (532, 'NJ_BUNSINJYUTSU', 'Mirror Image', '', NULL),
  (533, 'NJ_NINPOU', 'Spirit of the Blade', '', NULL),
  (534, 'NJ_KOUENKA', 'Crimson Fire Petal', '', NULL),
  (535, 'NJ_KAENSIN', 'Crimson Fire Formation', '', NULL),
  (536, 'NJ_BAKUENRYU', 'Raging Fire Dragon', '', NULL),
  (537, 'NJ_HYOUSENSOU', 'Spear of Ice', '', NULL),
  (538, 'NJ_SUITON', 'Hidden Water', '', NULL),
  (539, 'NJ_HYOUSYOURAKU', 'Ice Meteor', '', NULL),
  (540, 'NJ_HUUJIN', 'Wind Blade', '', NULL),
  (541, 'NJ_RAIGEKISAI', 'Lightning Strike of Destruction', '', NULL),
  (542, 'NJ_KAMAITACHI', 'Kamaitachi', '', NULL),
  (543, 'NJ_NEN', 'Soul', '', NULL),
  (544, 'NJ_ISSEN', 'Final Strike', '', NULL),
  (572, 'SL_DEATHKNIGHT', 'SL_DEATHKNIGHT', '', NULL),
  (573, 'SL_COLLECTOR', 'SL_COLLECTOR', '', NULL),
  (574, 'SL_NINJA', 'SL_NINJA', '', NULL),
  (575, 'SL_GUNNER', 'SL_GUNNER', '', NULL),
  (653, 'NPC_EARTHQUAKE', 'Earthquake', '', NULL),
  (654, 'NPC_FIREBREATH', 'Fire Breath', '', NULL),
  (655, 'NPC_ICEBREATH', 'Ice Breath', '', NULL),
  (656, 'NPC_THUNDERBREATH', 'Thunder Breath', '', NULL),
  (657, 'NPC_ACIDBREATH', 'Acid Breath', '', NULL),
  (658, 'NPC_DARKNESSBREATH', 'Darkness Breath', '', NULL),
  (659, 'NPC_DRAGONFEAR', 'Dragon Fear', '', NULL),
  (660, 'NPC_BLEEDING', 'Bleeding', '', NULL),
  (661, 'NPC_PULSESTRIKE', 'Pulse Strike', '', NULL),
  (662, 'NPC_HELLJUDGEMENT', 'Hell''s Judgement', '', NULL),
  (663, 'NPC_WIDESILENCE', 'Wide Silence', '', NULL),
  (664, 'NPC_WIDEFREEZE', 'Wide Freeze', '', NULL),
  (665, 'NPC_WIDEBLEEDING', 'Wide Bleeding', '', NULL),
  (666, 'NPC_WIDESTONE', 'Wide Petrify', '', NULL),
  (667, 'NPC_WIDECONFUSE', 'Wide Confusion', '', NULL),
  (668, 'NPC_WIDESLEEP', 'Wide Sleep', '', NULL),
  (669, 'NPC_WIDESIGHT', 'Wide Sight', '', NULL),
  (670, 'NPC_EVILLAND', 'Evil Land', '', NULL),
  (671, 'NPC_MAGICMIRROR', 'Magic Mirror', '', NULL),
  (672, 'NPC_SLOWCAST', 'Slow Cast', '', NULL),
  (673, 'NPC_CRITICALWOUND', 'Critical Wounds', '', NULL),
  (674, 'NPC_EXPULSION', 'Expulsion', '', NULL),
  (675, 'NPC_STONESKIN', 'Stone Skin', '', NULL),
  (676, 'NPC_ANTIMAGIC', 'Anti Magic', '', NULL),
  (677, 'NPC_WIDECURSE', 'Wide Curse', '', NULL),
  (678, 'NPC_WIDESTUN', 'Wide Stun', '', NULL),
  (679, 'NPC_VAMPIRE_GIFT', 'Vampire Gift', '', NULL),
  (680, 'NPC_WIDESOULDRAIN', 'Wide Soul Drain', '', NULL),
  (681, 'ALL_INCCARRY', 'Increase Weight Limit R', '', NULL),
  (682, 'NPC_TALK', 'Talk', '', NULL),
  (683, 'NPC_HELLPOWER', 'Hell Power', '', NULL),
  (684, 'NPC_WIDEHELLDIGNITY', 'Hell Dignity', '', NULL),
  (685, 'NPC_INVINCIBLE', 'Invincible', '', NULL),
  (686, 'NPC_INVINCIBLEOFF', 'Invincible off', '', NULL),
  (687, 'NPC_ALLHEAL', 'Full Heal', '', NULL),
  (688, 'GM_SANDMAN', 'GM Sandman', '', NULL),
  (689, 'CASH_BLESSING', 'Party Blessing', '', NULL),
  (690, 'CASH_INCAGI', 'Party Increase AGI', '', NULL),
  (691, 'CASH_ASSUMPTIO', 'Party Assumptio', '', NULL),
  (692, 'ALL_CATCRY', 'Cat Cry', '', NULL),
  (693, 'ALL_PARTYFLEE', 'Party Flee', '', NULL),
  (694, 'ALL_ANGEL_PROTECT', 'Angel''s Protection', '', NULL),
  (695, 'ALL_DREAM_SUMMERNIGHT', 'Summer Night Dream', '', NULL),
  (697, 'ALL_REVERSEORCISH', 'Reverse Orcish', '', NULL),
  (698, 'ALL_WEWISH', 'Christmas Carol', '', NULL),
  (706, 'NPC_VENOMFOG', 'Venom Fog', '', NULL),
  (707, 'NPC_MILLENNIUMSHIELD', 'Millenium Shield 2', '', NULL),
  (708, 'NPC_COMET', 'Comet 2', '', NULL),
  (709, 'NPC_ICEMINE', 'Ice Mine', '', NULL),
  (711, 'NPC_FLAMECROSS', 'Flame Cross', '', NULL),
  (712, 'NPC_PULSESTRIKE2', 'Pulse Strike 2', '', NULL),
  (713, 'NPC_DANCINGBLADE', 'Dancing Blade', '', NULL),
  (714, 'NPC_DANCINGBLADE_ATK', 'Dancing Blade Attack', '', NULL),
  (715, 'NPC_DARKPIERCING', 'Dark Piercing', '', NULL),
  (716, 'NPC_MAXPAIN', 'Max Pain', '', NULL),
  (717, 'NPC_MAXPAIN_ATK', 'Max Pain Attack', '', NULL),
  (718, 'NPC_DEATHSUMMON', 'Death Summon', '', NULL),
  (719, 'NPC_HELLBURNING', 'Hell Burning', '', NULL),
  (720, 'NPC_JACKFROST', 'Jack Frost 2', '', NULL),
  (721, 'NPC_WIDEWEB', 'Wide Web', '', NULL),
  (722, 'NPC_WIDESUCK', 'Wide Suck', '', NULL),
  (723, 'NPC_STORMGUST2', 'Storm Gust 2', '', NULL),
  (724, 'NPC_FIRESTORM', 'Fire Storm', '', NULL),
  (725, 'NPC_REVERBERATION', 'Reverberation 2', '', NULL),
  (726, 'NPC_REVERBERATION_ATK', 'Reverberation Attack', '', NULL),
  (727, 'NPC_LEX_AETERNA', 'Lex Aeterna 2', '', NULL),
  (728, 'NPC_ARROWSTORM', 'NPC Arrow Storm', '', NULL),
  (729, 'NPC_CHEAL', 'NPC Coluceo Heal', '', NULL),
  (730, 'NPC_SR_CURSEDCIRCLE', 'Cursed Circle', '', NULL),
  (731, 'NPC_DRAGONBREATH', 'NPC Dragon Breath', '', NULL),
  (732, 'NPC_FATALMENACE', 'Fatal Menace', '', NULL),
  (733, 'NPC_MAGMA_ERUPTION', 'NPC Magma Eruption', '', NULL),
  (734, 'NPC_MAGMA_ERUPTION_DOTDAMAGE', 'NPC Magma Eruption Dot Damage', '', NULL),
  (735, 'NPC_MANDRAGORA', 'NPC Howling of Mandragora', '', NULL),
  (736, 'NPC_PSYCHIC_WAVE', 'Psychic Wave', '', NULL),
  (737, 'NPC_RAYOFGENESIS', 'NPC Ray of Genesis', '', NULL),
  (738, 'NPC_VENOMIMPRESS', 'NPC Venom Impress', '', NULL),
  (739, 'NPC_CLOUD_KILL', 'Cloud Kill', '', NULL),
  (740, 'NPC_IGNITIONBREAK', 'Ignition Break', '', NULL),
  (741, 'NPC_PHANTOMTHRUST', 'Phantom Thrust', '', NULL),
  (742, 'NPC_POISON_BUSTER', 'Poison Buster', '', NULL),
  (743, 'NPC_HALLUCINATIONWALK', 'Hallucination Walk', '', NULL),
  (744, 'NPC_ELECTRICWALK', 'Electric Walk', '', NULL),
  (745, 'NPC_FIREWALK', 'Fire Walk', '', NULL),
  (747, 'NPC_LEASH', 'Leash', '', NULL),
  (748, 'NPC_WIDELEASH', 'Wide Leash', '', NULL),
  (749, 'NPC_WIDECRITICALWOUND', 'Wide Critical Wounds', '', NULL),
  (751, 'NPC_ALL_STAT_DOWN', 'Decrease All Stats', '', NULL),
  (752, 'NPC_GRADUAL_GRAVITY', 'Increased Gravity', '', NULL),
  (753, 'NPC_DAMAGE_HEAL', 'Damage Heal', '', NULL),
  (754, 'NPC_IMMUNE_PROPERTY', 'Property Immune', '', NULL),
  (755, 'NPC_MOVE_COORDINATE', 'Change Location', '', NULL),
  (756, 'NPC_WIDEBLEEDING2', 'Wide Bleeding', '', NULL),
  (757, 'NPC_WIDESILENCE2', 'Wide Silence', '', NULL),
  (758, 'NPC_WIDESTUN2', 'Wide Stun', '', NULL),
  (759, 'NPC_WIDESTONE2', 'Wide Petrify', '', NULL),
  (760, 'NPC_WIDESLEEP2', 'Wide Sleep', '', NULL),
  (761, 'NPC_WIDECURSE2', 'Wide Curse', '', NULL),
  (762, 'NPC_WIDECONFUSE2', 'Wide Confusion', '', NULL),
  (763, 'NPC_WIDEFREEZE2', 'Wide Freeze', '', NULL),
  (764, 'NPC_BLEEDING2', 'Bleeding', '', NULL),
  (765, 'NPC_ICEBREATH2', 'Ice Breath', '', NULL),
  (768, 'NPC_HELLJUDGEMENT2', 'Hell''s Judgement', '', NULL),
  (769, 'NPC_RAINOFMETEOR', 'Rain of Meteor', '', NULL),
  (770, 'NPC_GROUNDDRIVE', 'Ground Drive', '', NULL),
  (771, 'NPC_RELIEVE_ON', 'NPC_RELIEVE_ON', '', NULL),
  (772, 'NPC_RELIEVE_OFF', 'NPC_RELIEVE_OFF', '', NULL),
  (776, 'NPC_DEADLYCURSE', 'Deadly Curse', '', NULL),
  (779, 'NPC_DEADLYCURSE2', 'Deadly Curse 2', '', NULL),
  (780, 'NPC_CANE_OF_EVIL_EYE', 'Cane of evil eye', '', NULL),
  (783, 'NPC_KILLING_AURA', 'Killing Aura', '', NULL),
  (784, 'ALL_EVENT_20TH_ANNIVERSARY', 'RO 20th Anniversary Firecracker', '', NULL),
  (1001, 'KN_CHARGEATK', 'Charge Attack', '', NULL),
  (1002, 'CR_SHRINK', 'Shrink', '', NULL),
  (1003, 'AS_SONICACCEL', 'Sonic Acceleration', '', NULL),
  (1004, 'AS_VENOMKNIFE', 'Throw Venom Knife', '', NULL),
  (1005, 'RG_CLOSECONFINE', 'Close Confine', '', NULL),
  (1006, 'WZ_SIGHTBLASTER', 'Sight Blaster', '', NULL),
  (1007, 'SA_CREATECON', 'Create Elemental Converter', '', NULL),
  (1008, 'SA_ELEMENTWATER', 'Elemental Change Water', '', NULL),
  (1009, 'HT_PHANTASMIC', 'Phantasmic Arrow', '', NULL),
  (1010, 'BA_PANGVOICE', 'Pang Voice', '', NULL),
  (1011, 'DC_WINKCHARM', 'Wink of Charm', '', NULL),
  (1012, 'BS_UNFAIRLYTRICK', 'Unfair Trick', '', NULL),
  (1013, 'BS_GREED', 'Greed', '', NULL),
  (1014, 'PR_REDEMPTIO', 'Redemptio', '', NULL),
  (1015, 'MO_KITRANSLATION', 'Ki Translation', '', NULL),
  (1016, 'MO_BALKYOUNG', 'Ki Explosion', '', NULL),
  (1017, 'SA_ELEMENTGROUND', 'Elemental Change Earth', '', NULL),
  (1018, 'SA_ELEMENTFIRE', 'Elemental Change Fire', '', NULL),
  (1019, 'SA_ELEMENTWIND', 'Elemental Change Wind', '', NULL),
  (2001, 'RK_ENCHANTBLADE', 'Enchant Blade', '', NULL),
  (2002, 'RK_SONICWAVE', 'Sonic Wave', '', NULL),
  (2003, 'RK_DEATHBOUND', 'Death Bound', '', NULL),
  (2004, 'RK_HUNDREDSPEAR', 'Hundred Spear', '', NULL),
  (2005, 'RK_WINDCUTTER', 'Wind Cutter', '', NULL),
  (2006, 'RK_IGNITIONBREAK', 'Ignition Break', '', NULL),
  (2007, 'RK_DRAGONTRAINING', 'Dragon Training', '', NULL),
  (2008, 'RK_DRAGONBREATH', 'Dragon Breath', '', NULL),
  (2009, 'RK_DRAGONHOWLING', 'Dragon Howling', '', NULL),
  (2010, 'RK_RUNEMASTERY', 'Rune Mastery', '', NULL),
  (2011, 'RK_MILLENNIUMSHIELD', 'Millenium Shield', '', NULL),
  (2012, 'RK_CRUSHSTRIKE', 'Crush Strike', '', NULL),
  (2013, 'RK_REFRESH', 'Refresh', '', NULL),
  (2014, 'RK_GIANTGROWTH', 'Giant Growth', '', NULL),
  (2015, 'RK_STONEHARDSKIN', 'Stone Hard Skin', '', NULL),
  (2016, 'RK_VITALITYACTIVATION', 'Vitality Activation', '', NULL),
  (2017, 'RK_STORMBLAST', 'Storm Blast', '', NULL),
  (2018, 'RK_FIGHTINGSPIRIT', 'Fighting Spirit', '', NULL),
  (2019, 'RK_ABUNDANCE', 'Abundance', '', NULL),
  (2020, 'RK_PHANTOMTHRUST', 'Phantom Thrust', '', NULL),
  (2201, 'WL_WHITEIMPRISON', 'White Imprison', '', NULL),
  (2202, 'WL_SOULEXPANSION', 'Soul Expansion', '', NULL),
  (2203, 'WL_FROSTMISTY', 'Frosty Misty', '', NULL),
  (2204, 'WL_JACKFROST', 'Jack Frost', '', NULL),
  (2205, 'WL_MARSHOFABYSS', 'Marsh of Abyss', '', NULL),
  (2206, 'WL_RECOGNIZEDSPELL', 'Recognized Spell', '', NULL),
  (2207, 'WL_SIENNAEXECRATE', 'Sienna Execrate', '', NULL),
  (2208, 'WL_RADIUS', 'Radius', '', NULL),
  (2209, 'WL_STASIS', 'Stasis', '', NULL),
  (2210, 'WL_DRAINLIFE', 'Drain Life', '', NULL),
  (2211, 'WL_CRIMSONROCK', 'Crimson Rock', '', NULL),
  (2212, 'WL_HELLINFERNO', 'Hell Inferno', '', NULL),
  (2213, 'WL_COMET', 'Comet', '', NULL),
  (2214, 'WL_CHAINLIGHTNING', 'Chain Lightning', '', NULL),
  (2215, 'WL_CHAINLIGHTNING_ATK', 'Chain Lightning Attack', '', NULL),
  (2216, 'WL_EARTHSTRAIN', 'Earth Strain', '', NULL),
  (2217, 'WL_TETRAVORTEX', 'Tetra Vortex', '', NULL),
  (2218, 'WL_TETRAVORTEX_FIRE', 'Tetra Vortex Fire', '', NULL),
  (2219, 'WL_TETRAVORTEX_WATER', 'Tetra Vortex Water', '', NULL),
  (2220, 'WL_TETRAVORTEX_WIND', 'Tetra Vortex Wind', '', NULL),
  (2221, 'WL_TETRAVORTEX_GROUND', 'Tetra Vortex Earth', '', NULL),
  (2222, 'WL_SUMMONFB', 'Summon Fire Ball', '', NULL),
  (2223, 'WL_SUMMONBL', 'Summon Lightning Ball', '', NULL),
  (2224, 'WL_SUMMONWB', 'Summon Water Ball', '', NULL),
  (2225, 'WL_SUMMON_ATK_FIRE', 'Summon Attack Fire', '', NULL),
  (2226, 'WL_SUMMON_ATK_WIND', 'Summon Attack Wind', '', NULL),
  (2227, 'WL_SUMMON_ATK_WATER', 'Summon Attack Water', '', NULL),
  (2228, 'WL_SUMMON_ATK_GROUND', 'Summon Attack Earth', '', NULL),
  (2229, 'WL_SUMMONSTONE', 'Summon Stone', '', NULL),
  (2230, 'WL_RELEASE', 'Release', '', NULL),
  (2231, 'WL_READING_SB', 'Reading Spellbook', '', NULL),
  (2232, 'WL_FREEZE_SP', 'Freeze Spell', '', NULL),
  (2021, 'GC_VENOMIMPRESS', 'Venom Impress', '', NULL),
  (2022, 'GC_CROSSIMPACT', 'Cross Impact', '', NULL),
  (2023, 'GC_DARKILLUSION', 'Dark Illusion', '', NULL),
  (2024, 'GC_RESEARCHNEWPOISON', 'Research New Poison', '', NULL),
  (2025, 'GC_CREATENEWPOISON', 'Create New Poison', '', NULL),
  (2026, 'GC_ANTIDOTE', 'Antidote', '', NULL),
  (2027, 'GC_POISONINGWEAPON', 'Poisoning Weapon', '', NULL),
  (2028, 'GC_WEAPONBLOCKING', 'Weapon Blocking', '', NULL),
  (2029, 'GC_COUNTERSLASH', 'Counter Slash', '', NULL),
  (2030, 'GC_WEAPONCRUSH', 'Weapon Crush', '', NULL),
  (2031, 'GC_VENOMPRESSURE', 'Venom Pressure', '', NULL),
  (2032, 'GC_POISONSMOKE', 'Poison Smoke', '', NULL),
  (2033, 'GC_CLOAKINGEXCEED', 'Cloaking Exceed', '', NULL),
  (2034, 'GC_PHANTOMMENACE', 'Phantom Menace', '', NULL),
  (2035, 'GC_HALLUCINATIONWALK', 'Hallucination Walk', '', NULL),
  (2036, 'GC_ROLLINGCUTTER', 'Rolling Cutter', '', NULL),
  (2037, 'GC_CROSSRIPPERSLASHER', 'Cross Ripper Slasher', '', NULL),
  (2038, 'AB_JUDEX', 'Judex', '', NULL),
  (2039, 'AB_ANCILLA', 'Ancilla', '', NULL),
  (2040, 'AB_ADORAMUS', 'Adoramus', '', NULL),
  (2041, 'AB_CLEMENTIA', 'Crementia', '', NULL),
  (2042, 'AB_CANTO', 'Canto Candidus', '', NULL),
  (2043, 'AB_CHEAL', 'Coluceo Heal', '', NULL),
  (2044, 'AB_EPICLESIS', 'Epiclesis', '', NULL),
  (2045, 'AB_PRAEFATIO', 'Praefatio', '', NULL),
  (2046, 'AB_ORATIO', 'Oratio', '', NULL),
  (2047, 'AB_LAUDAAGNUS', 'Lauda Agnus', '', NULL),
  (2048, 'AB_LAUDARAMUS', 'Lauda Ramus', '', NULL),
  (2049, 'AB_EUCHARISTICA', 'Eucharistica', '', NULL),
  (2050, 'AB_RENOVATIO', 'Renovatio', '', NULL),
  (2051, 'AB_HIGHNESSHEAL', 'Highness Heal', '', NULL),
  (2052, 'AB_CLEARANCE', 'Clearance', '', NULL),
  (2053, 'AB_EXPIATIO', 'Expiatio', '', NULL),
  (2054, 'AB_DUPLELIGHT', 'Duple Light', '', NULL),
  (2055, 'AB_DUPLELIGHT_MELEE', 'Duple Light Melee', '', NULL),
  (2056, 'AB_DUPLELIGHT_MAGIC', 'Duple Light Magic', '', NULL),
  (2057, 'AB_SILENTIUM', 'Silentium', '', NULL),
  (2515, 'AB_SECRAMENT', 'Secrament', '', NULL),
  (2233, 'RA_ARROWSTORM', 'Arrow Storm', '', NULL),
  (2234, 'RA_FEARBREEZE', 'Fear Breeze', '', NULL),
  (2235, 'RA_RANGERMAIN', 'Ranger Main', '', NULL),
  (2236, 'RA_AIMEDBOLT', 'Aimed Bolt', '', NULL),
  (2237, 'RA_DETONATOR', 'Detonator', '', NULL),
  (2238, 'RA_ELECTRICSHOCKER', 'Electric Shocker', '', NULL),
  (2239, 'RA_CLUSTERBOMB', 'Cluster Bomb', '', NULL),
  (2240, 'RA_WUGMASTERY', 'Warg Mastery', '', NULL),
  (2241, 'RA_WUGRIDER', 'Warg Rider', '', NULL),
  (2242, 'RA_WUGDASH', 'Warg Dash', '', NULL),
  (2243, 'RA_WUGSTRIKE', 'Warg Strike', '', NULL),
  (2244, 'RA_WUGBITE', 'Warg Bite', '', NULL),
  (2245, 'RA_TOOTHOFWUG', 'Tooth of Warg', '', NULL),
  (2246, 'RA_SENSITIVEKEEN', 'Sensitive Keen', '', NULL),
  (2247, 'RA_CAMOUFLAGE', 'Camouflage', '', NULL),
  (2248, 'RA_RESEARCHTRAP', 'Research Trap', '', NULL),
  (2249, 'RA_MAGENTATRAP', 'Magenta Trap', '', NULL),
  (2250, 'RA_COBALTTRAP', 'Cobalt Trap', '', NULL),
  (2251, 'RA_MAIZETRAP', 'Maize Trap', '', NULL),
  (2252, 'RA_VERDURETRAP', 'Verdure Trap', '', NULL),
  (2253, 'RA_FIRINGTRAP', 'Firing Trap', '', NULL),
  (2254, 'RA_ICEBOUNDTRAP', 'Icebound Trap', '', NULL),
  (2255, 'NC_MADOLICENCE', 'Mado License', '', NULL),
  (2256, 'NC_BOOSTKNUCKLE', 'Boost Knuckle', '', NULL),
  (2257, 'NC_PILEBUNKER', 'Pile Bunker', '', NULL),
  (2258, 'NC_VULCANARM', 'Vulcan Arm', '', NULL),
  (2259, 'NC_FLAMELAUNCHER', 'Flame Launcher', '', NULL),
  (2260, 'NC_COLDSLOWER', 'Cold Slower', '', NULL),
  (2261, 'NC_ARMSCANNON', 'Arm Cannon', '', NULL),
  (2262, 'NC_ACCELERATION', 'Acceleration', '', NULL),
  (2263, 'NC_HOVERING', 'Hovering', '', NULL),
  (2264, 'NC_F_SIDESLIDE', 'Front-Side Slide', '', NULL),
  (2265, 'NC_B_SIDESLIDE', 'Back-Side Slide', '', NULL),
  (2266, 'NC_MAINFRAME', 'Mainframe Restructure', '', NULL),
  (2267, 'NC_SELFDESTRUCTION', 'Self Destruction', '', NULL),
  (2268, 'NC_SHAPESHIFT', 'Shape Shift', '', NULL),
  (2269, 'NC_EMERGENCYCOOL', 'Emergency Cool', '', NULL),
  (2270, 'NC_INFRAREDSCAN', 'Infrared Scan', '', NULL),
  (2271, 'NC_ANALYZE', 'Analyze', '', NULL),
  (2272, 'NC_MAGNETICFIELD', 'Magnetic Field', '', NULL),
  (2273, 'NC_NEUTRALBARRIER', 'Neutral Barrier', '', NULL),
  (2274, 'NC_STEALTHFIELD', 'Stealth Field', '', NULL),
  (2275, 'NC_REPAIR', 'Repair', '', NULL),
  (2276, 'NC_TRAININGAXE', 'Axe Training', '', NULL),
  (2277, 'NC_RESEARCHFE', 'Research Fire/Earth', '', NULL),
  (2278, 'NC_AXEBOOMERANG', 'Axe Boomerang', '', NULL),
  (2279, 'NC_POWERSWING', 'Power Swing', '', NULL),
  (2280, 'NC_AXETORNADO', 'Axe Tornado', '', NULL),
  (2281, 'NC_SILVERSNIPER', 'FAW - Silver Sniper', '', NULL),
  (2282, 'NC_MAGICDECOY', 'FAW - Magic Decoy', '', NULL),
  (2283, 'NC_DISJOINT', 'FAW Removal', '', NULL),
  (2284, 'SC_FATALMENACE', 'Fatal Menace', '', NULL),
  (2285, 'SC_REPRODUCE', 'Reproduce', '', NULL),
  (2286, 'SC_AUTOSHADOWSPELL', 'Auto Shadow Spell', '', NULL),
  (2287, 'SC_SHADOWFORM', 'Shadow Form', '', NULL),
  (2288, 'SC_TRIANGLESHOT', 'Triangle Shot', '', NULL),
  (2289, 'SC_BODYPAINT', 'Body Painting', '', NULL),
  (2290, 'SC_INVISIBILITY', 'Invisibility', '', NULL),
  (2291, 'SC_DEADLYINFECT', 'Deadly Infect', '', NULL),
  (2292, 'SC_ENERVATION', 'Masquerade - Enervation', '', NULL),
  (2293, 'SC_GROOMY', 'Masquerade - Gloomy', '', NULL),
  (2294, 'SC_IGNORANCE', 'Masquerade - Ignorance', '', NULL),
  (2295, 'SC_LAZINESS', 'Masquerade - Laziness', '', NULL),
  (2296, 'SC_UNLUCKY', 'Masquerade - Unlucky', '', NULL),
  (2297, 'SC_WEAKNESS', 'Masquerade - Weakness', '', NULL),
  (2298, 'SC_STRIPACCESSARY', 'Strip Accessory', '', NULL),
  (2299, 'SC_MANHOLE', 'Man Hole', '', NULL),
  (2300, 'SC_DIMENSIONDOOR', 'Dimension Door', '', NULL),
  (2301, 'SC_CHAOSPANIC', 'Chaos Panic', '', NULL),
  (2302, 'SC_MAELSTROM', 'Maelstrom', '', NULL),
  (2303, 'SC_BLOODYLUST', 'Bloody Lust', '', NULL),
  (2304, 'SC_FEINTBOMB', 'Feint Bomb', '', NULL),
  (2307, 'LG_CANNONSPEAR', 'Cannon Spear', '', NULL),
  (2308, 'LG_BANISHINGPOINT', 'Banishing Point', '', NULL),
  (2309, 'LG_TRAMPLE', 'Trample', '', NULL),
  (2310, 'LG_SHIELDPRESS', 'Shield Press', '', NULL),
  (2311, 'LG_REFLECTDAMAGE', 'Reflect Damage Reduction', '', NULL),
  (2312, 'LG_PINPOINTATTACK', 'Pinpoint Attack', '', NULL),
  (2313, 'LG_FORCEOFVANGUARD', 'Force of Vanguard', '', NULL),
  (2314, 'LG_RAGEBURST', 'Rage Burst', '', NULL),
  (2315, 'LG_SHIELDSPELL', 'Shield Spell', '', NULL),
  (2316, 'LG_EXEEDBREAK', 'Exceed Break', '', NULL),
  (2317, 'LG_OVERBRAND', 'Over Brand', '', NULL),
  (2318, 'LG_PRESTIGE', 'Prestige', '', NULL),
  (2319, 'LG_BANDING', 'Banding', '', NULL),
  (2320, 'LG_MOONSLASHER', 'Moon Slasher', '', NULL),
  (2321, 'LG_RAYOFGENESIS', 'Ray of Genesis', '', NULL),
  (2322, 'LG_PIETY', 'Piety', '', NULL),
  (2323, 'LG_EARTHDRIVE', 'Earth Drive', '', NULL),
  (2324, 'LG_HESPERUSLIT', 'Hesperus Lit', '', NULL),
  (2325, 'LG_INSPIRATION', 'Inspiration', '', NULL),
  (2519, 'LG_OVERBRAND_BRANDISH', 'Overbrand Brandish', '', NULL),
  (2520, 'LG_OVERBRAND_PLUSATK', 'Overbrand Plus Attack', '', NULL),
  (2326, 'SR_DRAGONCOMBO', 'Dragon Combo', '', NULL),
  (2327, 'SR_SKYNETBLOW', 'Sky Net Blow', '', NULL),
  (2328, 'SR_EARTHSHAKER', 'Earth Shaker', '', NULL),
  (2329, 'SR_FALLENEMPIRE', 'Fallen Empire', '', NULL),
  (2330, 'SR_TIGERCANNON', 'Tiger Cannon', '', NULL),
  (2331, 'SR_HELLGATE', 'Hell Gate', '', NULL),
  (2332, 'SR_RAMPAGEBLASTER', 'Rampage Blaster', '', NULL),
  (2333, 'SR_CRESCENTELBOW', 'Crescent Elbow', '', NULL),
  (2334, 'SR_CURSEDCIRCLE', 'Cursed Circle', '', NULL),
  (2335, 'SR_LIGHTNINGWALK', 'Lightning Walk', '', NULL),
  (2336, 'SR_KNUCKLEARROW', 'Knuckle Arrow', '', NULL),
  (2337, 'SR_WINDMILL', 'Windmill', '', NULL),
  (2338, 'SR_RAISINGDRAGON', 'Raising Dragon', '', NULL),
  (2339, 'SR_GENTLETOUCH', 'Gentle Touch', '', NULL),
  (2340, 'SR_ASSIMILATEPOWER', 'Assimilate Power', '', NULL),
  (2341, 'SR_POWERVELOCITY', 'Power Velocity', '', NULL),
  (2342, 'SR_CRESCENTELBOW_AUTOSPELL', 'Crescent Elbow Autospell', '', NULL),
  (2343, 'SR_GATEOFHELL', 'Gate of Hell', '', NULL),
  (2344, 'SR_GENTLETOUCH_QUIET', 'Gentle Touch - Quiet', '', NULL),
  (2345, 'SR_GENTLETOUCH_CURE', 'Gentle Touch - Cure', '', NULL),
  (2346, 'SR_GENTLETOUCH_ENERGYGAIN', 'Gentle Touch - Energy Gain', '', NULL),
  (2347, 'SR_GENTLETOUCH_CHANGE', 'Gentle Touch - Change', '', NULL),
  (2348, 'SR_GENTLETOUCH_REVITALIZE', 'Gentle Touch - Revitalize', '', NULL),
  (2517, 'SR_HOWLINGOFLION', 'Howling of Lion', '', NULL),
  (2518, 'SR_RIDEINLIGHTNING', 'Ride In Lightening', '', NULL),
  (2350, 'WA_SWING_DANCE', 'Swing Dance', '', NULL),
  (2351, 'WA_SYMPHONY_OF_LOVER', 'Symphony of Lovers', '', NULL),
  (2352, 'WA_MOONLIT_SERENADE', 'Moonlit Serenade', '', NULL),
  (2381, 'MI_RUSH_WINDMILL', 'Windmill Rush Attack', '', NULL),
  (2382, 'MI_ECHOSONG', 'Echo Song', '', NULL),
  (2383, 'MI_HARMONIZE', 'Harmonize', '', NULL),
  (2412, 'WM_LESSON', 'Lesson', '', NULL),
  (2413, 'WM_METALICSOUND', 'Metallic Sound', '', NULL),
  (2414, 'WM_REVERBERATION', 'Reverberation', '', NULL),
  (2415, 'WM_REVERBERATION_MELEE', 'Reverberation Melee', '', NULL),
  (2416, 'WM_REVERBERATION_MAGIC', 'Reverberation Magic', '', NULL),
  (2417, 'WM_DOMINION_IMPULSE', 'Dominion Impulse', '', NULL),
  (2418, 'WM_SEVERE_RAINSTORM', 'Severe Rainstorm', '', NULL),
  (2419, 'WM_POEMOFNETHERWORLD', 'Poem of The Netherworld', '', NULL),
  (2420, 'WM_VOICEOFSIREN', 'Voice of Siren', '', NULL),
  (2421, 'WM_DEADHILLHERE', 'Valley of Death', '', NULL),
  (2422, 'WM_LULLABY_DEEPSLEEP', 'Deep Sleep Lullaby', '', NULL),
  (2423, 'WM_SIRCLEOFNATURE', 'Circle of Nature''s Sound', '', NULL),
  (2424, 'WM_RANDOMIZESPELL', 'Improvised Song', '', NULL),
  (2425, 'WM_GLOOMYDAY', 'Gloomy Day', '', NULL),
  (2426, 'WM_GREAT_ECHO', 'Great Echo', '', NULL),
  (2427, 'WM_SONG_OF_MANA', 'Song of Mana', '', NULL),
  (2428, 'WM_DANCE_WITH_WUG', 'Dance With A Warg', '', NULL),
  (2429, 'WM_SOUND_OF_DESTRUCTION', 'Sound of Destruction', '', NULL),
  (2430, 'WM_SATURDAY_NIGHT_FEVER', 'Saturday Night Fever', '', NULL),
  (2431, 'WM_LERADS_DEW', 'Lerad''s Dew', '', NULL),
  (2432, 'WM_MELODYOFSINK', 'Melody of Sink', '', NULL),
  (2433, 'WM_BEYOND_OF_WARCRY', 'Warcry of Beyond', '', NULL),
  (2434, 'WM_UNLIMITED_HUMMING_VOICE', 'Unlimited Humming Voice', '', NULL),
  (2516, 'WM_SEVERE_RAINSTORM_MELEE', 'Severe Rainstorm Melee', '', NULL),
  (2443, 'SO_FIREWALK', 'Fire Walk', '', NULL),
  (2444, 'SO_ELECTRICWALK', 'Electric Walk', '', NULL),
  (2445, 'SO_SPELLFIST', 'Spell Fist', '', NULL),
  (2446, 'SO_EARTHGRAVE', 'Earth Grave', '', NULL),
  (2447, 'SO_DIAMONDDUST', 'Diamond Dust', '', NULL),
  (2448, 'SO_POISON_BUSTER', 'Poison Buster', '', NULL),
  (2449, 'SO_PSYCHIC_WAVE', 'Psychic Wave', '', NULL),
  (2450, 'SO_CLOUD_KILL', 'Cloud Kill', '', NULL),
  (2451, 'SO_STRIKING', 'Striking', '', NULL),
  (2452, 'SO_WARMER', 'Warmer', '', NULL),
  (2453, 'SO_VACUUM_EXTREME', 'Vacuum Extreme', '', NULL),
  (2454, 'SO_VARETYR_SPEAR', 'Varetyr Spear', '', NULL),
  (2455, 'SO_ARRULLO', 'Arrullo', '', NULL),
  (2456, 'SO_EL_CONTROL', 'Spirit Control', '', NULL),
  (2457, 'SO_SUMMON_AGNI', 'Summon Fire Spirit Agni', '', NULL),
  (2458, 'SO_SUMMON_AQUA', 'Summon Water Spirit Aqua', '', NULL),
  (2459, 'SO_SUMMON_VENTUS', 'Summon Wind Spirit Ventus', '', NULL),
  (2460, 'SO_SUMMON_TERA', 'Summon Earth Spirit Tera', '', NULL),
  (2461, 'SO_EL_ACTION', 'Elemental Action', '', NULL),
  (2462, 'SO_EL_ANALYSIS', 'Four Spirit Analysis', '', NULL),
  (2463, 'SO_EL_SYMPATHY', 'Spirit Sympathy', '', NULL),
  (2464, 'SO_EL_CURE', 'Spirit Recovery', '', NULL),
  (2465, 'SO_FIRE_INSIGNIA', 'Fire Insignia', '', NULL),
  (2466, 'SO_WATER_INSIGNIA', 'Water Insignia', '', NULL),
  (2467, 'SO_WIND_INSIGNIA', 'Wind Insignia', '', NULL),
  (2468, 'SO_EARTH_INSIGNIA', 'Earth Insignia', '', NULL),
  (2474, 'GN_TRAINING_SWORD', 'Sword Training', '', NULL),
  (2475, 'GN_REMODELING_CART', 'Cart Remodeling', '', NULL),
  (2476, 'GN_CART_TORNADO', 'Cart Tornado', '', NULL),
  (2477, 'GN_CARTCANNON', 'Cart Cannon', '', NULL),
  (2478, 'GN_CARTBOOST', 'Cart Boost', '', NULL),
  (2479, 'GN_THORNS_TRAP', 'Thorn Trap', '', NULL),
  (2480, 'GN_BLOOD_SUCKER', 'Blood Sucker', '', NULL),
  (2481, 'GN_SPORE_EXPLOSION', 'Spore Explosion', '', NULL),
  (2482, 'GN_WALLOFTHORN', 'Wall of Thorns', '', NULL),
  (2483, 'GN_CRAZYWEED', 'Crazy Weed', '', NULL),
  (2484, 'GN_CRAZYWEED_ATK', 'Crazy Weed Attack', '', NULL),
  (2485, 'GN_DEMONIC_FIRE', 'Demonic Fire', '', NULL),
  (2486, 'GN_FIRE_EXPANSION', 'Fire Expansion', '', NULL),
  (2487, 'GN_FIRE_EXPANSION_SMOKE_POWDER', 'Fire Expansion Smoke Powder', '', NULL),
  (2488, 'GN_FIRE_EXPANSION_TEAR_GAS', 'Fire Expansion Tear Gas', '', NULL),
  (2489, 'GN_FIRE_EXPANSION_ACID', 'Fire Expansion Acid', '', NULL),
  (2490, 'GN_HELLS_PLANT', 'Hell''s Plant', '', NULL),
  (2491, 'GN_HELLS_PLANT_ATK', 'Hell''s Plant Attack', '', NULL),
  (2492, 'GN_MANDRAGORA', 'Howling of Mandragora', '', NULL),
  (2493, 'GN_SLINGITEM', 'Sling Item', '', NULL),
  (2494, 'GN_CHANGEMATERIAL', 'Change Material', '', NULL),
  (2495, 'GN_MIX_COOKING', 'Mix Cooking', '', NULL),
  (2496, 'GN_MAKEBOMB', 'Create Bomb', '', NULL),
  (2497, 'GN_S_PHARMACY', 'Special Pharmacy', '', NULL),
  (2498, 'GN_SLINGITEM_RANGEMELEEATK', 'Sling Item Attack', '', NULL),
  (2533, 'ALL_ODINS_RECALL', 'Odin''s Recall', '', NULL),
  (2534, 'RETURN_TO_ELDICASTES', 'Return To Eldicastes', '', NULL),
  (2535, 'ALL_BUYING_STORE', 'Open Buying Store', '', NULL),
  (2536, 'ALL_GUARDIAN_RECALL', 'Guardian''s Recall', '', NULL),
  (2537, 'ALL_ODINS_POWER', 'Odin''s Power', '', NULL),
  (2543, 'ALL_RAY_OF_PROTECTION', 'Ray of Protection', '', NULL),
  (2544, 'MC_CARTDECORATE', 'Decorate Cart', '', NULL),
  (2552, 'RL_RICHS_COIN', 'Rich''s Coin', '', NULL),
  (2553, 'RL_MASS_SPIRAL', 'Mass Spiral', '', NULL),
  (2554, 'RL_BANISHING_BUSTER', 'Banishing Buster', '', NULL),
  (2555, 'RL_B_TRAP', 'Bind Trap', '', NULL),
  (2556, 'RL_FLICKER', 'Flicker', '', NULL),
  (2557, 'RL_S_STORM', 'Shatter Storm', '', NULL),
  (2558, 'RL_E_CHAIN', 'Eternal Chain', '', NULL),
  (2559, 'RL_QD_SHOT', 'Quick Draw Shot', '', NULL),
  (2560, 'RL_C_MARKER', 'Crimson Marker', '', NULL),
  (2561, 'RL_FIREDANCE', 'Fire Dance', '', NULL),
  (2562, 'RL_H_MINE', 'Howling Mine', '', NULL),
  (2563, 'RL_P_ALTER', 'Platinum Alter', '', NULL),
  (2564, 'RL_FALLEN_ANGEL', 'Fallen Angel', '', NULL),
  (2565, 'RL_R_TRIP', 'Round Trip', '', NULL),
  (2566, 'RL_D_TAIL', 'Dragon Tail', '', NULL),
  (2567, 'RL_FIRE_RAIN', 'Fire Rain', '', NULL),
  (2568, 'RL_HEAT_BARREL', 'Heat Barrel', '', NULL),
  (2569, 'RL_AM_BLAST', 'Anti-Material Blast', '', NULL),
  (2570, 'RL_SLUGSHOT', 'Slug Shot', '', NULL),
  (2571, 'RL_HAMMER_OF_GOD', 'Hammer of God', '', NULL),
  (2572, 'RL_R_TRIP_PLUSATK', 'Round Trip Plus Attack', '', NULL),
  (2574, 'SJ_LIGHTOFMOON', 'Light of Moon', '', NULL),
  (2575, 'SJ_LUNARSTANCE', 'Lunar Stance', '', NULL),
  (2576, 'SJ_FULLMOONKICK', 'Full Moon Kick', '', NULL),
  (2577, 'SJ_LIGHTOFSTAR', 'Light of Star', '', NULL),
  (2578, 'SJ_STARSTANCE', 'Star Stance', '', NULL),
  (2579, 'SJ_NEWMOONKICK', 'New Moon Kick', '', NULL),
  (2580, 'SJ_FLASHKICK', 'Flash Kick', '', NULL),
  (2581, 'SJ_STAREMPEROR', 'Star Emperor Advent', '', NULL),
  (2582, 'SJ_NOVAEXPLOSING', 'Nova Explosion', '', NULL),
  (2583, 'SJ_UNIVERSESTANCE', 'Universe Stance', '', NULL),
  (2584, 'SJ_FALLINGSTAR', 'Falling Star', '', NULL),
  (2585, 'SJ_GRAVITYCONTROL', 'Gravity Control', '', NULL),
  (2586, 'SJ_BOOKOFDIMENSION', 'Book of Dimension', '', NULL),
  (2587, 'SJ_BOOKOFCREATINGSTAR', 'Book of Creating Star', '', NULL),
  (2588, 'SJ_DOCUMENT', 'Document of Sun Moon and Star', '', NULL),
  (2589, 'SJ_PURIFY', 'Purification of Sun Moon and Star', '', NULL),
  (2590, 'SJ_LIGHTOFSUN', 'Light of Sun', '', NULL),
  (2591, 'SJ_SUNSTANCE', 'Sun Stance', '', NULL),
  (2592, 'SJ_SOLARBURST', 'Solar Burst', '', NULL),
  (2593, 'SJ_PROMINENCEKICK', 'Prominence Kick', '', NULL),
  (2594, 'SJ_FALLINGSTAR_ATK', 'Falling Star Attack', '', NULL),
  (2595, 'SJ_FALLINGSTAR_ATK2', 'Falling Star Attack 2', '', NULL),
  (2596, 'SP_SOULGOLEM', 'Golem''s Soul', '', NULL),
  (2597, 'SP_SOULSHADOW', 'Shadow''s Soul', '', NULL),
  (2598, 'SP_SOULFALCON', 'Falcon''s Soul', '', NULL),
  (2599, 'SP_SOULFAIRY', 'Fairy''s Soul', '', NULL),
  (2600, 'SP_CURSEEXPLOSION', 'Curse Explosion', '', NULL),
  (2601, 'SP_SOULCURSE', 'Soul Curse', '', NULL),
  (2602, 'SP_SPA', 'Espa', '', NULL),
  (2603, 'SP_SHA', 'Esha', '', NULL),
  (2604, 'SP_SWHOO', 'Eswhoo', '', NULL),
  (2605, 'SP_SOULUNITY', 'Soul Unity', '', NULL),
  (2606, 'SP_SOULDIVISION', 'Soul Division', '', NULL),
  (2607, 'SP_SOULREAPER', 'Soul Reaper', '', NULL),
  (2608, 'SP_SOULREVOLVE', 'Soul Revolution', '', NULL),
  (2609, 'SP_SOULCOLLECT', 'Soul Collect', '', NULL),
  (2610, 'SP_SOULEXPLOSION', 'Soul Explosion', '', NULL),
  (2611, 'SP_SOULENERGY', 'Soul Energy Research', '', NULL),
  (2612, 'SP_KAUTE', 'Kaute', '', NULL),
  (3001, 'KO_YAMIKUMO', 'Shadow Hiding', '', NULL),
  (3002, 'KO_RIGHT', 'Right Hand Mastery', '', NULL),
  (3003, 'KO_LEFT', 'Left Hand Mastery', '', NULL),
  (3004, 'KO_JYUMONJIKIRI', 'Cross Slash', '', NULL),
  (3005, 'KO_SETSUDAN', 'Soul Cutter', '', NULL),
  (3006, 'KO_BAKURETSU', 'Kunai Explosion', '', NULL),
  (3007, 'KO_HAPPOKUNAI', 'Kunai Splash', '', NULL),
  (3008, 'KO_MUCHANAGE', 'Rapid Throw', '', NULL),
  (3009, 'KO_HUUMARANKA', 'Swirling Petal', '', NULL),
  (3010, 'KO_MAKIBISHI', 'Makibishi', '', NULL),
  (3011, 'KO_MEIKYOUSISUI', 'Pure Soul', '', NULL),
  (3012, 'KO_ZANZOU', 'Illusion - Shadow', '', NULL),
  (3013, 'KO_KYOUGAKU', 'Illusion - Shock', '', NULL),
  (3014, 'KO_JYUSATSU', 'Illusion - Death', '', NULL),
  (3015, 'KO_KAHU_ENTEN', 'Fire Charm', '', NULL),
  (3016, 'KO_HYOUHU_HUBUKI', 'Ice Charm', '', NULL),
  (3017, 'KO_KAZEHU_SEIRAN', 'Wind Charm', '', NULL),
  (3018, 'KO_DOHU_KOUKAI', 'Earth Charm', '', NULL),
  (3019, 'KO_KAIHOU', 'Release Ninja Spell', '', NULL),
  (3020, 'KO_ZENKAI', 'Cast Ninja Spell', '', NULL),
  (3021, 'KO_GENWAKU', 'Illusion - Bewitch', '', NULL),
  (3022, 'KO_IZAYOI', '16th Night', '', NULL),
  (3023, 'KG_KAGEHUMI', 'Shadow Trampling', '', NULL),
  (3024, 'KG_KYOMU', 'Empty Shadow', '', NULL),
  (3025, 'KG_KAGEMUSYA', 'Shadow Warrior', '', NULL),
  (3026, 'OB_ZANGETSU', 'Distorted Crescent', '', NULL),
  (3027, 'OB_OBOROGENSOU', 'Moonlight Fantasy', '', NULL),
  (3028, 'OB_OBOROGENSOU_TRANSITION_ATK', 'Moonlight Fantasy Transition Attack', '', NULL),
  (3029, 'OB_AKAITSUKI', 'Ominous Moonlight', '', NULL),
  (3031, 'ECL_SNOWFLIP', 'Snow Flip', '', NULL),
  (3032, 'ECL_PEONYMAMY', 'Peony Mamy', '', NULL),
  (3033, 'ECL_SADAGUI', 'Sadagui', '', NULL),
  (3034, 'ECL_SEQUOIADUST', 'Sequoia Dust', '', NULL),
  (3035, 'ECLAGE_RECALL', 'Return To Eclage', '', NULL),
  (3041, 'ALL_NIFLHEIM_RECALL', 'Niflheim Recall', '', NULL),
  (3042, 'ALL_PRONTERA_RECALL', 'Prontera Recall', '', NULL),
  (3043, 'ALL_GLASTHEIM_RECALL', 'Return To Glast Heim', '', NULL),
  (3044, 'ALL_THANATOS_RECALL', 'Return To Thanatos', '', NULL),
  (3045, 'ALL_LIGHTHALZEN_RECALL', 'Return To Lighthalzen', '', NULL),
  (5001, 'GC_DARKCROW', 'Dark Claw', '', NULL),
  (5002, 'RA_UNLIMIT', 'Unlimited', '', NULL),
  (5003, 'GN_ILLUSIONDOPING', 'Illusion Doping', '', NULL),
  (5004, 'RK_DRAGONBREATH_WATER', 'Dragon Breath - Water', '', NULL),
  (5005, 'RK_LUXANIMA', 'Lux Anima', '', NULL),
  (5006, 'NC_MAGMA_ERUPTION', 'Magma Eruption', '', NULL),
  (5007, 'WM_FRIGG_SONG', 'Frigg''s Song', '', NULL),
  (5008, 'SO_ELEMENTAL_SHIELD', 'Elemental Shield', '', NULL),
  (5009, 'SR_FLASHCOMBO', 'Flash Combo', '', NULL),
  (5010, 'SC_ESCAPE', 'Emergency Escape', '', NULL),
  (5011, 'AB_OFFERTORIUM', 'Offertorium', '', NULL),
  (5012, 'WL_TELEKINESIS_INTENSE', 'Intense Telekinesis', '', NULL),
  (5013, 'LG_KINGS_GRACE', 'King''s Grace', '', NULL),
  (5014, 'ALL_FULL_THROTTLE', 'Full Throttle', '', NULL),
  (5015, 'NC_MAGMA_ERUPTION_DOTDAMAGE', 'Magma Eruption Dot Damage', '', NULL),
  (5018, 'SU_BASIC_SKILL', 'New Basic Skill', '', NULL),
  (5019, 'SU_BITE', 'Bite', '', NULL),
  (5020, 'SU_HIDE', 'Hide', '', NULL),
  (5021, 'SU_SCRATCH', 'Scratch', '', NULL),
  (5022, 'SU_STOOP', 'Stoop', '', NULL),
  (5023, 'SU_LOPE', 'Lope', '', NULL),
  (5024, 'SU_SPRITEMABLE', 'Spirit Marble', '', NULL),
  (5025, 'SU_POWEROFLAND', 'Power of Land', '', NULL),
  (5026, 'SU_SV_STEMSPEAR', 'Silvervine Stem Spear', '', NULL),
  (5027, 'SU_CN_POWDERING', 'Catnip Powdering', '', NULL),
  (5028, 'SU_CN_METEOR', 'Catnip Meteor', '', NULL),
  (5029, 'SU_SV_ROOTTWIST', 'Silvervine Root Twist', '', NULL),
  (5030, 'SU_SV_ROOTTWIST_ATK', 'Silver Vine Root Twist Attack', '', NULL),
  (5031, 'SU_POWEROFLIFE', 'Power of Life', '', NULL),
  (5032, 'SU_SCAROFTAROU', 'Scar of Tarou', '', NULL),
  (5033, 'SU_PICKYPECK', 'Picky Peck', '', NULL),
  (5034, 'SU_PICKYPECK_DOUBLE_ATK', 'Picky Peck Double Attack', '', NULL),
  (5035, 'SU_ARCLOUSEDASH', 'Arclouse Dash', '', NULL),
  (5036, 'SU_LUNATICCARROTBEAT', 'Lunatic Carrot Beat', '', NULL),
  (5037, 'SU_POWEROFSEA', 'Power of Sea', '', NULL),
  (5038, 'SU_TUNABELLY', 'Tuna Belly', '', NULL),
  (5039, 'SU_TUNAPARTY', 'Tuna Party', '', NULL),
  (5040, 'SU_BUNCHOFSHRIMP', 'Bunch of Shrimp', '', NULL),
  (5041, 'SU_FRESHSHRIMP', 'Fresh Shrimp', '', NULL),
  (5042, 'SU_CN_METEOR2', 'Catnip Meteor 2', '', NULL),
  (5043, 'SU_LUNATICCARROTBEAT2', 'Lunatic Carrot Beat 2', '', NULL),
  (5044, 'SU_SOULATTACK', 'Soul Attack', '', NULL),
  (5045, 'SU_POWEROFFLOCK', 'Power of Flock', '', NULL),
  (5046, 'SU_SVG_SPIRIT', 'Spirit of Savage', '', NULL),
  (5047, 'SU_HISS', 'Hiss', '', NULL),
  (5048, 'SU_NYANGGRASS', 'Nyang Grass', '', NULL),
  (5049, 'SU_GROOMING', 'Grooming', '', NULL),
  (5050, 'SU_PURRING', 'Purring', '', NULL),
  (5051, 'SU_SHRIMPARTY', 'Tasty Shrimp Party', '', NULL),
  (5052, 'SU_SPIRITOFLIFE', 'Spirit of Life', '', NULL),
  (5053, 'SU_MEOWMEOW', 'Meow Meow', '', NULL),
  (5054, 'SU_SPIRITOFLAND', 'Spirit of Land', '', NULL),
  (5055, 'SU_CHATTERING', 'Chattering', '', NULL),
  (5056, 'SU_SPIRITOFSEA', 'Spirit of Sea', '', NULL),
  (5063, 'WE_CALLALLFAMILY', 'Call All Family', '', NULL),
  (5064, 'WE_ONEFOREVER', 'One Forever', '', NULL),
  (5065, 'WE_CHEERUP', 'Cheer Up', '', NULL),
  (5067, 'ALL_EQSWITCH', 'Equip Switch', '', NULL),
  (5068, 'CG_SPECIALSINGER', 'Skilled Special Singer', '', NULL),
  (5072, 'AB_VITUPERATUM', 'Vituperatum', '', NULL),
  (5073, 'AB_CONVENIO', 'Convenio', '', NULL),
  (5075, 'NV_BREAKTHROUGH', 'Break Through', '', NULL),
  (5076, 'NV_HELPANGEL', 'Help Angel', '', NULL),
  (5077, 'NV_TRANSCENDENCE', 'Transcendence', '', NULL),
  (5078, 'WL_READING_SB_READING', 'Reading Spellbook', '', NULL),
  (5201, 'DK_SERVANTWEAPON', 'Servant Weapon', '', NULL),
  (5202, 'DK_SERVANTWEAPON_ATK', 'Servant Weapon Attack', '', NULL),
  (5203, 'DK_SERVANT_W_SIGN', 'Servant Weapon Sign', '', NULL),
  (5204, 'DK_SERVANT_W_PHANTOM', 'Servant Weapon Phantom', '', NULL),
  (5205, 'DK_SERVANT_W_DEMOL', 'Servant Weapon Demolition', '', NULL),
  (5206, 'DK_CHARGINGPIERCE', 'Charging Pierce', '', NULL),
  (5207, 'DK_TWOHANDDEF', 'Two Hand Def', '', NULL),
  (5208, 'DK_HACKANDSLASHER', 'Hack And Slasher', '', NULL),
  (5209, 'DK_HACKANDSLASHER_ATK', 'Hack And Slasher Attack', '', NULL),
  (5210, 'DK_DRAGONIC_AURA', 'Dragonic Aura', '', NULL),
  (5211, 'DK_MADNESS_CRUSHER', 'Madness Crusher', '', NULL),
  (5212, 'DK_VIGOR', 'Vigor', '', NULL),
  (5213, 'DK_STORMSLASH', 'Storm Slash', '', NULL),
  (5214, 'AG_DEADLY_PROJECTION', 'Deadly Projection', '', NULL),
  (5215, 'AG_DESTRUCTIVE_HURRICANE', 'Destructive Hurricane', '', NULL),
  (5216, 'AG_RAIN_OF_CRYSTAL', 'Rain Of Crystal', '', NULL),
  (5217, 'AG_MYSTERY_ILLUSION', 'Mystery Illusion', '', NULL),
  (5218, 'AG_VIOLENT_QUAKE', 'Violent Quake', '', NULL),
  (5219, 'AG_VIOLENT_QUAKE_ATK', 'Violent Quake Attack', '', NULL),
  (5220, 'AG_SOUL_VC_STRIKE', 'Soul Vulcan Strike', '', NULL),
  (5221, 'AG_STRANTUM_TREMOR', 'Strantum Tremor', '', NULL),
  (5222, 'AG_ALL_BLOOM', 'All Bloom', '', NULL),
  (5223, 'AG_ALL_BLOOM_ATK', 'All Bloom Attack', '', NULL),
  (5224, 'AG_ALL_BLOOM_ATK2', 'All Bloom Attack 2', '', NULL),
  (5225, 'AG_CRYSTAL_IMPACT', 'Crystal Impact', '', NULL),
  (5226, 'AG_CRYSTAL_IMPACT_ATK', 'Crystal Impact Attack', '', NULL),
  (5227, 'AG_TORNADO_STORM', 'Tornado Storm', '', NULL),
  (5228, 'AG_TWOHANDSTAFF', 'Two Hand Staff Mastery', '', NULL),
  (5229, 'AG_FLORAL_FLARE_ROAD', 'Floral Flare Road', '', NULL),
  (5230, 'AG_ASTRAL_STRIKE', 'Astral Strike', '', NULL),
  (5231, 'AG_ASTRAL_STRIKE_ATK', 'Astral Strike Attack', '', NULL),
  (5232, 'AG_CLIMAX', 'Climax', '', NULL),
  (5233, 'AG_ROCK_DOWN', 'Rock Down', '', NULL),
  (5234, 'AG_STORM_CANNON', 'Storm Cannon', '', NULL),
  (5235, 'AG_CRIMSON_ARROW', 'Crimson Arrow', '', NULL),
  (5236, 'AG_CRIMSON_ARROW_ATK', 'Crimson Arrow Attack', '', NULL),
  (5237, 'AG_FROZEN_SLASH', 'Frozen Slash', '', NULL),
  (5238, 'IQ_POWERFUL_FAITH', 'Powerful Faith', '', NULL),
  (5239, 'IQ_FIRM_FAITH', 'Firm Faith', '', NULL),
  (5240, 'IQ_WILL_OF_FAITH', 'Will Of Faith', '', NULL),
  (5241, 'IQ_OLEUM_SANCTUM', 'Oleum Sanctum', '', NULL),
  (5242, 'IQ_SINCERE_FAITH', 'Sincere Faith', '', NULL),
  (5243, 'IQ_MASSIVE_F_BLASTER', 'Massive Flame Blaster', '', NULL),
  (5244, 'IQ_EXPOSION_BLASTER', 'Explosion Blaster', '', NULL),
  (5245, 'IQ_FIRST_BRAND', 'First Brand', '', NULL),
  (5246, 'IQ_FIRST_FAITH_POWER', 'First Faith Power', '', NULL),
  (5247, 'IQ_JUDGE', 'Judge', '', NULL),
  (5248, 'IQ_SECOND_FLAME', 'Second Flame', '', NULL),
  (5249, 'IQ_SECOND_FAITH', 'Second Faith', '', NULL),
  (5250, 'IQ_SECOND_JUDGEMENT', 'Second Judgement', '', NULL),
  (5251, 'IQ_THIRD_PUNISH', 'Third Punish', '', NULL),
  (5252, 'IQ_THIRD_FLAME_BOMB', 'Third Flame Bomb', '', NULL),
  (5253, 'IQ_THIRD_CONSECRATION', 'Third Consecration', '', NULL),
  (5254, 'IQ_THIRD_EXOR_FLAME', 'Third Exorcism Flame', '', NULL),
  (5255, 'IG_GUARD_STANCE', 'Guard Stance', '', NULL),
  (5256, 'IG_GUARDIAN_SHIELD', 'Guardian Shield', '', NULL),
  (5257, 'IG_REBOUND_SHIELD', 'Rebound Shield', '', NULL),
  (5258, 'IG_SHIELD_MASTERY', 'Shield Mastery', '', NULL),
  (5259, 'IG_SPEAR_SWORD_M', 'Spear And Sword Mastery', '', NULL),
  (5260, 'IG_ATTACK_STANCE', 'Attack Stance', '', NULL),
  (5261, 'IG_ULTIMATE_SACRIFICE', 'Ultimate Sacrifice', '', NULL),
  (5262, 'IG_HOLY_SHIELD', 'Holy Shield', '', NULL),
  (5263, 'IG_GRAND_JUDGEMENT', 'Grand Judgement', '', NULL),
  (5264, 'IG_JUDGEMENT_CROSS', 'Judgement Cross', '', NULL),
  (5265, 'IG_SHIELD_SHOOTING', 'Shield Shooting', '', NULL),
  (5266, 'IG_OVERSLASH', 'Overslash', '', NULL),
  (5267, 'IG_CROSS_RAIN', 'Cross Rain', '', NULL),
  (5268, 'CD_REPARATIO', 'Reparatio', '', NULL),
  (5269, 'CD_MEDIALE_VOTUM', 'Mediale Votum', '', NULL),
  (5270, 'CD_MACE_BOOK_M', 'Mace Book Mastery', '', NULL),
  (5271, 'CD_ARGUTUS_VITA', 'Argutus Vita', '', NULL),
  (5272, 'CD_ARGUTUS_TELUM', 'Argutus Telum', '', NULL),
  (5273, 'CD_ARBITRIUM', 'Arbitrium', '', NULL),
  (5274, 'CD_ARBITRIUM_ATK', 'Arbitrium Attack', '', NULL),
  (5275, 'CD_PRESENS_ACIES', 'Presens Acies', '', NULL),
  (5276, 'CD_FIDUS_ANIMUS', 'Fidus Animus', '', NULL),
  (5277, 'CD_EFFLIGO', 'Effligo', '', NULL),
  (5278, 'CD_COMPETENTIA', 'Competentia', '', NULL),
  (5279, 'CD_PNEUMATICUS_PROCELLA', 'Pneumaticus Procella', '', NULL),
  (5280, 'CD_DILECTIO_HEAL', 'Dilectio Heal', '', NULL),
  (5281, 'CD_RELIGIO', 'Religio', '', NULL),
  (5282, 'CD_BENEDICTUM', 'Benedictum', '', NULL),
  (5283, 'CD_PETITIO', 'Petitio', '', NULL),
  (5284, 'CD_FRAMEN', 'Framen', '', NULL),
  (5285, 'SHC_SHADOW_EXCEED', 'Shadow Exceed', '', NULL),
  (5286, 'SHC_DANCING_KNIFE', 'Dancing Knife', '', NULL),
  (5287, 'SHC_SAVAGE_IMPACT', 'Savage Impact', '', NULL),
  (5288, 'SHC_SHADOW_SENSE', 'Shadow Sense', '', NULL),
  (5289, 'SHC_ETERNAL_SLASH', 'Eternal Slash', '', NULL),
  (5290, 'SHC_POTENT_VENOM', 'Potent Venom', '', NULL),
  (5291, 'SHC_SHADOW_STAB', 'Shadow Stab', '', NULL),
  (5292, 'SHC_IMPACT_CRATER', 'Impact Crater', '', NULL),
  (5293, 'SHC_ENCHANTING_SHADOW', 'Enchanting Shadow', '', NULL),
  (5294, 'SHC_FATAL_SHADOW_CROW', 'Fatal Shadow Crow', '', NULL),
  (5295, 'MT_AXE_STOMP', 'Axe Stomp', '', NULL),
  (5296, 'MT_RUSH_QUAKE', 'Rush Quake', '', NULL),
  (5297, 'MT_M_MACHINE', 'Manufacture Machine', '', NULL),
  (5298, 'MT_A_MACHINE', 'Attack Machine', '', NULL),
  (5299, 'MT_D_MACHINE', 'Defense Machine', '', NULL),
  (5300, 'MT_TWOAXEDEF', 'Two Hand Axe Def', '', NULL),
  (5301, 'MT_ABR_M', 'ABR Mastery', '', NULL),
  (5302, 'MT_SUMMON_ABR_BATTLE_WARIOR', 'ABR Battle Warior', '', NULL),
  (5303, 'MT_SUMMON_ABR_DUAL_CANNON', 'ABR Dual Cannon', '', NULL),
  (5304, 'MT_SUMMON_ABR_MOTHER_NET', 'ABR Mother Net', '', NULL),
  (5305, 'MT_SUMMON_ABR_INFINITY', 'ABR Infinity', '', NULL),
  (5306, 'AG_DESTRUCTIVE_HURRICANE_CLIMAX', 'Destructive Hurricane Climax', '', NULL),
  (5307, 'BO_ACIDIFIED_ZONE_WATER_ATK', 'Actified Zone Water Attack', '', NULL),
  (5308, 'BO_ACIDIFIED_ZONE_GROUND_ATK', 'Actified Zone Ground Attack', '', NULL),
  (5309, 'BO_ACIDIFIED_ZONE_WIND_ATK', 'Actified Zone Wind Attack', '', NULL),
  (5310, 'BO_ACIDIFIED_ZONE_FIRE_ATK', 'Actified Zone Fire Attack', '', NULL),
  (5311, 'ABC_DAGGER_AND_BOW_M', 'Dagger And Bow Mastery', '', NULL),
  (5312, 'ABC_MAGIC_SWORD_M', 'Magic Sword Mastery', '', NULL),
  (5313, 'ABC_STRIP_SHADOW', 'Strip Shadow', '', NULL),
  (5314, 'ABC_ABYSS_DAGGER', 'Abyss Dagger', '', NULL),
  (5315, 'ABC_UNLUCKY_RUSH', 'Unlucky Rush', '', NULL),
  (5316, 'ABC_CHAIN_REACTION_SHOT', 'Chain Reaction Shot', '', NULL),
  (5317, 'ABC_FROM_THE_ABYSS', 'From The Abyss', '', NULL),
  (5318, 'ABC_ABYSS_SLAYER', 'Abyss Slayer', '', NULL),
  (5319, 'ABC_ABYSS_STRIKE', 'Omega Abyss Strike', '', NULL),
  (5320, 'ABC_DEFT_STAB', 'Deft Stab', '', NULL),
  (5321, 'ABC_ABYSS_SQUARE', 'Abyss Square', '', NULL),
  (5322, 'ABC_FRENZY_SHOT', 'Frenzy Shot', '', NULL),
  (5323, 'WH_ADVANCED_TRAP', 'Advanced Trap', '', NULL),
  (5324, 'WH_WIND_SIGN', 'Wind Sign', '', NULL),
  (5325, 'WH_NATUREFRIENDLY', 'Nature Friendly', '', NULL),
  (5326, 'WH_HAWKRUSH', 'Hawk Rush', '', NULL),
  (5327, 'WH_HAWK_M', 'Hawk Mastery', '', NULL),
  (5328, 'WH_CALAMITYGALE', 'Calamity Gale', '', NULL),
  (5329, 'WH_HAWKBOOMERANG', 'Hawk Boomerang', '', NULL),
  (5330, 'WH_GALESTORM', 'Gale Storm', '', NULL),
  (5331, 'WH_DEEPBLINDTRAP', 'Deep Blind Trap', '', NULL),
  (5332, 'WH_SOLIDTRAP', 'Solid Trap', '', NULL),
  (5333, 'WH_SWIFTTRAP', 'Swift Trap', '', NULL),
  (5334, 'WH_CRESCIVE_BOLT', 'Crescive Bolt', '', NULL),
  (5335, 'WH_FLAMETRAP', 'Flame Trap', '', NULL),
  (5336, 'BO_BIONIC_PHARMACY', 'Bionic Pharmacy', '', NULL),
  (5337, 'BO_BIONICS_M', 'Bionics Mastery', '', NULL),
  (5338, 'BO_THE_WHOLE_PROTECTION', 'The Whole Protection', '', NULL),
  (5339, 'BO_ADVANCE_PROTECTION', 'Advance Protection', '', NULL),
  (5340, 'BO_ACIDIFIED_ZONE_WATER', 'Acidified Zone Water', '', NULL),
  (5341, 'BO_ACIDIFIED_ZONE_GROUND', 'Acidified Zone Ground', '', NULL),
  (5342, 'BO_ACIDIFIED_ZONE_WIND', 'Acidified Zone Wind', '', NULL),
  (5343, 'BO_ACIDIFIED_ZONE_FIRE', 'Acidified Zone Fire', '', NULL),
  (5344, 'BO_WOODENWARRIOR', 'Wooden Warrior', '', NULL),
  (5345, 'BO_WOODEN_FAIRY', 'Wooden Fairy', '', NULL),
  (5346, 'BO_CREEPER', 'Creeper', '', NULL),
  (5347, 'BO_RESEARCHREPORT', 'Research Report', '', NULL),
  (5348, 'BO_HELLTREE', 'Hell Tree', '', NULL),
  (5349, 'TR_STAGE_MANNER', 'Stage Manner', '', NULL),
  (5350, 'TR_RETROSPECTION', 'Retrospection', '', NULL),
  (5351, 'TR_MYSTIC_SYMPHONY', 'Mystic Symphony', '', NULL),
  (5352, 'TR_KVASIR_SONATA', 'Kvasir Sonata', '', NULL),
  (5353, 'TR_ROSEBLOSSOM', 'Rose Blossom', '', NULL),
  (5354, 'TR_ROSEBLOSSOM_ATK', 'Rose Blossom Attack', '', NULL),
  (5355, 'TR_RHYTHMSHOOTING', 'Rhythm Shooting', '', NULL),
  (5356, 'TR_METALIC_FURY', 'Metallic Fury', '', NULL),
  (5357, 'TR_SOUNDBLEND', 'Sound Blend', '', NULL),
  (5358, 'TR_GEF_NOCTURN', 'Geffenia Nocturn', '', NULL),
  (5359, 'TR_ROKI_CAPRICCIO', 'Roki Capriccio', '', NULL),
  (5360, 'TR_AIN_RHAPSODY', 'Ain Rhapsody', '', NULL),
  (5361, 'TR_MUSICAL_INTERLUDE', 'Musical Interlude', '', NULL),
  (5362, 'TR_JAWAII_SERENADE', 'Jawaii Serenade', '', NULL),
  (5363, 'TR_NIPELHEIM_REQUIEM', 'Nipelheim Requiem', '', NULL),
  (5364, 'TR_PRON_MARCH', 'Pron March', '', NULL),
  (5365, 'EM_MAGIC_BOOK_M', 'Magic Book Mastery', '', NULL),
  (5366, 'EM_SPELL_ENCHANTING', 'Spell Enchanting', '', NULL),
  (5367, 'EM_ACTIVITY_BURN', 'Activity Burn', '', NULL),
  (5368, 'EM_INCREASING_ACTIVITY', 'Increasing Activity', '', NULL),
  (5369, 'EM_DIAMOND_STORM', 'Diamond Storm', '', NULL),
  (5370, 'EM_LIGHTNING_LAND', 'Lightning Land', '', NULL),
  (5371, 'EM_VENOM_SWAMP', 'Venom Swamp', '', NULL),
  (5372, 'EM_CONFLAGRATION', 'Conflagration', '', NULL),
  (5373, 'EM_TERRA_DRIVE', 'Terra Drive', '', NULL),
  (5374, 'EM_ELEMENTAL_SPIRIT_M', 'Elemental Spirit Mastery', '', NULL),
  (5375, 'EM_SUMMON_ELEMENTAL_ARDOR', 'Summon Elemental Ardor', '', NULL),
  (5376, 'EM_SUMMON_ELEMENTAL_DILUVIO', 'Summon Elemental Diluvio', '', NULL),
  (5377, 'EM_SUMMON_ELEMENTAL_PROCELLA', 'Summon Elemental Procella', '', NULL),
  (5378, 'EM_SUMMON_ELEMENTAL_TERREMOTUS', 'Summon Elemental Terremotus', '', NULL),
  (5379, 'EM_SUMMON_ELEMENTAL_SERPENS', 'Summon Elemental Serpens', '', NULL),
  (5380, 'EM_ELEMENTAL_BUSTER', 'Elemental Buster', '', NULL),
  (5381, 'EM_ELEMENTAL_VEIL', 'Elemental Veil', '', NULL),
  (5382, 'ABC_CHAIN_REACTION_SHOT_ATK', 'Chain Reaction Shot Attack', '', NULL),
  (5383, 'ABC_FROM_THE_ABYSS_ATK', 'From The Abyss Attack', '', NULL),
  (5384, 'BO_WOODEN_THROWROCK', 'Wooden Throw Rock', '', NULL),
  (5385, 'BO_WOODEN_ATTACK', 'Wooden Attack', '', NULL),
  (5386, 'BO_HELL_HOWLING', 'Hell Howling', '', NULL),
  (5387, 'BO_HELL_DUSTY', 'Hell Dusty', '', NULL),
  (5388, 'BO_FAIRY_DUSTY', 'Fairy Dusty', '', NULL),
  (5389, 'EM_ELEMENTAL_BUSTER_FIRE', 'Elemental Buster Fire', '', NULL),
  (5390, 'EM_ELEMENTAL_BUSTER_WATER', 'Elemental Buster Water', '', NULL),
  (5391, 'EM_ELEMENTAL_BUSTER_WIND', 'Elemental Buster Wind', '', NULL),
  (5392, 'EM_ELEMENTAL_BUSTER_GROUND', 'Elemental Buster Ground', '', NULL),
  (5393, 'EM_ELEMENTAL_BUSTER_POISON', 'Elemental Buster Poison', '', NULL),
  (5433, 'SH_MYSTICAL_CREATURE_MASTERY', 'Mystical Creature Mastery', '', NULL),
  (5434, 'SH_COMMUNE_WITH_CHUL_HO', 'Commune with Chulho', '', NULL),
  (5435, 'SH_CHUL_HO_SONIC_CLAW', 'Chulho Sonic Claw', '', NULL),
  (5436, 'SH_HOWLING_OF_CHUL_HO', 'Howling of Chulho', '', NULL),
  (5437, 'SH_HOGOGONG_STRIKE', 'Hogogong Strike', '', NULL),
  (5438, 'SH_COMMUNE_WITH_KI_SUL', 'Commune with Kisul', '', NULL),
  (5439, 'SH_KI_SUL_WATER_SPRAYING', 'Kisul Water Spraying', '', NULL),
  (5440, 'SH_MARINE_FESTIVAL_OF_KI_SUL', 'Marine Festival of Kisul', '', NULL),
  (5441, 'SH_SANDY_FESTIVAL_OF_KI_SUL', 'Sandy Festival of Kisul', '', NULL),
  (5442, 'SH_KI_SUL_RAMPAGE', 'Kisul Rampage', '', NULL),
  (5443, 'SH_COMMUNE_WITH_HYUN_ROK', 'Commune with Hyunrok', '', NULL),
  (5444, 'SH_COLORS_OF_HYUN_ROK', 'Colors of Hyunrok', '', NULL),
  (5445, 'SH_HYUN_ROKS_BREEZE', 'Hyunrok Breeze', '', NULL),
  (5446, 'SH_HYUN_ROK_CANNON', 'Hyunrok Cannon', '', NULL),
  (5447, 'SH_TEMPORARY_COMMUNION', 'Temporary Communion', '', NULL),
  (5448, 'SH_BLESSING_OF_MYSTICAL_CREATURES', 'Blessing of Mystical Creatures', '', NULL),
  (5401, 'NW_P_F_I', 'P.F.I', '', NULL),
  (5402, 'NW_GRENADE_MASTERY', 'Grenade Mastery', '', NULL),
  (5403, 'NW_INTENSIVE_AIM', 'Intensive Aim', '', NULL),
  (5404, 'NW_GRENADE_FRAGMENT', 'Grenade Fragment', '', NULL),
  (5405, 'NW_THE_VIGILANTE_AT_NIGHT', 'The Vigilante at Night', '', NULL),
  (5406, 'NW_ONLY_ONE_BULLET', 'Only One Bullet', '', NULL),
  (5407, 'NW_SPIRAL_SHOOTING', 'Spiral Shooting', '', NULL),
  (5408, 'NW_MAGAZINE_FOR_ONE', 'Magazine for One', '', NULL),
  (5409, 'NW_WILD_FIRE', 'Wild Fire', '', NULL),
  (5410, 'NW_BASIC_GRENADE', 'Basic Grenade', '', NULL),
  (5411, 'NW_HASTY_FIRE_IN_THE_HOLE', 'Hasty Fire in the Hole', '', NULL),
  (5412, 'NW_GRENADES_DROPPING', 'Grenades Dropping', '', NULL),
  (5413, 'NW_AUTO_FIRING_LAUNCHER', 'Auto Firing Launcher', '', NULL),
  (5414, 'NW_HIDDEN_CARD', 'Hidden Card', '', NULL),
  (5415, 'NW_MISSION_BOMBARD', 'Mission Bombard', '', NULL),
  (5416, 'SOA_TALISMAN_MASTERY', 'Talisman Mastery', '', NULL),
  (5417, 'SOA_SOUL_MASTERY', 'Soul Mastery', '', NULL),
  (5418, 'SOA_TALISMAN_OF_PROTECTION', 'Talisman Of Protection', '', NULL),
  (5419, 'SOA_TALISMAN_OF_WARRIOR', 'Talisman Of Warrior', '', NULL),
  (5420, 'SOA_TALISMAN_OF_MAGICIAN', 'Talisman Of Magician', '', NULL),
  (5421, 'SOA_SOUL_GATHERING', 'Soul Gathering', '', NULL),
  (5422, 'SOA_TOTEM_OF_TUTELARY', 'Totem Of Tutelary', '', NULL),
  (5423, 'SOA_TALISMAN_OF_FIVE_ELEMENTS', 'Talisman Of Five Elements', '', NULL),
  (5424, 'SOA_TALISMAN_OF_SOUL_STEALING', 'Talisman Of Soul Stealing', '', NULL),
  (5425, 'SOA_EXORCISM_OF_MALICIOUS_SOUL', 'Exorcism Of Malicious Soul', '', NULL),
  (5426, 'SOA_TALISMAN_OF_BLUE_DRAGON', 'Talisman Of Blue Dragon', '', NULL),
  (5427, 'SOA_TALISMAN_OF_WHITE_TIGER', 'Talisman Of White Tiger', '', NULL),
  (5428, 'SOA_TALISMAN_OF_RED_PHOENIX', 'Talisman Of Red Phoenix', '', NULL),
  (5429, 'SOA_TALISMAN_OF_BLACK_TORTOISE', 'Talisman Of Black Tortoise', '', NULL),
  (5430, 'SOA_TALISMAN_OF_FOUR_BEARING_GOD', 'Talisman Of Four Bearing God', '', NULL),
  (5431, 'SOA_CIRCLE_OF_DIRECTIONS_AND_ELEMENTALS', 'Circle Of Directions And Elementals', '', NULL),
  (5432, 'SOA_SOUL_OF_HEAVEN_AND_EARTH', 'Soul Of Heaven And Earth', '', NULL),
  (5449, 'HN_SELFSTUDY_TATICS', 'Self Study Tactics', '', NULL),
  (5450, 'HN_SELFSTUDY_SOCERY', 'Self Study Sorcery', '', NULL),
  (5451, 'HN_DOUBLEBOWLINGBASH', 'Double Bowling Bash', '', NULL),
  (5452, 'HN_MEGA_SONIC_BLOW', 'Mega Sonic Blow', '', NULL),
  (5453, 'HN_SHIELD_CHAIN_RUSH', 'Shield Chain Rush', '', NULL),
  (5454, 'HN_SPIRAL_PIERCE_MAX', 'Spiral Pierce Max', '', NULL),
  (5455, 'HN_METEOR_STORM_BUSTER', 'Meteor Storm Buster', '', NULL),
  (5456, 'HN_JUPITEL_THUNDER_STORM', 'Jupitel Thunderstorm', '', NULL),
  (5457, 'HN_JACK_FROST_NOVA', 'Jack Frost Nova', '', NULL),
  (5458, 'HN_HELLS_DRIVE', 'Hell''s Drive', '', NULL),
  (5459, 'HN_GROUND_GRAVITATION', 'Ground Gravitation', '', NULL),
  (5460, 'HN_NAPALM_VULCAN_STRIKE', 'Napalm Vulcan Strike', '', NULL),
  (5461, 'HN_BREAKINGLIMIT', 'Breaking Limit', '', NULL),
  (5462, 'HN_RULEBREAK', 'Rule Break', '', NULL),
  (5463, 'SKE_SKY_MASTERY', 'Sky Mastery', '', NULL),
  (5464, 'SKE_WAR_BOOK_MASTERY', 'War Book Mastery', '', NULL),
  (5465, 'SKE_RISING_SUN', 'Rising Sun', '', NULL),
  (5466, 'SKE_NOON_BLAST', 'Noon Blast', '', NULL),
  (5467, 'SKE_SUNSET_BLAST', 'Sunset Blast', '', NULL),
  (5468, 'SKE_RISING_MOON', 'Rising Moon', '', NULL),
  (5469, 'SKE_MIDNIGHT_KICK', 'Midnight Kick', '', NULL),
  (5470, 'SKE_DAWN_BREAK', 'Dawn Break', '', NULL),
  (5471, 'SKE_TWINKLING_GALAXY', 'Twinkling Galaxy', '', NULL),
  (5472, 'SKE_STAR_BURST', 'Star Burst', '', NULL),
  (5473, 'SKE_STAR_CANNON', 'Star Cannon', '', NULL),
  (5474, 'SKE_ALL_IN_THE_SKY', 'All in the Sky', '', NULL),
  (5475, 'SKE_ENCHANTING_SKY', 'Enchanting Sky', '', NULL),
  (5476, 'SS_TOKEDASU', 'Melt Away', '', NULL),
  (5477, 'SS_SHIMIRU', 'Infiltrate', '', NULL),
  (5478, 'SS_AKUMUKESU', 'Nightmare Erasion', '', NULL),
  (5479, 'SS_SHINKIROU', 'Mirage', '', NULL),
  (5480, 'SS_KAGEGARI', 'Shadow Hunting', '', NULL),
  (5481, 'SS_KAGENOMAI', 'Shadow Dance', '', NULL),
  (5482, 'SS_KAGEGISSEN', 'Shadow Flash', '', NULL),
  (5483, 'SS_FUUMASHOUAKU', 'Huuma Shuriken - Grasp', '', NULL),
  (5484, 'SS_FUUMAKOUCHIKU', 'Huuma Shuriken - Construct', '', NULL),
  (5485, 'SS_KUNAIWAIKYOKU', 'Kunai - Distortion', '', NULL),
  (5486, 'SS_KUNAIKAITEN', 'Kunai - Rotation', '', NULL),
  (5487, 'SS_KUNAIKUSSETSU', 'Kunai - Refraction', '', NULL),
  (5488, 'SS_SEKIENHOU', 'Red Flame Cannon', '', NULL),
  (5489, 'SS_REIKETSUHOU', 'Cold Blooded Cannon', '', NULL),
  (5490, 'SS_RAIDENPOU', 'Thundering Cannon', '', NULL),
  (5491, 'SS_KINRYUUHOU', 'Golden Dragon Cannon', '', NULL),
  (5492, 'SS_ANTENPOU', 'Darkening Cannon', '', NULL),
  (5493, 'SS_KAGEAKUMU', 'Shadow - Nightmare', '', NULL),
  (5494, 'SS_HITOUAKUMU', 'Kunai - Nightmare', '', NULL),
  (5495, 'SS_ANKOKURYUUAKUMU', 'Dark Dragon - Nightmare', '', NULL),
  (5496, 'NW_THE_VIGILANTE_AT_NIGHT_GUN_GATLING', 'The Vigilante At Night Gun Gatling', '', NULL),
  (5497, 'NW_THE_VIGILANTE_AT_NIGHT_GUN_SHOTGUN', 'The Vigilante At Night Gun Shotgun', '', NULL),
  (5499, 'SS_FOUR_CHARM', 'Four Colors Charm', '', NULL),
  (5500, 'NW_WILD_SHOT', 'Wild Shot', '', NULL),
  (5501, 'NW_MIDNIGHT_FALLEN', 'Midnight Fallen', '', NULL),
  (5502, 'SKE_SKY_SUN', 'Sky Sun', '', NULL),
  (5503, 'SKE_SKY_MOON', 'Sky Moon', '', NULL),
  (5504, 'SKE_STAR_LIGHT_KICK', 'Star Light Kick', '', NULL),
  (5506, 'SH_CHUL_HO_BATTERING', 'Chulho Battering', '', NULL),
  (5507, 'SH_HYUN_ROK_SPIRIT_POWER', 'Hyunrok Spirit Power', '', NULL),
  (5505, 'HN_OVERCOMING_CRISIS', 'Overcoming Crisis', '', NULL),
  (6001, 'DK_DRAGONIC_BREATH', 'Dragonic Breath', '', NULL),
  (6002, 'MT_SPARK_BLASTER', 'Spark Blaster', '', NULL),
  (6003, 'MT_TRIPLE_LASER', 'Triple Laser', '', NULL),
  (6004, 'MT_MIGHTY_SMASH', 'Mighty Smash', '', NULL),
  (6005, 'BO_EXPLOSIVE_POWDER', 'Explosive Powder', '', NULL),
  (6006, 'BO_MAYHEMIC_THORNS', 'Mayhemic Thorns', '', NULL),
  (6502, 'DK_DRAGONIC_PIERCE', 'Dragonic Pierce', '', NULL),
  (6503, 'IG_RADIANT_SPEAR', 'Radiant Spear', '', NULL),
  (6504, 'IG_IMPERIAL_CROSS', 'Imperial Cross', '', NULL),
  (6505, 'IG_IMPERIAL_PRESSURE', 'Imperial Pressure', '', NULL),
  (6506, 'MT_RUSH_STRIKE', 'Rush Strike', '', NULL),
  (6507, 'MT_POWERFUL_SWING', 'Powerful Swing', '', NULL),
  (6508, 'MT_ENERGY_CANNONADE', 'Energy Cannonade', '', NULL),
  (6509, 'BO_MYSTERY_POWDER', 'Mystery Powder', '', NULL),
  (6510, 'BO_DUST_EXPLOSION', 'Dust Explosion', '', NULL),
  (6512, 'ABC_HIT_AND_SLIDING', 'Hit And Sliding', '', NULL),
  (6513, 'ABC_CHASING_BREAK', 'Chasing Break', '', NULL),
  (6514, 'ABC_CHASING_SHOT', 'Chasing Shot', '', NULL),
  (6516, 'AG_ENERGY_CONVERSION', 'Energy Conversion', '', NULL),
  (6511, 'SHC_CROSS_SLASH', 'Cross Slash', '', NULL),
  (6515, 'ABC_ABYSS_FLAME', 'Abyss Flame', '', NULL),
  (6517, 'EM_PSYCHIC_STREAM', 'Psychic Stream', '', NULL),
  (6518, 'CD_DIVINUS_FLOS', 'Divinus Flos', '', NULL),
  (6519, 'IQ_BLAZING_FLAME_BLAST', 'Blazing Flame Blast', '', NULL),
  (6520, 'WH_WILD_WALK', 'Wild Walk', '', NULL),
  (6521, 'TR_RHYTHMICAL_WAVE', 'Rhythmical Wave', '', NULL),
  (6522, 'ABC_ABYSS_FLAME_ATK', 'Abyss Flame Attack', '', NULL),
  (8001, 'HLIF_HEAL', 'Healing Touch', '', NULL),
  (8002, 'HLIF_AVOID', 'Avoid', '', NULL),
  (8003, 'HLIF_BRAIN', 'Brain Surgery', '', NULL),
  (8004, 'HLIF_CHANGE', 'Change', '', NULL),
  (8005, 'HAMI_CASTLE', 'Castling', '', NULL),
  (8006, 'HAMI_DEFENCE', 'Defense', '', NULL),
  (8007, 'HAMI_SKIN', 'Adamantium Skin', '', NULL),
  (8008, 'HAMI_BLOODLUST', 'Bloodlust', '', NULL),
  (8009, 'HFLI_MOON', 'Moonlight', '', NULL),
  (8010, 'HFLI_FLEET', 'Fleeting Move', '', NULL),
  (8011, 'HFLI_SPEED', 'Speed', '', NULL),
  (8012, 'HFLI_SBR44', 'S.B.R.44', '', NULL),
  (8013, 'HVAN_CAPRICE', 'Caprice', '', NULL),
  (8014, 'HVAN_CHAOTIC', 'Benediction of Chaos', '', NULL),
  (8015, 'HVAN_INSTRUCT', 'Instruct', '', NULL),
  (8016, 'HVAN_EXPLOSION', 'Bio Explosion', '', NULL),
  (8018, 'MH_SUMMON_LEGION', 'Summon Legion', '', NULL),
  (8019, 'MH_NEEDLE_OF_PARALYZE', 'Needle of Paralyze', '', NULL),
  (8020, 'MH_POISON_MIST', 'Poison Mist', '', NULL),
  (8021, 'MH_PAIN_KILLER', 'Pain Killer', '', NULL),
  (8022, 'MH_LIGHT_OF_REGENE', 'Light of Regene', '', NULL),
  (8023, 'MH_OVERED_BOOST', 'Overed Boost', '', NULL),
  (8024, 'MH_ERASER_CUTTER', 'Eraser Cutter', '', NULL),
  (8025, 'MH_XENO_SLASHER', 'Xeno Slasher', '', NULL),
  (8026, 'MH_SILENT_BREEZE', 'Silent Breeze', '', NULL),
  (8027, 'MH_STYLE_CHANGE', 'Style Change', '', NULL),
  (8028, 'MH_SONIC_CRAW', 'Sonic Claw', '', NULL),
  (8029, 'MH_SILVERVEIN_RUSH', 'Silver Bain Rush', '', NULL),
  (8030, 'MH_MIDNIGHT_FRENZY', 'Midnight Frenzy', '', NULL),
  (8031, 'MH_STAHL_HORN', 'Steel Horn', '', NULL),
  (8032, 'MH_GOLDENE_FERSE', 'Golden Heel', '', NULL),
  (8033, 'MH_STEINWAND', 'Stone Wall', '', NULL),
  (8034, 'MH_HEILIGE_STANGE', 'Holy Pole', '', NULL),
  (8035, 'MH_ANGRIFFS_MODUS', 'Attack Mode', '', NULL),
  (8036, 'MH_TINDER_BREAKER', 'Tinder Breaker', '', NULL),
  (8037, 'MH_CBC', 'Continual Break Combo', '', NULL),
  (8038, 'MH_EQC', 'Eternal Quick Combo', '', NULL),
  (8039, 'MH_MAGMA_FLOW', 'Magma Flow', '', NULL),
  (8040, 'MH_GRANITIC_ARMOR', 'Granitic Armor', '', NULL),
  (8041, 'MH_LAVA_SLIDE', 'Lava Slide', '', NULL),
  (8042, 'MH_PYROCLASTIC', 'Pyroclastic', '', NULL),
  (8043, 'MH_VOLCANIC_ASH', 'Volcanic Ash', '', NULL),
  (8044, 'MH_BLAST_FORGE', 'Blast Forge', '', NULL),
  (8045, 'MH_TEMPERING', 'Tempering', '', NULL),
  (8046, 'MH_CLASSY_FLUTTER', 'Classy Flutter', '', NULL),
  (8047, 'MH_TWISTER_CUTTER', 'Twister Cutter', '', NULL),
  (8048, 'MH_ABSOLUTE_ZEPHYR', 'Absolute Zephyr', '', NULL),
  (8049, 'MH_BRUSHUP_CLAW', 'Brushup Claw', '', NULL),
  (8050, 'MH_BLAZING_AND_FURIOUS', 'Blazing And Furious', '', NULL),
  (8051, 'MH_THE_ONE_FIGHTER_RISES', 'The One Fighter Rises', '', NULL),
  (8052, 'MH_POLISHING_NEEDLE', 'Polishing Needle', '', NULL),
  (8053, 'MH_TOXIN_OF_MANDARA', 'Toxin Of Mandara', '', NULL),
  (8054, 'MH_NEEDLE_STINGER', 'Needle Stinger', '', NULL),
  (8055, 'MH_LICHT_GEHORN', 'Licht Gehorn', '', NULL),
  (8056, 'MH_GLANZEN_SPIES', 'Glanzen Spies', '', NULL),
  (8057, 'MH_HEILIGE_PFERD', 'Heilige Pferd', '', NULL),
  (8058, 'MH_GOLDENE_TONE', 'Goldene Tone', '', NULL),
  (8059, 'MH_BLAZING_LAVA', 'Blazing Lava', '', NULL),
  (8201, 'MS_BASH', 'Bash', '', NULL),
  (8202, 'MS_MAGNUM', 'Magnum_Break', '', NULL),
  (8203, 'MS_BOWLINGBASH', 'Bowling_Bash', '', NULL),
  (8204, 'MS_PARRYING', 'Parry', '', NULL),
  (8205, 'MS_REFLECTSHIELD', 'Shield_Reflect', '', NULL),
  (8206, 'MS_BERSERK', 'Frenzy', '', NULL),
  (8207, 'MA_DOUBLE', 'Double_Strafe', '', NULL),
  (8208, 'MA_SHOWER', 'Arrow_Shower', '', NULL),
  (8209, 'MA_SKIDTRAP', 'Skid_Trap', '', NULL),
  (8210, 'MA_LANDMINE', 'Land_Mine', '', NULL),
  (8211, 'MA_SANDMAN', 'Sandman', '', NULL),
  (8212, 'MA_FREEZINGTRAP', 'Freezing_Trap', '', NULL),
  (8213, 'MA_REMOVETRAP', 'Remove_Trap', '', NULL),
  (8214, 'MA_CHARGEARROW', 'Arrow_Repel', '', NULL),
  (8215, 'MA_SHARPSHOOTING', 'Focused_Arrow_Strike', '', NULL),
  (8216, 'ML_PIERCE', 'Pierce', '', NULL),
  (8217, 'ML_BRANDISH', 'Brandish_Spear', '', NULL),
  (8218, 'ML_SPIRALPIERCE', 'Spiral_Pierce', '', NULL),
  (8219, 'ML_DEFENDER', 'Defending_Aura', '', NULL),
  (8220, 'ML_AUTOGUARD', 'Guard', '', NULL),
  (8221, 'ML_DEVOTION', 'Sacrifice', '', NULL),
  (8222, 'MER_MAGNIFICAT', 'Magnificat', '', NULL),
  (8223, 'MER_QUICKEN', 'Two-Hand_Quicken', '', NULL),
  (8224, 'MER_SIGHT', 'Sight', '', NULL),
  (8225, 'MER_CRASH', 'Crash', '', NULL),
  (8226, 'MER_REGAIN', 'Regain', '', NULL),
  (8227, 'MER_TENDER', 'Tender', '', NULL),
  (8228, 'MER_BENEDICTION', 'Benediction', '', NULL),
  (8229, 'MER_RECUPERATE', 'Recuperate', '', NULL),
  (8230, 'MER_MENTALCURE', 'Mental_Cure', '', NULL),
  (8231, 'MER_COMPRESS', 'Compress', '', NULL),
  (8232, 'MER_PROVOKE', 'Provoke', '', NULL),
  (8233, 'MER_AUTOBERSERK', 'Berserk', '', NULL),
  (8234, 'MER_DECAGI', 'Decrease_AGI', '', NULL),
  (8235, 'MER_SCAPEGOAT', 'Scapegoat', '', NULL),
  (8236, 'MER_LEXDIVINA', 'Lex_Divina', '', NULL),
  (8237, 'MER_ESTIMATION', 'Sense', '', NULL),
  (8238, 'MER_KYRIE', 'Kyrie Eleison', '', NULL),
  (8239, 'MER_BLESSING', 'Blessing', '', NULL),
  (8240, 'MER_INCAGI', 'Increase Agility', '', NULL),
  (8241, 'MER_INVINCIBLEOFF2', 'Mind Blaster', '', NULL),
  (8401, 'EL_CIRCLE_OF_FIRE', 'Circle of Fire', '', NULL),
  (8402, 'EL_FIRE_CLOAK', 'Fire Cloak', '', NULL),
  (8403, 'EL_FIRE_MANTLE', 'Fire Mantle', '', NULL),
  (8404, 'EL_WATER_SCREEN', 'Water Screen', '', NULL),
  (8405, 'EL_WATER_DROP', 'Water Drop', '', NULL),
  (8406, 'EL_WATER_BARRIER', 'Water Barrier', '', NULL),
  (8407, 'EL_WIND_STEP', 'Wind Step', '', NULL),
  (8408, 'EL_WIND_CURTAIN', 'Wind Curtain', '', NULL),
  (8409, 'EL_ZEPHYR', 'Zephyr', '', NULL),
  (8410, 'EL_SOLID_SKIN', 'Solid Skin', '', NULL),
  (8411, 'EL_STONE_SHIELD', 'Stone Shield', '', NULL),
  (8412, 'EL_POWER_OF_GAIA', 'Power of Gaia', '', NULL),
  (8413, 'EL_PYROTECHNIC', 'Pyrotechnic', '', NULL),
  (8414, 'EL_HEATER', 'Heater', '', NULL),
  (8415, 'EL_TROPIC', 'Tropic', '', NULL),
  (8416, 'EL_AQUAPLAY', 'Aqua Play', '', NULL),
  (8417, 'EL_COOLER', 'Cooler', '', NULL),
  (8418, 'EL_CHILLY_AIR', 'Cool Air', '', NULL),
  (8419, 'EL_GUST', 'Gust', '', NULL),
  (8420, 'EL_BLAST', 'Blast', '', NULL),
  (8421, 'EL_WILD_STORM', 'Wild Storm', '', NULL),
  (8422, 'EL_PETROLOGY', 'Petrology', '', NULL),
  (8423, 'EL_CURSED_SOIL', 'Cursed Soil', '', NULL),
  (8424, 'EL_UPHEAVAL', 'Upheaval', '', NULL),
  (8425, 'EL_FIRE_ARROW', 'Fire Arrow', '', NULL),
  (8426, 'EL_FIRE_BOMB', 'Fire Bomb', '', NULL),
  (8427, 'EL_FIRE_BOMB_ATK', 'Fire Bomb Attack', '', NULL),
  (8428, 'EL_FIRE_WAVE', 'Fire Wave', '', NULL),
  (8429, 'EL_FIRE_WAVE_ATK', 'Fire Wave Attack', '', NULL),
  (8430, 'EL_ICE_NEEDLE', 'Ice Needle', '', NULL),
  (8431, 'EL_WATER_SCREW', 'Water Screw', '', NULL),
  (8432, 'EL_WATER_SCREW_ATK', 'Water Screw Attack', '', NULL),
  (8433, 'EL_TIDAL_WEAPON', 'Tidal Weapon', '', NULL),
  (8434, 'EL_WIND_SLASH', 'Wind Slasher', '', NULL),
  (8435, 'EL_HURRICANE', 'Hurricane Rage', '', NULL),
  (8436, 'EL_HURRICANE_ATK', 'Hurricane Rage Attack', '', NULL),
  (8437, 'EL_TYPOON_MIS', 'Typhoon Missile', '', NULL),
  (8438, 'EL_TYPOON_MIS_ATK', 'Typhoon Missile Attack', '', NULL),
  (8439, 'EL_STONE_HAMMER', 'Stone Hammer', '', NULL),
  (8440, 'EL_ROCK_CRUSHER', 'Rock Launcher', '', NULL),
  (8441, 'EL_ROCK_CRUSHER_ATK', 'Rock Launcher Attack', '', NULL),
  (8442, 'EL_STONE_RAIN', 'Stone Rain', '', NULL),
  (8443, 'EM_EL_FLAMETECHNIC', 'Flame Technic', '', NULL),
  (8444, 'EM_EL_FLAMEARMOR', 'Flame Armor', '', NULL),
  (8445, 'EM_EL_FLAMEROCK', 'Flame Rock', '', NULL),
  (8446, 'EM_EL_COLD_FORCE', 'Cold Force', '', NULL),
  (8447, 'EM_EL_CRYSTAL_ARMOR', 'Crystal Armor', '', NULL),
  (8448, 'EM_EL_AGE_OF_ICE', 'Age Of Ice', '', NULL),
  (8449, 'EM_EL_GRACE_BREEZE', 'Grace Breeze', '', NULL),
  (8450, 'EM_EL_EYES_OF_STORM', 'Eyes Of Storm', '', NULL),
  (8451, 'EM_EL_STORM_WIND', 'Storm Wind', '', NULL),
  (8452, 'EM_EL_EARTH_CARE', 'Earth Care', '', NULL),
  (8453, 'EM_EL_STRONG_PROTECTION', 'Strong Protection', '', NULL),
  (8454, 'EM_EL_AVALANCHE', 'Avalanche', '', NULL),
  (8455, 'EM_EL_DEEP_POISONING', 'Deep Poisoning', '', NULL),
  (8456, 'EM_EL_POISON_SHIELD', 'Poison Shield', '', NULL),
  (8457, 'EM_EL_DEADLY_POISON', 'Deadly Poison', '', NULL),
  (8601, 'ABR_BATTLE_BUSTER', 'Battle Buster', '', NULL),
  (8602, 'ABR_DUAL_CANNON_FIRE', 'Dual Cannon Fire', '', NULL),
  (8603, 'ABR_NET_REPAIR', 'Net Repair', '', NULL),
  (8604, 'ABR_NET_SUPPORT', 'Net Support', '', NULL),
  (8605, 'ABR_INFINITY_BUSTER', 'Infinity Buster', '', NULL),
  (10000, 'GD_APPROVAL', 'Official Guild Approval', '', NULL),
  (10001, 'GD_KAFRACONTRACT', 'Kafra Contract', '', NULL),
  (10002, 'GD_GUARDRESEARCH', 'Guardian Research', '', NULL),
  (10003, 'GD_GUARDUP', 'Strengthen Guardians', '', NULL),
  (10004, 'GD_EXTENSION', 'Guild Extension', '', NULL),
  (10005, 'GD_GLORYGUILD', 'Guild''s Glory', '', NULL),
  (10006, 'GD_LEADERSHIP', 'Great Leadership', '', NULL),
  (10007, 'GD_GLORYWOUNDS', 'Glorious Wounds', '', NULL),
  (10008, 'GD_SOULCOLD', 'Cold Heart', '', NULL),
  (10009, 'GD_HAWKEYES', 'Sharp Gaze', '', NULL),
  (10010, 'GD_BATTLEORDER', 'Battle Orders', '', NULL),
  (10011, 'GD_REGENERATION', 'Regeneration', '', NULL),
  (10012, 'GD_RESTORE', 'Restoration', '', NULL),
  (10013, 'GD_EMERGENCYCALL', 'Urgent Call', '', NULL),
  (10014, 'GD_DEVELOPMENT', 'Permanent Development', '', NULL),
  (10015, 'GD_ITEMEMERGENCYCALL', 'Item Emergency Call', '', NULL),
  (10016, 'GD_GUILD_STORAGE', 'Guild Storage Expansion', '', NULL),
  (10017, 'GD_CHARGESHOUT_FLAG', 'Charge Shout Flag', '', NULL),
  (10018, 'GD_CHARGESHOUT_BEATING', 'Charge Shout Beating', '', NULL),
  (10019, 'GD_EMERGENCY_MOVE', 'Emergency Move', '', NULL)
ON CONFLICT (id) DO UPDATE SET
    name   = EXCLUDED.name,
    type   = EXCLUDED.type,
    script = EXCLUDED.script;
